packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-cache/src/types/error-for-client.ts
packages/zero-cache/src/workers/connection.ts

Select appropriate log levels for different types of errors to improve the signal-to-noise ratio in server logs.
Some errors like OwnershipError are used for control flow and some are related to client conditions and do not constitute a problem on the server.

chore(zero-cache): adjust log levels of thrown errors

---

packages/replicache/src/mod.ts

Current workaround is:
```js
function getDefaultPusher() {
const r = new Replicache({ name: "foo", licenseKey: "bar" })
return r.pusher
}
```

Expose `getDefaultPusher`

---

packages/zero-cache/src/server/life-cycle.ts

user-facing workers used to exit with code `0` after draining, but with the new multi-level process tree, the kill signal is reported instead. From the logs, the right thing is happening, so consider this an expected scenario and log as `info` instead of `warn`.

chore(zero-cache): fix log level when user-facing worker exits

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts

Logs show an instance of an assert that should not be possible given the CVR schema constraints (i.e. `clientID` is a foreign key reference):
Indeed, the data in the DB looks well formed:
So this incidence is a bit of a mystery. Add more logging to debug if/when it happens again.

chore(zero-cache): log more information when a client is not found

---

packages/zero-cache/src/server/life-cycle.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/multi/main.ts

Reverts #3424 as that did not fix the issue.
Instead, have each process managing worker (`multi/main.ts` and `server/main.ts`) await its process manager before exiting. 
This avoids sending an additional `SIGTERM` to child processes when they are still draining.

fix(zero-cache): fix graceful shutdown by awaiting process manager before exiting

---

packages/zero-cache/src/db/migration.ts
packages/zero-cache/src/services/change-streamer/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-streamer/pg/change-source.ts
packages/zero-cache/src/services/change-streamer/pg/schema/init.pg-test.ts
packages/zero-cache/src/services/change-streamer/pg/schema/init.ts
packages/zero-cache/src/services/running-state.ts

An addendum to #3237, this change in particular catches the case where upstream tables have been cleared but the replication slot still exists, e.g.
https://discord.com/channels/830183651022471199/1319617557488992266/1319698226093363260
Check to ensure that the upstream shard is initialized when starting up `zero-cache`. If it is not, it fails fast with a similar error message prompting the developer to wipe the replica and re-sync:

fix(zero-cache): check shard initialized before updating

---

packages/zero-cache/src/server/life-cycle.ts

The replication-manager isn't drained like the view-syncer; it's "graceful" shutdown is initiated by the pg_terminate_backend() command from the new replication manager.
Fix the process manager to understand that at the multi-tenant level. This should properly classify the exit as an 'info' rather than 'error' level event.

fix(zero-cache): fix log level / exit code when replication-manager exits

---

prod/templates/sandbox/template.yml

Another configuration that we need to carry over from the previous incarnation of sandbox. 
Requests to the `change-streamer` are long-lived websockets and thus should not be subject to timeouts.

fix(sandbox): disable timeouts for requests to change-streamer

---

prod/templates/sandbox/template.yml

Reduce the health check interval so that servers are considered healthy earlier. Keep the start period long, though, to allow for slow startup due to large `litestream restore` operations.
This is an experiment to see if we can reduce the occurrence of 503's from view-syncers to change-streamers when the latter are updated.

chore(sandbox): reduce health check interval

---

prod/templates/sandbox/template.yml

Follow the workaround described in https://github.com/aws/containers-roadmap/issues/2334#issuecomment-2285926075 to delay ServiceConnect requests to the `change-streamer` until it is healthy.
Once this behavior is vetted, the replication-manager will be modified to delay handing off the replication stream until the first subscription is received (signaling that ServiceConnect has considered the task healthy).

feat(sandbox): delay service connect requests on change-streamer health

---

packages/zero-cache/src/services/change-streamer/change-streamer-http.test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.ts
packages/zero-cache/src/services/change-streamer/change-streamer.ts
packages/zero-cache/src/services/replicator/incremental-sync.pg-test.ts
packages/zero-cache/src/services/replicator/incremental-sync.ts
packages/zero-cache/src/services/replicator/replicator.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
prod/templates/template.yml

An initializing `replication-manager` effectively kills the previous `replication-manager` when subscribing to the Postgres replication slot (as there can be only one subscriber).
If routing layers (from `view-syncer` to `replication-manager`) have not been updated to begin sending traffic to the new `replication-manager`, this can result in routing errors (e.g. 503s in AWS ServiceConnect) until the new `replication-manager` is recognized as healthy, during which replication is essentially paused.
This change reduces this gap by:
* Delaying ServiceConnect routing to the `replication-manager` until the container is healthy. This is an AWS-specific [workaround / trick](https://github.com/aws/containers-roadmap/issues/2334#issuecomment-2285926075) that has already been vetted in sandbox …

feat(zero-cache): tighter replication-manager handoff

---

package-lock.json
packages/shared/src/tool/vitest-config.ts
packages/zql/package.json

this was used in early benchmarking of ivm1 to test client side db impl vs sqlite-in-browser. No longer used.

chore(zero): rm wa-sqlite

---

package-lock.json
packages/shared/package.json
packages/shared/src/tool/get-external-from-package-json.js
packages/zero/tool/build.js

- Replace use of `URL(...).pathname` with `node:path.resolve` to address path name differences on Windows
- update `pkg-up` dependency to `package-up` (package got renamed)

Fixes windows build and deprecation of deprecation of pkg-up package

---

packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/services/change-streamer/pg/change-source.ts
packages/zero-cache/src/services/change-streamer/pg/schema/init.ts
packages/zero-cache/src/services/change-streamer/schema/tables.ts

Automatically wipe the replica and rerun initial sync if the upstream DB has been reset (e.g. replication slot is missing, or shard schema is gone). 
This handles a common pattern of developers clearing their upstream DB but not clearing their replica file. The system now recovers from this automatically by clearing the replica file and retrying, obviating the need for developers to know about the replica file (e.g. it may be in a docker volume).

feat(zero-cache): auto-reset replica if upstream is reset

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/snapshotter.test.ts
packages/zero-cache/src/services/view-syncer/snapshotter.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

Truncates were initially processed by converting the TRUNCATE event into a sequence of `del` patches that were to be pushed through IVM pipelines. This never worked, as the generation of this sequence opened an iterator over the `prev` database handle, and that database needs to be concurrently advanced by the IVM push.
Instead, truncates are now processed in the same manner as that of schema changes; the advancement is aborted and pipelines are rehydrated from the `curr` database handle.

fix(zero-cache): fix replication of TRUNCATE statements

---

packages/zero-cache/src/workers/connection.ts
packages/zero-protocol/src/protocol-version.ts

Developers seem to hit protocol version mismatches often, usually when running client code that's newer than server code:
https://discord.com/channels/830183651022471199/1288232858795769917/1321105123224715315
https://discord.com/channels/830183651022471199/1322659299717287946/1322706138126614630
Improve the error message returned by the `zero-cache` to specify which component should be updated to a newer release.
Also make the deprecation of older protocol versions explicit with a `MIN_SERVER_SUPPORTED_PROTOCOL_VERSION` constant, rather than forcing `PROTOCOL_VERSION -  1`. Since protocol version deprecation generally involves manual cleanup (i.e. of old code), the support boundary should also be manually updated.

feat(zero-cache): improve the error message for unsupported protocol versions

---

packages/zero-cache/src/services/change-streamer/pg/change-source.test.ts
packages/zero-cache/src/services/change-streamer/pg/change-source.ts

Postgres `keepalive` messages contain the LSN of the end of the WAL:
https://www.postgresql.org/docs/current/protocol-replication.html#PROTOCOL-REPLICATION-PRIMARY-KEEPALIVE-MESSAGE
The replication streaming logic previously only responded with the LSN of its latest processed replication message. In particular, it is important not to ACK any received data that was not successfully persisted by the `change-streamer`.
However, if all replicated messages have been processed and acknowledged, the end-of-WAL LSN of subsequent keepalive messages must be acknowledged in order to allow postgres to clean up subsequent WAL entries (i.e. that are unrelated to the logical replication stream). Failure to do so results in potentially unbounded WAL growth until a new replication message arrives on the …

fix(zero-cache): fix acknowledgement of pg keepalives

---

apps/zbugs/src/pages/issue/comment.tsx
apps/zbugs/src/pages/issue/issue-page.tsx
packages/zql/src/query/query.test.ts
packages/zql/src/query/query.ts
packages/zqlite/src/query.test.ts

This came up from a user here: https://discord.com/channels/830183651022471199/1322274277453594705/1322276660627898470
The question was how they could derive the types to use for `props` in a component from a query.

feat(zql): fix `IS` to take null, fix `Row` to take `Query`

---

packages/zero-cache/src/services/change-streamer/pg/change-source.ts

Developers often mistakenly run multiple `zero-cache` instances pointed to the same upstream db. This results in flapping, where the instances continually kill each other in order to take over the replication slot.
Log the reason for shutdown so that it is clearer what's going on.

feat(zero-cache): log reason when shutting down because of another zero-cache

---

packages/zero-cache/src/services/change-streamer/pg/change-source.ts

"shutdown signal received (e.g. another zero-cache taking over the replication stream)"

chore(zero-cache): betterer shutdown message

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/server/multi/config.test.ts
packages/zero-cache/src/services/change-streamer/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-streamer/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-streamer/pg/change-source.ts
packages/zero-cache/src/services/change-streamer/pg/initial-sync.pg-test.ts
packages/zero-cache/src/services/change-streamer/pg/initial-sync.ts
packages/zero-cache/src/services/change-streamer/pg/sync-schema.pg-test.ts
packages/zero-cache/src/services/change-streamer/pg/sync-schema.ts

Make configurable the number of table copy workers, and the size of the row batches fetched during initial sync. Decrease the default batch size from 100,000 rows to 10,000 rows.

feat(zero-cache): make initial-sync parameters configurable

---

packages/zero-cache/src/server/multi/tenant-dispatcher.ts
packages/zero-cache/src/services/dispatcher/websocket-handoff.test.ts
packages/zero-cache/src/services/dispatcher/websocket-handoff.ts

An error during tenant dispatch was causing the server to crash:
https://discord.com/channels/830183651022471199/1324367282952077352/1324368361471348749
This was due to an Error thrown from the `ws` library when the close message exceeds the websocket spec of 123 bytes.
```
/Users/ocean/roci/mono/node_modules/ws/lib/sender.js:195
throw new RangeError('The message must not be greater than 123 bytes');
^
```
Make the error message smaller by only including the host and path, and also truncate long error messages at the library level.

fix(zero-cache): fix tenant dispatch errors

---

packages/zero-cache/src/types/processes.ts

Workers crash on windows if they don't have a place to pipe their output. Fix that.

feat(zero-cache): send worker io to parent process

---

packages/zero-advanced/src/mod.ts
packages/zero-react/src/use-query.tsx
packages/zero-solid/src/solid-view.test.ts
packages/zero-solid/src/solid-view.ts
packages/zero-solid/src/use-query.ts

Bring zero-solid up to par with React features added in https://github.com/rocicorp/mono/pull/3229/files

feat(zero-solid): Add resultType support to zero-solid

---

packages/zero-schema/src/column.ts

This adds strong typing to the optional property passed into e.g. `column.string(false)`, instead of `optional: boolean`
```
const _demo = string(false)
//     ^ { type: 'string', optional: false, customType: string }
const _demo2 = string()
//     ^ { type: 'string', optional: false, customType: string }
const _demo3 = string(true)
//     ^ { type: 'string', optional: true, customType: string }
```

feat(schema): added strong optional typing

---

apps/zbugs/package.json
apps/zbugs/src/components/login-provider.tsx
package-lock.json
packages/zero-react/package.json
packages/zero-react/src/use-query.tsx

https://bugs.rocicorp.dev/issue/3388
This is to allow zero-react to work prior to the release of react 18.

fix(zero-react): useSyncExternalStore shim

---

packages/zero-schema/src/schema.test.ts
packages/zero-schema/src/schema.ts

https://bugs.rocicorp.dev/issue/3370
This is to catch typos like issue vs issues which is a pretty common mistake.

feat(zero-schema): Add a runtime check for tableName

---

packages/zero/src/zero-cache-dev.ts

Flags parsing needs to `allowPartial` for multi-tenant flag parsing logic.
https://discord.com/channels/830183651022471199/1325206399218614282/1326159204293152811

fix(zero-cache-dev): fix zero-cache-dev for multitenant

---

packages/zero-cache/src/services/change-streamer/pg/schema/shard.pg-test.ts
packages/zero-cache/src/test/db.ts
packages/zero-cache/test/pg-container-setup.ts
packages/zero-cache/vitest.workspace.ts

Adds a `CUSTOM_PG=postgresql?... npx run tests` option for running the `zero-cache` tests on a custom PG instance, such as an Aurora instance.
Fix a tests to clean up global state, so that it can be rerun on the same pg instance multiple times.

chore(zero-cache): api to run unit tests on custom pg instance

---

package-lock.json
packages/shared/package.json
packages/shared/src/options.test.ts
packages/shared/src/options.ts
packages/zero-cache/package.json
packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/server/multi/config.test.ts
packages/zero/package.json

This PR replaces usages of `strip-ansi` with the [native node implementation](https://nodejs.org/api/util.html#utilstripvtcontrolcharactersstr) as part of the [e18e](https://e18e.dev) initiative.
`stripVTControlCharacter` is available from node v16.11.0 which should be fine as `@rocicorp/zero` requires v20

chore(zero,zero-cache): Replace strip-ansi with native impl

---

packages/zero-client/src/client/zero-poke-handler.test.ts
packages/zero-client/src/client/zero-poke-handler.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/protocol-version.ts
packages/zero-protocol/src/row-patch.ts

Start the migration to send the full row in `del` patches to make the protocol agnostic to the primary key.
* A new (optional) `value` field is introduced to hold the full row value
* `id` is made optional
* server must set one or the other
* client accepts either; the logic for extracting the key from the full row is already in place
TODO: Remove obsolete `update` patch.

chore(zero-protocol): bump to v4, start renaming delPatch.id to delPatch.value

---

package-lock.json
packages/zero-solid/package.json
packages/zero-solid/src/solid-view.test.ts
packages/zero-solid/src/solid-view.ts
packages/zero-solid/src/use-query.test.ts
packages/zero-solid/src/use-query.ts

BREAKING CHANGE!
Previously it returned an accessor of a tuple which is not ergonomic.
It forced you to do:
```tsx
const rows = () = useQuery(q)()[0]; // yes you need the ()[0]
</List items={rows()}/>
// or
const res = useQuery(q);
</List items={rows()[0]}/>
```
With this change you can do:
```tsx
const [rows] = useQuery(q);
</List items={rows()}/>
```

fix(zero-solid)!: useQuery return tuple of Accessor

---

apps/zbugs/package.json
package-lock.json

```ts
npm run analyze
```
t
One quick win: we could replace `b+tree` with the `treap` we were using a ways back.

feat(zbugs): add bundle analyzer so we can start paring down size

---

packages/zero-schema/src/normalize-table-schema.ts
packages/zero-schema/src/normalized-schema.test.ts
packages/zero-schema/src/normalized-schema.ts
packages/zero-schema/src/schema.test.ts
packages/zero-schema/src/schema.ts

zbugs: [Potential for a better error message when a table is referenced in a relationship but not included in createSchema](https://bugs.rocicorp.dev/issue/3370)
Thank you @arv for the work on https://github.com/rocicorp/mono/pull/3477. It pointed me in the direction of where to look code wise. I wanted to expand the work that was done to resolve the issue I ran into where defining a `destSchema` for a table that isn't referenced in `schema.tables` causes an error.
I added test cases for two potential ways to have a missing table. If anyone can think of other scenarios I can gladly write more tests.
My only question about adding this, while I think it improves the DX and will help people to ensure their schema is valid, is there any concern about runtime cost and having `createSchema` …

feat(zero-schema): Add runtime assertion for all relationship tables in createSchema

---

packages/zero-cache/src/server/multi/config.test.ts
packages/zero-cache/src/server/multi/config.ts
packages/zero-cache/src/server/multi/main.ts

Require that each tenant in the `tenants-json` as fields that need to be unique to each tenant.
(Note that `ZERO_UPSTREAM_DB` is not included because that can be shared provided that tenants have unique `ZERO_SHARD_ID`s.)
#papercut: https://discord.com/channels/830183651022471199/1326923532671783036/1326925731900559416

feat(zero-cache): require that each tenant define its necessarily unique fields

---

packages/zero-cache/src/server/multi/main.ts

Propagate the parent's ENV vars to tenant zero-caches, so that variables such as `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` find their way to the `litestream` subprocess.

fix(zero-cache): propagate env varz to tenants

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/multi/main.ts
prod/templates/sandbox/template.yml
prod/templates/template.yml

This prevents bad deployments from getting stuck. (This was enabled pre-CloudFormation)
Also give our containers the default (5 minute) grace period for becoming health. Not sure why it was reduced to such a low value.

prod(zero-cache): enable deployment circuit breaker

---

prod/templates/sandbox/template.yml
prod/templates/template.yml

This should not result in a behavioral difference in Fargate based on our deployment configuration, but enabling it reflects the intention.
https://stackoverflow.com/questions/74269206/ecs-fargate-expected-deployment-circuit-breaker-rollback-behaviour

prod(zero-cache): enable circuit breaker rollback

---

packages/replicache/src/get-default-puller.ts
packages/replicache/src/mod.ts
packages/replicache/src/puller.ts
packages/replicache/src/sync/pull.test.ts
packages/replicache/src/sync/pull.ts
packages/replicache/src/sync/push.ts
packages/zero-client/src/client/zero-rate.test.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts

BREAKING CHANGE!
This removes support for the old pull and push formats.
- PullResponseOKV0
- PullResponseV0
- PullerResultV0
- MutationV0
- PushRequestV0
It also removes the V1 types in favor of the non versioned ones now that there is only one version.

chore(replicache)!: Remove Pull/Push V0

---

packages/zero-cache/src/services/view-syncer/pipeline-driver.ts

Include the list of known tables when an unknown table is specified in a query.
```json
{
"name":"ServerError",
"message":"Internal: Error: table 'users' is not one of: comment,emoji,issue,issueLabel,label,user,userPref,viewState",
"stack":"ServerError: Internal: Error: table 'users' is not one of: comment,emoji,issue,issueLabel,label,user,userPref,viewState\n"
...
} 
```
#papercut: https://discord.com/channels/830183651022471199/1288232858795769917/threads/1323147352537829437

feat(zero-cache): improve error message for unknown tables

---

packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/protocol/current/control.ts
packages/zero-cache/src/services/change-source/protocol/current/downstream.ts
packages/zero-cache/src/services/change-source/protocol/version.test.ts

The first step in migrating to replica schema v2 (https://bugs.rocicorp.dev/issue/3404).
The ChangeSource and ChangeStreamer now use the `commitLSN` for the `commitWatermark` of `begin` messages and the `watermark` of `commit` messages. The former are not used yet, but will be in a subsequent step.

chore(zero-cache): add the commit watermark to "begin" messages

---

packages/zero-cache/src/types/pg.ts
prod/templates/sandbox/template.yml

Adjust connection counts to fit into the `max_connections` of 2000, and increase the connect timeout to handle slow startup when scaling from zero.

prod(sandbox): adjust connection parameters for aurora-based CVR db

---

packages/zero-cache/src/services/change-source/protocol/current/downstream.ts
packages/zero-cache/src/services/change-source/protocol/version.test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.pg-test.ts
packages/zero-cache/src/services/change-streamer/forwarder.test.ts
packages/zero-cache/src/services/change-streamer/storer.pg-test.ts
packages/zero-cache/src/services/change-streamer/storer.ts
packages/zero-cache/src/services/change-streamer/subscriber.test.ts
packages/zero-cache/src/services/replicator/incremental-sync.message-processor.test.ts
packages/zero-cache/src/services/replicator/incremental-sync.pg-test.ts
packages/zero-cache/src/services/replicator/test-utils.ts

This is a followup to #3513 to complete the migration of the change protocol to include commit watermarks in the `["begin", ... ]` message.
They are not used yet; this is just a protocol change, which had to be done in two steps because it is sent over the wire between `view-syncer`s and the `replication-manager`.

chore(zero-cache): finish migration of change protocol to include commit watermarks

---

packages/zero/package.json
packages/zero/tool/build.js

The server part of zero is not bundled using esbuild. It is just compiled using tsc and the code structure maps the source code structure.
Followup to https://github.com/rocicorp/mono/pull/3491

fix(zero): Do not "bundle" change-protocol

---

packages/zero-cache/src/server/main.ts

Only run a replicator in "serving-copy" mode if running all of syncer, change-streamer, and litestream. (Essentially, only in dev). Production view-syncers need not make a copy since they are running litestream backup.

fix(zero-cache): avoid unnecesarily running serving-copy

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.pg-test.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.ts
packages/zero-cache/src/services/replicator/incremental-sync.message-processor.test.ts
packages/zero-cache/src/services/replicator/incremental-sync.pg-test.ts
packages/zero-cache/src/services/replicator/incremental-sync.ts
packages/zero-cache/src/services/replicator/schema/replication-state.test.ts
packages/zero-cache/src/services/replicator/schema/replication-state.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/schema/cvr.ts
packages/zero-cache/src/services/view-syncer/snapshotter.test.ts
packages/zero-cache/src/services/view-syncer/snapshotter.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
prod/templates/sandbox/template.yml
prod/templates/template.yml

Migrate to replica schema v2: https://bugs.rocicorp.dev/issue/3404
Main change:
* Initial sync sets row versions to the LSN at the initial sync point, rather than '00'
* All subsequent transactions get versions from the associated commit LSN, rather than (confusingly) the previous one
Side effect:
* Newly synced replicas are backwards compatible with CVRs from old replicas, as there's no longer ambiguity in what a row's '00' version is. When a CVR hits a new replica, the rows will be re-downloaded (because they have a later version in the new replica), but we no longer need to drop other client state (clients, queries, pending mutations, etc.).
* If a CVR hits an older replica (for whatever reason ... e.g. upstream gets completely wiped and starts the WAL over), we drop it as we do today.

feat(zero-cache): replica schema v2

---

packages/zero-cache/src/services/change-source/pg/initial-sync.ts

Run the `pg_terminate_backend(active_pid)` query before resetting the upstream publications.
If the upstream publications are first reset, this makes the `active_pid`  null for some reason and the terminate fails.

fix(zero-cache): kill subscriber before resync (take 2)

---

packages/zero-client/src/client/options.ts
packages/zero-client/src/client/zero.ts

I couldn't figure out how to test this. I added a test like this to `zero.test.ts` and it behaves as if the storage isn't shared while I can plainly see it is in the real browser. Also couldn't figure out how to open a debugger to test:
```ts
test('storage partioning', async () => {
const schema = {
version: 1,
tables: {
foo: {
columns: {
id: {type: 'string'},
val: {type: 'number'},
},
primaryKey: ['id'],
tableName: 'foo',
},
},
} as const;
const z1 = zeroForTest({
schema,
userID: 'u1',
kvStore: 'idb',
});
await z1.mutate.foo.insert({id: 'a', val: 1});
await z1.close();
const z2 = zeroForTest({
schema,
userID: 'u1',
kvStore: 'idb',
});
const {promise, resolve} = resolver();
const view = z2.query.foo.where('id', 'a').one().materialize();
view.addListener((row, type) => {
console.log(row, …
```

feat(zero-client): Add `storageKey` constructor param.

---

packages/zql/src/ivm/exists.ts
packages/zql/src/ivm/fan-in.ts
packages/zql/src/ivm/filter.ts
packages/zql/src/ivm/join.ts
packages/zql/src/ivm/operator.ts
packages/zql/src/ivm/skip.ts
packages/zql/src/ivm/snitch.ts
packages/zql/src/ivm/take.ts

Instead of having to keep checking if output is set we initialize it to a noop Output object.

chore(zql): add noop output to ivm operators

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/server/life-cycle.test.ts
packages/zero-cache/src/server/life-cycle.ts

Adds an integration test configuration that runs a `view-syncer` zero-cache connecting to a `replication-manager` integration test.

chore(zero-cache): multi-node integration test

---

packages/zero-cache/src/services/dispatcher/websocket-handoff.ts
packages/zero-cache/src/services/replicator/incremental-sync.ts
packages/zero-cache/src/services/replicator/replicator.ts
packages/zero-cache/src/types/ws.test.ts
packages/zero-cache/src/types/ws.ts

Factor out `closeWithProtocolError()` so that it can be reused in another context.
Also delete some vestigial code.

chore(zero-cache): factor out websocket error handling code

---

packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/protocol/current/downstream.ts
packages/zero-cache/src/services/change-source/protocol/current/mod.ts
packages/zero-cache/src/services/change-source/protocol/current/status.ts
packages/zero-cache/src/services/change-source/protocol/current/upstream.ts
packages/zero-cache/src/services/change-source/protocol/version.test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.ts
packages/zero-cache/src/services/change-streamer/storer.pg-test.ts
packages/zero-cache/src/services/change-streamer/storer.ts

Adds a `['status', ..., {watermark: string}]` message to the `change-protocol` that encapsulates the communication of log positions between a ChangeSource and the `zero-cache`.
Move the ack logic previously confined to the Postgres implementation down into the ChangeStreamerService implementation so that it is applicable to all ChangeSource implementations.
@cbnsndwch

feat(zero-cache): define a "status" message for the change-protocol

---

packages/zero-cache/src/services/litestream/commands.ts

This doesn't fix the popups for all of the other Workers (which are created via `fork()`), but we might as well do this for `litestream`, which is invoked via `spawn()`.
https://discord.com/channels/830183651022471199/1288232858795769917/1329188972743622676

chore(zero-cache): set windowsHide for litestream subprocesses

---

packages/zero-cache/src/services/change-source/pg/initial-sync.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/validation.ts

Enums are supported now, but we were incorrectly emitting a warning that they wouldn't be synced.

fix(zero-cache): stop incorrectly warning about enums

---

packages/zqlite/src/table-source.test.ts
packages/zqlite/src/table-source.ts

Remove the requirement of an explicit `PRIMARY KEY` from TableSource.
Instead, rely on the table's `UNIQUE` indexes.
* TableSource is still configured with a "PrimaryKey" for the purposes of uniquely identifying rows. However, this key can be any uniquely indexed set of columns, and need not be an explicit `PRIMARY KEY` (which, in SQLite, mean the same thing, as the [rowid](https://www.sqlite.org/withoutrowid.html) is the only real "primary key").
* Similarly, the `Ordering` check is relaxed to allow an ordering that includes the columns of any unique index, and not necessarily those of the primary key.
https://bugs.rocicorp.dev/issue/3186
https://bugs.rocicorp.dev/issue/3198

feat(zero-cache): allow TableSource to work on tables without a `PRIMARY KEY`

---

apps/zbugs/schema.ts
apps/zbugs/src/comment-query.ts
apps/zbugs/src/pages/issue/issue-page.tsx
apps/zbugs/src/zero-setup.ts
packages/zero-cache/bench/schema.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-cache/src/auth/read-authorizer.test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-schema/src/builder/relationship-builder.ts
packages/zero-schema/src/builder/schema-builder.test.ts
packages/zero-schema/src/schema-config.test.ts
packages/zero-schema/src/schema-config.ts
packages/zero-schema/src/schema.test.ts
packages/zero-schema/src/table-schema.test.ts
packages/zero-schema/src/table-schema.ts
packages/zql/src/query/query-impl.query-kitchen-sink.test.ts
packages/zql/src/query/query-impl.query.test.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.test.ts
packages/zql/src/query/query.ts
packages/zql/src/query/test/test-schemas.ts
packages/zqlite/src/query.test.ts

Example:
```ts
const issueRelationships = relationships(issue, ({many, one}) => ({
labels: many(
{
sourceField: ['id'],
destField: ['issueID'],
destSchema: issueLabel,
},
{
sourceField: ['labelID'],
destField: ['id'],
destSchema: label,
},
),
comments: many({
sourceField: ['id'],
destField: ['issueID'],
destSchema: comment,
}),
creator: one({
sourceField: ['creatorID'],
destField: ['id'],
destSchema: user,
}),
assignee: one({
sourceField: ['assigneeID'],
destField: ['id'],
destSchema: user,
}),
viewState: many({
sourceField: ['id'],
destField: ['issueID'],
destSchema: viewState,
}),
emoji: many({
sourceField: ['id'],
destField: ['subjectID'],
destSchema: emoji,
}),
}));
```
Which allows us to finally drop all those manual `one` calls for relationships that are known to only return one …

feat(zql)!: support `one` and `many` in schema definitions

---

packages/zqlite/src/table-source.test.ts
packages/zqlite/src/table-source.ts

When connecting an Input, select an appropriate `primaryKey` (amongst the table's unique indexes) to for the specified `sort` Ordering. Take will assert that the Ordering contains all of the columns in the primaryKey.
This will also be tested at a higher level (pipeline-driver) in a subsequent PR.

feat(zqlite): select an appriopriate "primary key" for a given sort

---

packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts

Use the "unionKey" as CVR row keys and del-patches to allow clients to see both the old and new primary key.
This facilitates the migration steps outlined in: https://rocicorp.slack.com/archives/C013XFG80JC/p1736376499195429?thread_ts=1736355005.417389&cid=C013XFG80JC

feat(zero-cache): facilitate migrating beetween primary keys

---

packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.ts
packages/zero-cache/src/services/change-source/pg/schema/validation.ts

Fixes: [Support prisma join tables](https://bugs.rocicorp.dev/issue/3198)
For tables without a `PRIMARY KEY`, look for a suitable index to use as the [`REPLICA IDENTITY USING INDEX`](https://www.postgresql.org/docs/current/sql-altertable.html#SQL-ALTERTABLE-REPLICA-IDENTITY):
* unique
* non-partial
* immediate
* non-null columns only
(For example, the [indexes created by Prisma for join tables](https://www.prisma.io/docs/orm/prisma-schema/data-model/relations/many-to-many-relations#implicit-many-to-many-relations) satisfies these criteria)
If found, initial-sync will set the replica identity of the PRIMARY KEY-less table such that it can fully participate in replication and sync.

feat(zero-cache): automaticaly set REPLICA IDENTITY for tables without PKs

---

packages/zero-cache/src/types/processes.ts

Setting `detached: true` for forked processes in windows results in opening separate terminals per child process, and breaks inter-process kill-signals that are needed for proper shutdown.
Setting it to `false` breaks graceful shutdown in non-Windows in that the SIGINT signal is automatically propagated to all child workers, whereas we need to control shutdown of children such that all `user-facing` workers exit before `supporting` workers.
The compromise is to only set `detached` to `true` for non-Windows environments.

fix(zero-cache): do not detach forked processes in windows

---

packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zqlite/src/table-source.test.ts
packages/zqlite/src/table-source.ts

For client catchup. The CVR rows keys may differ from the TableSource row keys, so the latter must be able to look up rows by any row key.

fix(zero-cache): fix client catchup

---

prod/templates/template.yml

Resync the prod zbugs replica to refresh everyone's CVRs. 
The theory on the current [(blank page) production issue](https://discord.com/channels/830183651022471199/1288232858795769917/1330306654700437545) is that some bad CVRs were created in the midst of all of the index / key changes that were landing last night.

prod(zbugs): resync prod replica

---

packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.ts

Completes [support for prisma join tables](https://bugs.rocicorp.dev/issue/3198)
A supplement to #3559, this PR adds `REPLICA IDENTITY` to eligibile tables without a primary key (e.g. prisma join tables) that are created after initial sync.

feat(zero-cache): set REPLICA IDENTITIES for tables created after initial sync

---

.github/workflows/bencher-benchmarks-pr.yml
.github/workflows/bencher-benchmarks.yml

Instead of only using max versions of we can use max sample size. This keeps the whole plot but only uses the last report and the current report for the alerts.

chore(zero): Fix file size threshold

---

packages/zqlite/src/table-source.ts

Improve the error message when an unknown columns is encountered in IVM / write authorizer, use the term "synced columns" instead of "Postgres" to be more specific about what the column is missing from.
https://discord.com/channels/830183651022471199/830183651022471202/1330784397439406171

chore(zero-cache): improve error message for unknown/unsynced columns

---

packages/zero-cache/src/server/main.ts

Include a prescriptive fix when the number of sync workers exceeds the configured maximum connections.
https://discord.com/channels/830183651022471199/1288232858795769917/1329693875702599721

chore(zero-cache): improve error message for insufficient connections

---

packages/replicache/src/replicache-impl.ts
packages/zero-client/src/client/zero.bench.ts

This was triggered in the zero perf benchmark which calls persist. Sometimes this call got overlapped with the scheduled persist call which raised the assert.
Instead of asserting in this condition we wait until the current persist operation is done.

fix(replicache): Wrap persist in a lock.

---

packages/zero-client/src/mod.ts
packages/zero-protocol/src/ast.ts
packages/zero-schema/src/permissions.ts

https://bugs.rocicorp.dev/issue/3459
When a library imports `@rocicorp/zero` and uses `definePermission`, and the library has a `tsconfig.json` that includes `declaration: true`, then tsc complains that it cannot infer the type:
```
The inferred type of 'permissions' cannot be named without a reference
to '../node_modules/@rocicorp/zero/out/zero-protocol/src/ast'. This is
likely not portable. A type annotation is necessary.
```
The reason is that `definePermission` has a dependency on the `Condition` type from `ast.ts` from `zero-protocol`, but that file is never loaded by tsc so it does not know about this type.
The solution is to export a type dependency from `ast.ts`. That way `tsc` is happy.
However, to be less magic we now export all the **transitive** dependencies of …

fix(zero): Add missing type exports

---

apps/zbugs/schema.ts
packages/zero-cache/bench/schema.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-cache/src/auth/read-authorizer.test.ts
packages/zero-cache/src/auth/write-authorizer.test.ts
packages/zero-cache/src/services/mutagen/mutagen.authz.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-client/src/client/context.test.ts
packages/zero-client/src/client/worker-test.ts
packages/zero-client/src/client/zero-poke-handler.test.ts
packages/zero-client/src/client/zero-rate.test.ts
packages/zero-client/src/client/zero.json.test.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-schema/src/builder/schema-builder.test.ts
packages/zero-schema/src/builder/schema-builder.ts
packages/zero-schema/src/permissions.test.ts
packages/zero-schema/src/schema-config.test.ts
packages/zero-schema/src/schema.test.ts
packages/zero-schema/src/table-schema.test.ts
packages/zero-solid/src/solid-view.test.ts
packages/zero-solid/src/use-query.test.ts
packages/zql/src/query/query-impl.query.test.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.test.ts
packages/zql/src/query/test/test-schemas.ts

Uses:
```ts
{
[K in TTables[number]['schema']['name']]: ...
}
```
to pull unique names from array members to use as object keys.
And then
```ts
Extract<
TTables[number]['schema'],
{name: K}
>
```
to pull the corresponding value type with the given name from the array.

feat(zql)!: `tables` and `relationships` are now arrays not objects

---

apps/zbugs/package.json
package-lock.json
package.json
packages/datadog/package.json
packages/datadog/src/datadog-log-sink.ts
packages/replicache-perf/package.json
packages/replicache/package.json
packages/replicache/src/hash.test.ts
packages/replicache/src/persist/clients.test.ts
packages/replicache/src/sync/pull.ts
packages/shared/package.json
packages/shared/src/tool/vitest-perf-json-to-bmf.ts
packages/zero-cache/package.json
packages/zero-cache/src/scripts/run-query.ts
packages/zero-cache/src/scripts/transform-query.ts
packages/zero-cache/src/server/life-cycle.ts
packages/zero-cache/src/server/logging.ts
packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/test/db.ts
packages/zero-client/package.json
packages/zero-client/src/client/server-option.ts
packages/zero-client/src/client/worker-test.ts
packages/zero-protocol/package.json
packages/zero/package.json
packages/zero/src/zero-cache-dev.ts
packages/zql/package.json
packages/zqlite-zql-test/package.json
packages/zqlite/package.json

In particular this pull in "no-console".

chore: update @rocicorp/eslint-config to 0.7.0

---

packages/zero/src/zero-cache-dev.ts

By default, use fewer cores and db connections when running `zero-cache-dev`.
#papercut: https://discord.com/channels/830183651022471199/1288232858795769917/1331403438642434299

feat(zero-cache-dev): set lower defaults

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/key-columns.test.ts
packages/zero-cache/src/services/view-syncer/key-columns.ts
prod/templates/sandbox/template.yml
prod/templates/template.yml

Make the CVR update logic detect row key changes and recognize when two different keys reference the same row.
Algorithm:
* The `KeyColumns` class determines the (potentially old) key columns referenced in the CVR.
* It does this purely by examining the current CVR rows.
* This relies on an invariant that a CVR's row keys are self-consistent, explained in the js doc.
* When processing rows produced by the IVM pipeline, check if the row exists in the CVR by either the new key (from the pipeline) or the old key (used by the CVR). This is possible at this point because the full row is available, and thus the old key columns can be looked up.
* Edge case: If the old key columns no longer exist in the replica, we throw `ClientNotFound` and drop the CVR. This would only happen if the developer …

fix(zero-cache): correctly handle row key changes in CVR updates

---

packages/zero-react/package.json
packages/zero-react/src/use-query.test.ts
packages/zero-react/src/use-query.tsx
packages/zero-react/vitest.config.ts

strict mode will mount, unmount, remount a component causing `changeDesiredQueries` to remove the query then re-add it. This creates flickering for users who do not have a preload or covering query higher up in the component hierarchy.
It also creates unnecessary query churn in dev mode.
https://discord.com/channels/830183651022471199/1322102519987572747

feat(zero-react): delay unsubscribing queries

---

packages/zero-cache/src/types/processes.ts

Remove the stdio piping between parent/child processes, as it causes event listener warnings. This was a workaround for Windows that should not longer be necessary now that the child processes are no longer `detached`.

fix(zero-cache): stop piping stdio between parent and child

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts

When converting row keys in the CVR, fix an edge case in which a converted row is added-and-deleted. In this case, the right poke happens, but the new (deleted) row was not being persisted in the row cache, and thus would not show up when catching up other clients.
In doing so, the special case for deletes is removed the no-op write removal logic, and is instead replaced by a manual override to force the updates for specific rows.

fix(zero-cache): fix an edge case when row keys change

---

packages/zero-cache/src/auth/write-authorizer.test.ts
packages/zero-cache/src/auth/write-authorizer.ts

https://discord.com/channels/830183651022471199/1330784397439406171/1331443590760501328
Another issue with write authorization as it stands today -- when using ZQL for write permissions, we can only consider the fields which are expressible in ZQL.

fix(zql): only select syncable columns in the write authorizer

---

apps/zbugs/src/hooks/use-element-size.ts
apps/zbugs/src/pages/list/list-page.tsx
packages/zero-react/src/use-query.tsx

Every time we mount a component we do a render with no data then a render with data.
I made a change to fix this previously and it caused the zbugs issue list to render no data when going back.
This was not a bug in the change but rather a bug in our `use-element-size` hook which is now fixed.
---
Before (13 renders):
https://github.com/user-attachments/assets/acb23c80-a34f-4286-a455-478ee10a73ab
After (5 renders)
https://github.com/user-attachments/assets/a75226de-54e8-4c2e-bc6c-b018fda0fda7
Before (6 renders):
https://github.com/user-attachments/assets/cac35de1-63c0-45c7-bf61-afa88837730d
After (2 renders):
https://github.com/user-attachments/assets/343818f4-32b4-4ce0-ba1c-68765b0611f7

feat(zero-react): remove empty data render, fix `use-element-resize`

---

packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/error.ts

Adds an optional `reconnectParams: Record<string, string>` directive to all backoff errors which instructs the client to append (non-conflicting) query parameters to the next request.
This will be used when rebalancing requests to cooperatively gauge overall system load without relying on a central coordinating entity.

feat(zero-protocol): add a side-channel for transporting load-balancing info via query-params

---

packages/zero-cache/src/server/change-streamer.ts
packages/zqlite/src/db.ts

Another #papercut that we see a lot, particularly among Windows users that copy the quickstart config verbatim.
The error message now includes "ZERO_REPLICA_FILE" and the (invalid) path.

chore(zero-cache): improve error message when the `--replica-file` cannot be opened

---

packages/replicache/src/sync/request-id.test.ts
packages/replicache/src/sync/request-id.ts

The old code was generating the same ID over and over.

fix(replicache): newRequestID should return a new ID each time

---

packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/multi/runtime.ts
packages/zero-cache/src/services/dispatcher/sync-dispatcher.ts

Include the `taskID` (i.e. of the `view-syncer`) when hashing an incoming connection / client-group to a worker process. This diversifies the distribution of client-groups across processes for different `view-syncer`s, allowing loaded `view-syncer`s to shed client-groups on their most heavily loaded workers to a uniform distribution on the receiving tasks.
Unrelated: Also shorten taskID names; we only need the unique identifier, and not all of the resource namespacing included in the Task ARN.

feat(zero-cache): diversify client-group distribution across tasks

---

prod/templates/sandbox/vpc.yml
prod/templates/vpc.yml

* Set the load balancing algorithm to "least outstanding requests"
* Fix the deregistration delay to be 3 minutes (this is the amount of time an outgoing task gets to drain requests)
* Reduce the cookie stickiness duration to 3 minutes. This essentially becomes the lower bound on connection lifetime when shedding requests.
Next:
* Enable auto-scaling on sandbox

prod(zbugs): set lb algorithm to least oustanding requests

---

packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/ast.ts
packages/zero-protocol/src/protocol-version.ts
packages/zero-schema/src/permissions.test.ts

the valita schema and typescript type for `Parameter` drifted.  There's no need to have two types, just infer the `Parameter` type from the valita schema.

fix(zql): make valita the source of truth for the `Parameter` type

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/test/db.ts

Increase test timeouts for integration-level postgres tests to run on custom (remote) pg instances like Aurora

chore(zero-cache): increase test timeouts for running on remote pg instances

---

packages/zero-cache/src/services/running-state.test.ts
packages/zero-cache/src/services/running-state.ts

Not all backoff situations warrant `error` level logging. Retries and backoff are an expected occurrence when services restart. Start with `info` and progress through `warn` (> 1 sec) and `error` (> 5 sec) to improve the signal-to-noise ratio.

chore(zero-cache): vary log level according to backoff delay

---

packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/multi/main.ts
packages/zero-cache/src/server/multi/tenant-dispatcher.ts
packages/zero-cache/src/server/replicator.ts
packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.ts
packages/zero-cache/src/services/dispatcher/sync-dispatcher.ts
packages/zero-cache/src/services/http-service.ts
packages/zero-cache/src/services/life-cycle.test.ts
packages/zero-cache/src/services/life-cycle.ts

Add heartbeat monitoring to all HttpServices on the "/keepalive" path.
This will facilitate moving "mandatory" load balancer health checks (i.e. heartbeats) to the the main traffic port rather than the special 4850 port, using the "/keepalive" path to keep the feature opt-in. (This also will facilitate support for SST).
And with this, both the `view-syncer` and `replication-manager` will be able to detect drains at 4848 and 4849, respectively, with the latter enabled via an internal load balancer.

feat(zero-cache): make heartbeat monitoring based on path rather than port

---

prod/templates/sandbox/template.yml

Fix sandbox's `MinimumHealthyPercent` value to be compatible with Autoscaling. 
Deployments otherwise fail because the number of "healthy" tasks (scaled down to 1) is less than the minimum healthy percentage of the DesiredCount.

prod(sandbox): fix MinimumHealthyPercent for auto scaling

---

apps/zbugs/README.md

Fixes md link to the app so it doesn't try to relatively redirect in github.
> Caught this while trying to find the link

fix(zbugs): README link typo

---

packages/zero-schema/src/builder/schema-builder.test.ts
packages/zql/src/query/query.ts

TS2589: Type instantiation is excessively deep and possibly infinite
The hint to solve this was here:
https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
The solution is to compute the types that cause problems step by step. By using `T extends infer U`, we can force the computation of `T` instead of deferring it. This way the instantiation does not get deeper.
instantiation is excessively deep and possibly infinite

fix(zero-schema): Fix an issue with TS2589

---

.github/workflows/bencher-benchmarks-pr.yml

The github action was thinking that the two different jobs were for the same report.

chore(zero): Distinguish the two different bencher comments

---

packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/scripts/run-query.ts

Running ASTs was getting horribly annoying.
```sh
npm run run-query -- --debug-query 'z.query.issue.whereExists("comments")'
> zbugs@0.0.0 run-query
> npm run zero-build-schema && tsx ../../packages/zero-cache/src/scripts/run-query.ts --debug-query z.query.issue.whereExists("comments")
> zbugs@0.0.0 zero-build-schema
> tsx ../../packages/zero-schema/src/build-schema.ts
issue VENDED:  [
[
'SELECT "id","shortID","title","open","modified","created","creatorID","assigneeID","description","visibility" FROM "issue" ORDER BY "id" asc',
10523
],
[
'SELECT "id","shortID","title","open","modified","created","creatorID","assigneeID","description","visibility" FROM "issue" WHERE (("id" > ?) OR ("id" = ?)) ORDER BY "id" asc',
10523
]
]
comment VENDED:  [
[
'SELECT …
```

chore(zql): allow the debug script to run query text in addition to asts

---

packages/zero-cache/src/services/change-streamer/change-streamer-http.ts
packages/zero-cache/src/services/dispatcher/websocket-handoff.ts
packages/zero-cache/src/types/streams.test.ts
packages/zero-cache/src/types/streams.ts
packages/zero-cache/src/types/subscription.ts
packages/zero-cache/src/types/ws.test.ts
packages/zero-cache/src/types/ws.ts

Transforms the incoming and outgoing streams of a WebSocket into Subscription objects with proper back-pressure signaled backoff. 
This will be used for communicating with the custom Change Source endpoint. (@cbnsndwch)
In the future, we should also change our pre-existing transformation logic (i.e. `streamIn()` and `streamOut()` used for internal websocket communication) to use this under the covers in order to properly handle back pressure there as well.

feat(zero-cache): back-pressure aware handling of websockets

---

packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/server/multi/config.test.ts
packages/zero-cache/src/services/change-source/custom/change-source.test.ts
packages/zero-cache/src/services/change-source/custom/change-source.ts
packages/zero-cache/src/services/change-source/custom/sync-schema.ts
packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-streamer/schema/tables.ts
packages/zero-cache/src/services/replicator/change-processor.ts
packages/zero-cache/src/types/streams.ts

Initial experimental support for custom backends via the `change-protocol`.
Enable this by setting:
```
ZERO_UPSTREAM_DB = http://my-change-source-endpoint.dev/changes/v0/stream?...
ZERO_UPSTREAM_TYPE = custom
```
@cbnsndwch

feat(zero-cache): support for custom backends (experimental)

---

packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/protocol/current/data.ts
packages/zero-cache/src/services/change-source/protocol/version.test.ts
packages/zero-cache/src/services/replicator/change-processor.ts

Make a couple of unnecessary fields optional in the change-protocol, to be removed in a later release.
@cbnsndwch

feat(zero-cache): deprecate unnecessary fields from change-protocol

---

packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/options.ts

Mainly lifting from https://github.com/rocicorp/mono/pull/3493/files#diff-eb7e31f6f0fe54b4a8955bb87dbf0f33aaa890361470233ad2875cc2e6f4ce7a
tweaks:
- multiple args to mutators
- add a default type parameter for `MD` so it need not be specified

feat(zero): add type functions for custom mutators

---

packages/zero-cache/src/services/replicator/change-processor.ts
packages/zero-cache/src/workers/replicator.ts
packages/zqlite/src/db.ts

Add a call to `PRAGMA optimize` after performing schema changes (as recommended in https://www.sqlite.org/lang_analyze.html).
Set a `busy_timeout` for all replica files, i.e. in the `view-syncer` as well as in the `replication-manager`, now that we are introducing (occasional) multiple writes.
Catch and log exceptions if the optimize-on-close call fails (e.g. with a lock timeout), since the application can/should continue running if the optimize could not acquire the lock.

feat(zero-cache): optimize after schema changes. handle lock contention

---

packages/zero-cache/src/services/life-cycle.ts

Check the last keepalive more frequently (every 5 seconds) so that a drain is detected between 15 ~ 20 seconds after the last keepalive (as opposed to 15 ~ 30 seconds).

feat(zero-cache): faster drain detection (rolling restarts)

---

packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts

Rather than having all mutators at the top level, they'll need to be namespaced.
Example:
```ts
const mutators = {
issue: {
setTitle: (tx, id: string, title: string) => {
tx.mutate.issue.update({id, title});
},
},
notATableName: { doThing: () => {} }
};
```
The namespace is not required to match a table name but tables names are provided to intellisense at this callsite.

feat(zero): namespace custom mutators to the table they impact

---

packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts

The previous schema change logic relied on the assumption that for an `ALTER TABLE` statement, only one column change can happen at a time. This is incorrect, as multiple column actions can be present in the statement. 
The corrected logic leverages the tables' `oid` and associated columns' `attnum` values to determine the diffs that need to be applied to the replica. As such, it no longer needs to know what the DDL command was (e.g. `ALTER TABLE` vs `ALTER PUBLICATION`).
https://discord.com/channels/830183651022471199/1333484736814776360/1333497466363973642
Tangential: Also fix the degraded-mode schema change detection logic (e.g. supabase, neon) to detect changes in the columns' NOT NULL attribute.

fix(zero-cache): correctly handle multiple-column schema changes

---

packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zql/src/builder/builder.test.ts
packages/zql/src/ivm/array-view.test.ts
packages/zql/src/ivm/catch.ts
packages/zql/src/ivm/change.ts
packages/zql/src/ivm/data.ts
packages/zql/src/ivm/exists.fetch.test.ts
packages/zql/src/ivm/exists.push.test.ts
packages/zql/src/ivm/exists.ts
packages/zql/src/ivm/fan-out-fan-in.test.ts
packages/zql/src/ivm/filter-push.ts
packages/zql/src/ivm/filter.test.ts
packages/zql/src/ivm/filter.ts
packages/zql/src/ivm/join.fetch.test.ts
packages/zql/src/ivm/join.push.test.ts
packages/zql/src/ivm/join.sibling.test.ts
packages/zql/src/ivm/join.ts
packages/zql/src/ivm/memory-source.test.ts
packages/zql/src/ivm/skip.ts
packages/zql/src/ivm/snitch.ts
packages/zql/src/ivm/source.test.ts
packages/zql/src/ivm/take.fetch.test.ts
packages/zql/src/ivm/take.push-child.test.ts
packages/zql/src/ivm/take.ts
packages/zql/src/ivm/view-apply-change.ts

The `Exist` operators `#fetchNodeForRow` is quite expensive and is a work around for the fact that `Node`'s relationships can only be consumed a single time.  In order to read the relevant relationship, `Exist` has to fetch from source the parent `Node`.   This fetch is pure overhead, we are fetching a row we already have.
This change updates `Node`'s relationships to be callable, so that they can be consumed multiple times.
`Node`'s type changes from 
```
export type Node = {
row: Row;
relationships: Record<string, Stream<Node>>;
};
```
to 
```
export type Node = {
row: Row;
relationships: Record<string, () => Stream<Node>>;
};
```
This change also updates `ChildChange` to have a `node: Node` rather than a `row: Row` so that the relationships needed by `Exist` are also available on …

refactor(zql): callable relationships

---

packages/zero-cache/src/services/change-streamer/change-streamer-service.pg-test.ts
packages/zero-cache/src/services/change-streamer/error-type-enum.ts
packages/zero-cache/src/services/change-streamer/storer.pg-test.ts
packages/zero-cache/src/services/change-streamer/storer.ts

Because the `change-streamer` forwards messages to view-syncers immediately, and concurrently stores and acks upstream, it is possible for a replica to be ahead of the change log if a server is killed before the change can be stored. 
Handle this case by considering the subscriber "caught up" if it is ahead of the change log. The existing forwarder logic already handles filtering out messages that have already been seen.
https://discord.com/channels/830183651022471199/1288232858795769917/1334328586265563260
https://discord.com/channels/830183651022471199/1332721644527157319

fix(zero-cache): handle subscribers ahead of the change-streamer change-log

---

packages/replicache/src/persist/client-gc.test.ts
packages/replicache/src/persist/client-gc.ts
packages/replicache/src/persist/client-group-gc.test.ts
packages/replicache/src/persist/clients.test.ts
packages/replicache/src/persist/clients.ts
packages/replicache/src/persist/collect-idb-databases.test.ts
packages/replicache/src/persist/collect-idb-databases.ts
packages/replicache/src/replicache-impl.ts
packages/shared/src/resolved-promises.ts

Replicache has 3 different gc processes:
- Collect IDB (also applies to mem if you keep your browser open long enough)
- When this happens we look at all the clients in the store before deleting it and call the callback.
- Collect Client:
- When a client gets collected we call the callback
- Collect Client Group:
- A client group is only collected if it no longer has any clients in it so there is nothing to do in this case.
This callback will be used in Zero to tell the server about the deleted clients.

chore(replicache): Add onClientsDeleted callback

---

packages/shared/src/btree-set.test.ts
packages/shared/src/btree-set.ts

This'll be needed to support reads in custom mutators on the client.
Design: https://www.notion.so/replicache/Custom-Mutators-1353bed8954580f09875f1484e7ce7d4#18b3bed8954580f38321e897032b0fdf

feat(shared) re-add `clone` to `btree-set`

---

packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.ts
packages/zero-cache/src/services/change-streamer/schema/init.pg-test.ts
packages/zero-cache/src/services/change-streamer/schema/init.ts
packages/zero-cache/src/services/change-streamer/schema/tables.pg-test.ts
packages/zero-cache/src/services/change-streamer/schema/tables.ts
packages/zero-cache/src/services/change-streamer/storer.pg-test.ts
packages/zero-cache/src/services/change-streamer/storer.ts

The `replication-manager` reads the `lastWatermark` from the change DB in order to take over the postgres replication slot from the right starting point.
Because the old replication manager is not killed until the replication slot is taken over, there is a potential race condition in which the old replication manager, before shutting down, commits a new change to the change log, moving the watermark forward. This would result in an INSERT conflict when the new replication manager attempts to persist that same transaction.
Although ignoring conflicts is a potential workaround, it has the drawback of masking other types of subtle bugs.
The solution implemented here uses a new `replicationState` table with a single row used to coordinate handoffs. The row contains:
* an `owner` column for …

fix(zero-cache): make replication-manager handoff watertight

---

packages/zero-react/src/use-query.tsx

Fixes https://bugs.rocicorp.dev/issue/3497
This was broken with:
https://github.com/rocicorp/mono/pull/3409#discussion_r1894702111
I don't think the server check was actually needed to accomplish the goal of that PR, but will check w/ chase. Want to land this now to unblock user with canary.

fix(react): Allows useQuery to work again when server is null.

---

packages/zero-cache/src/services/change-source/custom/change-source.ts
packages/zero/package.json
packages/zero/src/change-protocol/v0.ts
packages/zero/tsconfig.server.json

The `change-protocol/v0` export paths in `@rocicorp/zero@0.13.2025013101` point to a `mod.ts` file that doesn't exist in the `out` directory, which breaks imports for custom change sources.
This PR fixes this by:
- adding a `change-protocol/v0.ts` file to `zero/src`
- adding the `change-protocol` directory to the `include` setting in `packages/zero/tsconfig.server.json`
- updating the `./change-protocol/v0` export in `packages/zero/package.json` to point to the new file

fix(zero): fix change-protocol/v0 export paths in package.json

---

packages/z2s/src/compiler.pg-test.ts
packages/z2s/src/compiler.ts
packages/z2s/vitest.config.ts
packages/z2s/vitest.workspace.ts
packages/zero-cache/vitest.workspace.ts
packages/zqlite/src/query.test.ts
packages/zqlite/src/table-source.ts
packages/zqlite/src/test/source-factory.ts

Reveals that the compiler will need to:
1. support `hidden` tables for junction edges
2. support `one`
Will provide the `format` as an arg to the `compiler` in a follow up PR so we can take `one` and `junction` edges into account.

feat(z2s): test against pg

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.ts
packages/zero-cache/src/services/change-source/pg/schema/validation.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/validation.ts
packages/zero-cache/src/services/mutagen/mutagen.pg-test.ts

Tables from non-public schemas can be synced to the client.
This requires [creating a publication](https://www.postgresql.org/docs/current/sql-createpublication.html) on upstream (as the default will only sync tables from the "public" schema):
```sql
CREATE PUBLICATION zero_data FOR TABLE foo, TABLE bar, TABLE my_schema.baz, ...;
```
and specifying that publication in the `ZERO_SHARD_PUBLICATIONS` server option:
```env
ZERO_SHARD_PUBLICATIONS=zero_data
```
Finally, on the client, the schema must be configured to reference the table correctly:
```ts
// schema.ts
const baz = table('baz')
.from('my_schema.baz')
.columns({...})
.build();
```

feat(zero-cache): support syncing tables from non-public schemas

---

packages/zero-advanced/src/mod.ts
packages/zero-client/src/client/context.ts
packages/zero-solid/src/solid-view.test.ts
packages/zero-solid/src/solid-view.ts
packages/zql/src/ivm/view-apply-change.ts

The `reconcile` optimization approach (https://github.com/rocicorp/mono/pull/3682) was incorrect (I misunderstood how reconcile works), as was revealed by the tests added here: https://github.com/rocicorp/mono/pull/3692.  
This approach goes back to using `produce`, but addresses the correctness issue by using an idea @tantaman came up with of reading the relationships of the changes at the time the push is received, but still queueing them to be applied to the solid store state on transaction completion.   We are careful to only read relationships in the changes actually used by `applyChanges`.
This solved the correctness problem, but while much faster than the 30 seconds prior to us trying to optimize this, the 3000 row initial load case in hello-zero-solid was still spending ~742ms in …

perf,fix(zero-solid): back to produce but pre-reading relationships and optimizing initial view build

---

packages/zero-solid/src/solid-view.ts

This further optimizes the case of building from empty by avoiding allocating temp arrays.
Now we only have to allocate temp arrays for storing relationships between push and transaction commit when updating a non empty view, which is often smaller updates.
This didn't have an appreciable impact on the test case we've been using of 3000 rows (with 2, 1 child, relationships per row) in hello-zero-solid, but those rows all have very small non-nested relationships, so thats understandable.  I still think this is a worthwhile optimization despite it adding a bit of complexity.

perf(zero-solid): avoid temp arrays when building from empty

---

packages/replicache/src/patch-operation.ts
packages/zero-client/src/client/query-manager.ts
packages/zero-client/src/client/zero-poke-handler.test.ts
packages/zero-client/src/client/zero-poke-handler.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/ast.ts
packages/zero-protocol/src/push.test.ts
packages/zero-protocol/src/push.ts
packages/zero-protocol/tsconfig.json
packages/zero-schema/src/name-mapper.test.ts
packages/zero-schema/src/name-mapper.ts
packages/zero-schema/src/permissions.ts

Maps CRUD operations to their server names if aliased in the schema.
Also consolidates the name mapping logic.

feat(zero-cache): map CRUD operations to server names

---

packages/zql/src/query/query.ts

Fixes https://bugs.rocicorp.dev/issue/3503

Allow `Row` helper to work with singular queries.

---

packages/replicache/src/replicache-impl.ts
packages/replicache/src/replicache.ts
packages/replicache/src/sync/patch.test.ts
packages/replicache/src/sync/patch.ts
packages/replicache/src/sync/pull.ts
packages/zero-client/src/client/context.ts
packages/zero-client/src/client/ivm-source-repo.test.ts
packages/zero-client/src/client/ivm-source-repo.ts
packages/zero-client/src/client/zero.ts
packages/zql/src/query/test/test-schemas.ts

After the first pull is applied, the `sync` branch of the IVM sources is created.
For later pulls, `diffs` are applied to the sync branch to advance it.
The `patch.apply` function was updated to return diffs for the IVM source to apply. The contents of a patch did not have enough information to apply it to IVM sources directly: old values were missing for delete and edit. Rather than doing extra lookups or diffing between dag commits, gathering diffs in `patch.apply` seemed to be the most efficient and minimal change.

feat(zero-client): maintain the `sync` branch of IVM sources

---

packages/zero-client/src/client/crud.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/ivm-source-repo.test.ts

I did not update crud mutators to write to the IVM source  during a rebase as the intent is to remove support for CRUD mutators when custom mutators are ready.

feat(zero-client): implement rebasing of custom mutators

---

packages/zero-cache/src/db/migration.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/services/view-syncer/cvr-store.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/schema/cvr.ts
packages/zero-cache/src/services/view-syncer/schema/init.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

For dev instances, "preview" instances, and sharding, zero-caches with different `--shard-id` values can point to the same UPSTREAM_DB 
They can now also point to the same CVR_DB, as they will each operate in their own `cvr_{shard-id}` schema.
Data from the existing global `cvr` schema will be migrated the first time.
(Similar change for the CHANGE_DB is forthcoming)
https://bugs.rocicorp.dev/issue/3502

feat(zero-cache): allow multiple zero-cache shards to use the same CVR db

---

packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.ts
packages/zero-cache/src/services/change-streamer/schema/init.pg-test.ts
packages/zero-cache/src/services/change-streamer/schema/init.ts
packages/zero-cache/src/services/change-streamer/schema/tables.pg-test.ts
packages/zero-cache/src/services/change-streamer/schema/tables.ts
packages/zero-cache/src/services/change-streamer/storer.pg-test.ts
packages/zero-cache/src/services/change-streamer/storer.ts

For dev instances, "preview" instances, and sharding, zero-caches with different `--shard-id` values can point to the same UPSTREAM_DB
They can now also point to the same CHANGE_DB, as they will each operate in their own `cdc_{shard-id}` schema.
Data from the existing global `cdc` schema will be migrated the first time.
This is analogous to the change done for the CVR schema in #3714.
https://bugs.rocicorp.dev/issue/3502

feat(zero-cache): allow multiple zero-cache shards to use the same CHANGE db

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts

Use the "Rehome" error kind introduced in #3589 when redirecting the client to the newer view-syncer (instead of "Internal", which looks like something's wrong). 
Also use the `minBackoffMs` directive to have the client reconnect immediately instead of waiting for 5 seconds.

fix(zero-cache): use the new "Rehome" error kind when CVR ownership changes

---

package-lock.json
packages/zero-cache/package.json
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero/package.json

When running an IVM pipeline, yield the process every 500ms, preventing a long-running query from hogging the CPU. This should improve fairness as well as eliminate connection timeouts (from missed pongs).
The original implementation in #3651 did not work because the magic stopwatch was used incorrectly. 
The new implementation just uses Date.now().
Verified functionality thanks to @cesara's gigabugs dataset.
Two ViewSyncers (`clientGroupID`) are taking turns processing chunks of their pipelines in the same process (`pid`), and ping-pong is responsive all the while:

feat(zero-cache): take 2: time-slice IVM for fairness and responsiveness

---

packages/shared/src/queue.test.ts
packages/shared/src/queue.ts
packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts

addresses https://github.com/rocicorp/mono/pull/3724#discussion_r1946270166 to use the existing queue class.

chore(zero-cache): use existing queue in `PusherService`

---

package-lock.json
packages/z2s/package.json
packages/z2s/src/test/query-gen.ts
packages/z2s/src/test/schema-gen.test.ts
packages/z2s/src/test/schema-gen.ts
packages/zero-cache/src/auth/write-authorizer.ts
packages/zero-schema/src/mod.ts
packages/zero-schema/src/permissions.ts
packages/zql/src/query/static-query.ts

Starting on the `@rocicorp/zero/pg` SDK for custom mutators and I'd like more confidence in our ZQL vs SQL execution.
Adding a way to randomly build queries in order to fuzz our ZQL and ZQL->SQL implementations.

feat(z2s): auto generate a schema for testing

---

packages/zero-client/src/client/zero-poke-handler.test.ts
packages/zero-client/src/client/zero-poke-handler.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/poke.ts
packages/zero-protocol/src/protocol-version.ts

Adds an optional `cookie` field to `pokeEnd` which overrides the value that was specified in `pokeStart`.
(In the future, we should considering moving the field to only be in `pokeEnd`.)
The motivation for this change is to allow the `view-syncer` to avoid CVR updates for IVM pushes that don't change the CVR (thereby avoiding the quadratic writes to the CVR db). 
When this happens, the associated pokes can either be:
1. cancelled if nothing was sent, or
2. completed (e.g. if catchup rows were sent) with a revised cookie reflecting what is stored in the CVR

feat(zero-protocol): client-side of revised-cookie poke protocol

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/view-syncer/client-handler.test.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/cvr-store.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-cache/src/workers/connection.ts

System scalability improvement which eliminates CVR db updates and pokes for replica changes that do not affect the client group. 
This mitigates the quadratic nature of replication processing by pruning processing branches before writing to the CVR postgres DB and downstream clients, limiting the blast radius to IVM push processing. 
* The CVR pruning avoids a flush if there are no pending writes. Note that this means that we will update the `lastActive` field of a CVR less often, but that only affects garbage collection.
* The poke pruning involves buffering the initial `pokeStart` until a subsequent message is sent, and avoiding sending anything at all if the `finalVersion` passed to `pokeEnd` is equal to the client's `baseCookie`
Note that both features rely on the client correctly …

feat(zero-cache): eliminate quadratic CVR writes

---

packages/z2s/src/compiler.output.test.ts
packages/z2s/src/compiler.pg-test.ts
packages/z2s/src/compiler.ts
packages/z2s/src/test/nullish.ts

This fixes `one` in the compiler.
`hidden` is also mostly fixed. When seeing `hidden` we now translate the hidden path to joins rather than sub-selects.
The ivm builder is putting `hidden` where I would not expect it so need to figure that out in a future PR.

feat(z2s): fix `one`, start handling `hidden`

---

packages/replicache/src/deleted-clients.ts
packages/replicache/src/persist/client-gc.test.ts
packages/replicache/src/persist/client-gc.ts
packages/replicache/src/persist/collect-idb-databases.test.ts
packages/replicache/src/persist/collect-idb-databases.ts
packages/zero-client/src/client/delete-clients-manager.test.ts
packages/zero-client/src/client/delete-clients-manager.ts

Now, replicache writes the deleted clients head as clients are deleted.
This was previously managed by zero since replicache does not really need this information.

chore(zero, replicache): Let replicache manage the deleted clients head

---

packages/z2s/src/compiler.pg-test.ts
packages/zql/src/ivm/join.ts
packages/zql/src/query/query-impl.ast.test.ts
packages/zql/src/query/query-impl.query-kitchen-sink.test.ts
packages/zql/src/query/query-impl.ts

`query-impl` put the `hidden` flag at the final table in a junction edge, which was incorrect. ZQL did the right thing because `join` moved the hidden flag up a level incorrectly. Two errors made a right in this case.
Concretely:
- query impl would hide the `label` table
- join would move the `hidden` flag back up to the `issue-label` table.
The z2s compiler, however, couldn't work properly with the `hidden` flag being placed in the wrong level by `query-impl`

fix(zql,z2s): place `hidden` flag on the correct relationship

---

packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-client/src/client/zero-poke-handler.test.ts

Adds a sanity check that the finalVersion always advances if pokes were sent.
Fix unit test to advance the cookie since a poke was sent (otherwise it is exercising a scenario that should not be possible)

chore(zero-cache): add sanity check, fix test

---

packages/z2s/src/test/chinook/chinook.pg-test.ts
packages/zero-cache/src/types/pg.ts

ZQL returns `numeric` as a number.
PG returns it as a `string`.
Change `pg` to return it as a number if it fits JS precision.
If we go this route, `table-source` should be update to convert to `string` on an overflow as well.

feat(zero-cache): treat `numeric` as `number` 

---

packages/zero-cache/src/auth/read-authorizer.ts
packages/zero-cache/src/auth/write-authorizer.test.ts
packages/zero-cache/src/auth/write-authorizer.ts
packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/workers/connection.ts
packages/zero-protocol/src/protocol-version.ts
packages/zero-schema/src/compiled-permissions.ts
packages/zero-schema/src/permissions.test.ts
packages/zero-schema/src/permissions.ts

Change the schema of the permissions JSON object to include the `PROTOCOL_VERSION` with which it was compiled. (Design: https://www.notion.so/replicache/Permissions-Deployment-1933bed895458002b4c8c3a2ab02c11b?pvs=4#1933bed8954580399706dce2889a2274)
This will serve a similar purpose to the protocol version declare in the `/sync/v{#}/connect` url path, allowing the server to determine compatibility and output a useful error message in the case of incompatibilities (as opposed to [cryptic valita errors](https://discord.com/channels/830183651022471199/1337466220894617650/1337750510991708161)).
The checking of the new `protocolVersion` field is not yet implemented. This will be bundled with the change that retrieves the permissions object from upstream.

feat(zero-schema): encode the protocol version in the permissions JSON

---

packages/zero-cache/src/auth/load-schema.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/scripts/run-query.ts
packages/zero-cache/src/scripts/transform-query.ts

Move the options relevant to each script into the script itself. This should make it more sustainable to add other scripts (like an up-and-coming `deploy-permissions` script) without making the main server options a nexus.

chore(zero-cache): move debugging options into debugging scripts

---

.github/workflows/sst-prod-deploy.yml
.github/workflows/sst-sandbox-deploy.yml

Runs the new `zero-deploy-permissions` command from #3755 to deploy the zbugs permissions.

prod(zbugs): run deploy-permissions as part of continuous deploy

---

packages/zero-client/src/client/crud.ts
packages/zero-client/src/client/zero.test.ts

Fixes https://bugs.rocicorp.dev/issue/3529

fix(zero-client): Allow overlapped mutators.

---

packages/shared/src/immutable.test.ts
packages/shared/src/immutable.ts

We were getting:
```
Type instantiation is excessively deep and possibly infinite.ts(2589)
```
When a ReadonlyArray was passed into `Immutable`. The reason was that we were using `extends Array<infer U>`, but ReadonlyArray does not extend Array.

fix(shared): Immutable type too deep

---

packages/replicache/src/deleted-clients.ts
packages/replicache/src/persist/client-gc.test.ts
packages/replicache/src/persist/client-gc.ts
packages/replicache/src/persist/client-group-gc.test.ts
packages/replicache/src/persist/client-group-gc.ts
packages/replicache/src/persist/clients.ts
packages/replicache/src/persist/collect-idb-databases.test.ts
packages/replicache/src/persist/collect-idb-databases.ts
packages/replicache/src/replicache-impl.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-client/src/client/delete-clients-manager.test.ts
packages/zero-client/src/client/delete-clients-manager.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/connect.test.ts
packages/zero-protocol/src/connect.ts
packages/zero-protocol/src/delete-clients.ts

Now we store `{clientIDs, clientGroupIDs}` in the deleted clients head and update these as needed.
When sending `deletedClients` (as part of connection, initConnection etc) we send both client IDs and client group IDS.

chore(zero, replicache): include client group ids in deleted clients

---

packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/mutator.ts
packages/zero-cache/src/services/dispatcher/dispatcher.test.ts
packages/zero-cache/src/services/dispatcher/dispatcher.ts
packages/zero-cache/src/workers/mutator.ts

Follows the same pattern as `syncer` to set up a `mutator` worker that will receive websocket connections from the dispatcher.

feat(zero-cache): update `dispatcher` to be able to hand-off to `mutator`

---

packages/zero-cache/src/scripts/deploy-permissions.ts
packages/zero-cache/src/scripts/transform-query.ts

Have the `transform-query` script use the schema loading logic from `deploy-permissions`, to remove a dependency on the soon-to-go-away schema.json logic.

chore(zero-cache): use the schema load logic in deploy-zero-permissions

---

packages/zero-cache/src/scripts/deploy-permissions-options.ts
packages/zero-cache/src/scripts/deploy-permissions.ts
packages/zero-cache/src/scripts/transform-query.ts

Move the deployment options to a separate file so that importing them does not execute the main script.

chore(zero-cache): move options to separate file

---

packages/zero-cache/src/services/change-source/pg/schema/init.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/init.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.pg-test.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.ts
prod/sst/sst.config.ts

Doing a surgical upgrade from v3 to v4 isn't working out. Just do a reset.

fix(zero-cache): reset the replica for new permissions schema

---

packages/zero/src/zero-cache-dev.ts

An error can happen during a redeploy. This doesn't stop an already running server.

fix(zero-cache-dev): better error message during redeploy failures

---

packages/zero-cache/src/services/view-syncer/schema/init.ts

The renaming of the legacy `cvr` schema to sharded `cvr_{shard-id}` schemas is not compatible with a multi-node setup: https://discord.com/channels/830183651022471199/1339066868245467157/1339076089309298689
Removing it provides the correct semantics; the new `zero-cache` just starts storing cvrs in the new schema.
The disadvantage is that the old schema does not get cleaned up. This could be addressed in cleanup tool, but it has to be performed manually with the knowledge that the legacy schema is no longer being used.

fix(zero-cache): remove cvr migration from legacy schema

---

packages/replicache/src/deleted-clients.test.ts
packages/replicache/src/deleted-clients.ts

The client heads change from `ClientID[]` to `{clientIDs: ClientID[],
clientGroupIDs: clientGroupID[]}`.
Even though this was never released it broke zbugs which gets deployed from main. This change allows reading the old format.

fix(zero-client): Allow reading legacy deleted clients head

---

packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-cache/src/workers/connection.ts
packages/zero-cache/src/workers/syncer.ts

The end state is to put the pusher/mutator on its own websocket connection (https://github.com/rocicorp/mono/pull/3770).
That requires some refactoring of the client. Till that refactor is done (and so you all can use custom mutators while I'm on vacation), handle push messages over the existing websocket connection.

feat(zero-cache): wire pusher service through the existing ws connection

---

package-lock.json
packages/z2s/tsconfig.json
packages/zero-client/src/client/crud.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/options.ts
packages/zero-client/src/client/test-utils.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-client/src/mod.ts
packages/zql/src/mutate/custom.ts

Custom mutator interfaces are required on the client and server. They also depend on the `Query` type, hence the reason to move them to the `zql` package.
@aboodman - this adds a "server" transaction reason. I considered "authoritative" but, while that is accurate, it is not immediately clear what it means to a new user.
```ts
export type TransactionReason = 'optimistic' | 'rebase' | 'server';
```
since `tx` could be a server tx or a client tx in the case where the user shares their mutator code with client and server.

feat(zero-pg): move the `custom mutator` interfaces to `zql`

---

packages/zero-cache/src/scripts/deploy-permissions.ts
packages/zero-cache/src/scripts/permissions.ts
packages/zero/src/zero-cache-dev.ts

Have `zero-deploy-permissions` error for custom upstreams, and `zero-cache-dev` skip permissions deployment for them.
@cbnsndwch

fix(zero-deploy-permissions): allow zero-cache-dev to work for custom upstreams

---

packages/zero-cache/src/scripts/deploy-permissions.ts
packages/zero-cache/src/scripts/permissions.ts

* `json`: one-line json, useful for custom backends
* `pretty`: indented json for debugging
@cbnsndwch

feat(zero-deploy-permissions): add "json" and "pretty" output formats

---

packages/zero-cache/src/workers/connection.ts
packages/zero-cache/src/workers/syncer-ws-message-handler.ts
packages/zero-cache/src/workers/syncer.ts

The mutator/pusher will also have a websocket connection. Make the `Connection` class reusable by parameterizing it with a `messageHandler`

refactor(zero-cache): allow reusing `connection` for syncer and mutator

---

packages/zero-cache/src/auth/load-permissions.test.ts
packages/zero-cache/src/auth/load-permissions.ts
packages/zero-cache/src/types/strings.test.ts
packages/zero-cache/src/types/strings.ts
packages/zero-cache/src/types/ws.ts
packages/zero-schema/src/compiled-permissions.ts

Using the (wire + AST) `protocolVersion` in the Permissions protocol will be too sensitive. For the percentage of users that don't bother to wait for server deployments to complete before deploying new permissions (e.g. zbugs), this will unnecessarily result in errors every time we change the wire-protocol.
Because the Permissions only relies on the AST schema, consider the data "supported" if it (strictly) parses with its valita schema. This means that semantic changes must be accompanied by a change in the AST format, which unsupporting code will correctly fail to parse. This should pretty much always be the case; we just have to never, e.g. change the meaning of an existing field or something like that.

feat(zero-cache): deprecate protocolVersion from the Permissions format

---

packages/zero-cache/src/scripts/permissions.ts

Also make any exceptions more readable by throwing them to the console (rather than logging them as objects).

feat(zero-permissions): add "type":"module" recommendation when schema load fails

---

prod/sst/sst.config.ts

Use a resource dependency (by calling `apply()` on an `Output` of the  ViewSyncer) to wait for the deployment to complete, after which `npx zero-deploy-permissions` is run.

feat(prod): deploy permissions with sst

---

prod/sst/package-lock.json
prod/sst/package.json
prod/sst/sst.config.ts

Update sst so that we can use the new `wait: true` fanciness.
Also use the `taskDefinition` output instead of the `url` output, as the latter comes from the loadbalancer rather than the view-syncer service.

feat(prod): wait until view-syncers are deployed

---

.github/workflows/sst-prod-deploy.yml
.github/workflows/sst-sandbox-deploy.yml
prod/sst/sst.config.ts

Use SST for deploying permissions, removing the redundant GitHub actions.
Also, set `Service.wait` to `false` by default to keep deployments fast in the common case.
We only need to set them to `true` for the occasional protocol / AST version upgrade, which we can do manually (in the same PR as the protocol change).

feat(prod): fully migrate to SST for permissions deployment

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.ts
packages/zero-cache/src/services/change-streamer/schema/init.ts
packages/zero-cache/src/services/change-streamer/schema/tables.ts

Postgres supports encoding NULL unicode characters in JSON columns, but not in JSONB columns.
https://vladimir.varank.in/notes/2021/01/you-dont-insert-unicode-null-character-as-postgres-jsonb/
Change the datatype of the changeLog to store messages in JSON instead of JSONB so that it can properly ferry these values.
https://discord.com/channels/830183651022471199/1339712194539163669/1339730002966610015

fix(zero-cache): handle NULL characters in JSON columns

---

packages/zero-pg/package.json
packages/zero-pg/src/custom.pg-test.ts
packages/zero-pg/src/custom.ts
packages/zero-pg/src/test/util.ts
packages/zero-pg/src/web.pg-test.ts
packages/zero-pg/src/web.ts
packages/zqlite/src/table-source.ts

In the body of a custom mutator on the server, CRUD operators are provided to update the underlying tables.
This matches what also exists on the client, allowing users to share their mutator code between client and server.

feat(zero-pg): implement `makeSchemaCRUD` for the server

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/schema/cvr.ts
packages/zero-cache/src/services/view-syncer/schema/init.ts
packages/zero-cache/src/services/view-syncer/schema/types.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-client/src/client/context.ts
packages/zero-client/src/client/query-manager.test.ts
packages/zero-client/src/client/query-manager.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/connect.test.ts
packages/zero-protocol/src/queries-patch.ts
packages/zql/src/query/query-impl.query-kitchen-sink.test.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/static-query.ts
packages/zql/src/query/test/query-delegate.ts

Different clients may have different ttl for the same query. We therefore save this in the CVR desires table.
This adds 3 new columns;
- ttl: If any, the time to live in ms after the query has become inactive. (stored as an INTERVAL).
- expiresAt: The time at which the query will expire. This gets set when the query become inactive and the client tells the server so.
- inactivatedAt: The time at which the query became inactive.
These columns are read/written into the CVR but not yet used.

wip(zero): Add ttl etc to cvr desires table

---

packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts

Fix a false positive in degraded-mode ddl change detection in which a table with a compound key is incorrectly flagged as having its schema changed.
https://discord.com/channels/830183651022471199/1288232858795769917/1341135548944744448
The `keyColumns` sent in Postgres MessageRelation contain columns in table declaration order, whereas the PublishedTableSpec contains columns in key / index order. Since it is not possible to detect index-order changes from the MessageRelation itself, just do an order-agnostic compare.

fix(zero-cache): fix false-positive in degraded-mode ddl-change detection

---

prod/sst/sst.config.ts

The `healthCheckGracePeriodSeconds` tells the ELB to hold off on declaring a task unhealthy, which serves a similar purpose to the ECS `startPeriod` value for the equivalent configuration in container health checks.
This should fix the occasional "Task failed ELB health checks" error when trying to update tasks.

fix(prod): set healthCheckGracePeriodSeconds to match startPeriod

---

packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-client/src/client/zero-poke-handler.test.ts
packages/zero-client/src/client/zero-poke-handler.ts
packages/zero-client/src/client/zero-rate.test.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/poke.ts
packages/zero-protocol/src/protocol-version.ts

* This bumps the sync wire protocol from `/sync/v5/connect` to `/sync/v6/connect`
* The `view-syncers` must be fully rolled out before client code is rolled out
* Makes `pokeStart.cookie` optional.
* Makes `pokeEnd.cookie` required.
* Server sends both
* Client only reads the latter

!feat(zero-protocol): transition to pokeEnd.cookie

---

apps/zbugs/schema.ts
packages/zero-cache/src/auth/write-authorizer.ts

feat(zql): Print out permissions when write authorization fails
Fixes https://bugs.rocicorp.dev/issue/3573

fix(zbugs): comment edit was broken

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/schema/cvr.ts
packages/zero-cache/src/services/view-syncer/schema/types.ts

and getInactiveDesiredQueries which returns all inactive queries in the order that we want to try to remove them.

wip(zero-cache): Mark desired query as inactive

---

packages/zero-cache/src/db/migration-lite.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.ts

Copy tables / rows before creating indexes. On a 1GB dataset, this doubles the speed of initial sync, though improvements may be larger for tables with more complex indexes.
Before:
After:

feat(zero-cache): copy before index (faster initial sync)

---

packages/zero-cache/src/services/change-source/pg/initial-sync.ts

This results in a 5~10% copy speedup locally:
Before:
After:

feat(zero-cache): parallelize fetch and inserts (faster initial sync)

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/server/multi/config.test.ts
packages/zero-cache/src/services/litestream/commands.ts
packages/zero-cache/src/services/litestream/config.yml

Set (config-adjustable) litestream defaults to behave more reasonably for zero applications, particularly those with a high write rate.
* Increase the sync interval from the default of 1 second to 5 minutes. This reduces the number of wal segment files that get written to the snapshot generation folder (at the expense of replaying more change history after a restore).
* Decrease the snapshot interval from 1 day to 1 hour. This further reduces the number of wal segment files that can accumulate per generation, at the expense of making a full db copy to s3 more often. This also allows litestream to clear local shadow wal files and thus reduce local disk usage.

feat(zero-cache): tune litestream for zero semantics

---

packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

Handle the case when multiple queries (with different client hashes) are logically equivalent. This was not expected before but can reasonably happen after applying permissions. It is occasionally encountered when multiple queries are disallowed entirely.
https://bugs.rocicorp.dev/issue/3584
https://rocicorp.slack.com/archives/C08AHHFQMMY/p1739577732367319?thread_ts=1739485390.141439&cid=C08AHHFQMMY

fix(zero-cache): handle query collisions

---

package-lock.json
packages/replicache-perf/package.json
packages/replicache/package.json
packages/zero-client/package.json
packages/zero/package.json

This is needed for installing packages via sst, which is at '0.25.0'.

chore: update to esbuild 0.25.0

---

packages/zero-cache/src/scripts/permissions.ts

Fix the loading of permissions when the loading script is in the same directory as `schema.ts`. This would only happen if the loading script is rebundled (e.g. in a lambda).

fix(zero-permissions): fix edge case in loading permissions

---

.github/workflows/sst-sandbox-deploy.yml
prod/functions/package.json
prod/functions/src/permissions.ts
prod/functions/tsconfig.json
prod/sst/sst.config.ts

In the sandbox stage, deploy permission using a Lambda in the VPC, as an example of how permissions can be deployed to upstream databases that are not accessible outside of the AWS network.
This is largely how we would recommend users to deploy permissions. The only difference for the `mono` / `zbugs` setup is that because we deploy at head, we install "@rocicorp/zero" via a tarball, whereas users would simply reference their desired version in the function's `package.json` file.
For prod, continue using the local `Command` to deploy permissions, so that both approaches are exercised.

feat(zero-permissions): deploy permissions via a Lambda in the VPC

---

packages/shared/src/queue.test.ts
packages/shared/src/queue.ts
packages/zero-cache/src/db/transaction-pool.pg-test.ts
packages/zero-cache/src/db/transaction-pool.ts
packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/ddl.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.pg-test.ts
packages/zero-cache/src/services/change-streamer/storer.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/types/streams.ts

`enqueue()` formerly returned a Promise that allowed the caller to wait for the item to be consumed.
However, no (application) code actually needs that API.
Since this class is used in some potentially hot paths, remove that functionality to both eliminate an unnecessary `Resolver` per invocation, as well as make the calling code more readable by not requiring the `void` qualifier.

chore(shared): simplify the Queue class

---

packages/shared/src/queue.test.ts
packages/shared/src/queue.ts
packages/zero-cache/src/types/streams.ts

A small optimization that avoids a `Promise.resolve()` wrapper for common case enqueueing.
`dequeue()` now returns `Promise<T> | T`, which makes a couple of call sights that relied `then()` slightly more complicated, but overall the reduction in Promise creation seems worth it.

chore(shared): avoid promise wrapping in the common case

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/server/multi/config.test.ts

Default to 15-minute sync intervals and 12-hour snapshots.
This makes the restarts download on average 24 files (48 max) and catch up with 7.5 minutes (15 max) of changes, with full db snapshots to s3 happening twice daily.

feat(zero-cache): make litestream defaults less aggressive

---

packages/zero-cache/src/auth/load-permissions.test.ts
packages/zero-cache/src/auth/load-permissions.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-cache/src/auth/write-authorizer.test.ts
packages/zero-cache/src/auth/write-authorizer.ts
packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/mutagen/mutagen.authz.pg-test.ts
packages/zero-cache/src/services/mutagen/mutagen.ts
packages/zero-cache/src/services/view-syncer/client-handler.test.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zero-cache/src/services/view-syncer/snapshotter.test.ts
packages/zero-cache/src/services/view-syncer/snapshotter.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

Replaces the "zero" constant name with an `appID` parameter in code that reads the replicated `permissions`, `clients`, and `schemaVersions` tables.
This value plumbed from the top level config, and is currently hard-coded to "zero", so this PR in and of itself has no behavioral change.
This is in preparation for transitioning the existing `--shard-id` parameter to an `--app-id`. 
Context: https://www.notion.so/replicache/Zero-Upstream-Organization-1a33bed8954580e9a03fdddf81690fcc

chore(zero-cache): plumb an "appID" to code that reads `permissions`, `clients`, `schemaVersions`

---

packages/zero-cache/src/auth/load-permissions.test.ts
packages/zero-cache/src/auth/load-permissions.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-cache/src/auth/write-authorizer.test.ts
packages/zero-cache/src/auth/write-authorizer.ts
packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/mutagen/mutagen.authz.pg-test.ts
packages/zero-cache/src/services/mutagen/mutagen.ts
packages/zero-cache/src/services/view-syncer/client-handler.test.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zero-cache/src/services/view-syncer/snapshotter.test.ts
packages/zero-cache/src/services/view-syncer/snapshotter.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

Temporarily revert to do a release w/o this.
Reverts rocicorp/mono#3865

Revert "chore(zero-cache): plumb an "appID" to code that reads `permissions`, `clients`, `schemaVersions`"

---

packages/zero-cache/src/services/litestream/config.yml

Restore the `monitor-interval` to the default value of `1 second`, which is the rate at which the database is monitored locally. This has the side effect of kicking off the initial replica sync immediately (technically, after 1 second), which is necessary for publishing an initially synced replica from the `replication-manager` to `view-syncers`.
Henceforth, the replica is updated at `ZERO_LITESTREAM_INCREMENTAL_BACKUP_INTERVAL_MINUTES` intervals.

fix(zero-cache): trigger an initial litestream sync immediately

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/server/multi/config.test.ts
packages/zero-cache/src/services/litestream/commands.ts
packages/zero-cache/src/services/litestream/config.yml

Add a configuration option for the wal size threshold at which litestream performs a checkpoint, which corresponds to creating a wal segment that is eventually backed up to s3.

feat(zero-cache): add configuration for litestream checkpoint threshold

---

packages/z2s/src/compiler.pg-test.ts
packages/z2s/src/test/chinook/chinook.pg-test.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/zero.json.test.ts
packages/zero-protocol/src/connect.test.ts
packages/zero-schema/src/builder/schema-builder.test.ts
packages/zql/src/query/query-impl.query.test.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.test.ts
packages/zql/src/query/query.ts
packages/zql/src/query/static-query.ts
packages/zqlite/src/query.test.ts

`query.run` has to return a promise on the server (we're invoking PG) so it'll need to return a promise on the client as well so the code for custom mutators is isomorphic between the two.

feat!(zql): `query.run` now returns a promise

---

packages/zero/Dockerfile

fix: Remove log level override that was defaulting zero-cache

---

packages/z2s/src/test/chinook/get-deps.ts
packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/scripts/deploy-permissions.ts
packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/server/multi/config.test.ts
packages/zero-cache/src/services/change-source/custom/change-source.test.ts
packages/zero-cache/src/services/change-source/custom/change-source.ts
packages/zero-cache/src/services/change-source/custom/sync-schema.ts
packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.ts
packages/zero-cache/src/services/change-source/pg/schema/ddl-test-utils.ts
packages/zero-cache/src/services/change-source/pg/schema/ddl.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/ddl.ts
packages/zero-cache/src/services/change-source/pg/schema/init.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/init.ts
packages/zero-cache/src/services/change-source/pg/schema/published.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.ts
packages/zero-cache/src/services/change-source/pg/schema/validation.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.pg-test.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.ts
packages/zero-cache/src/services/mutagen/mutagen-test-shared.ts
packages/zero-cache/src/services/mutagen/mutagen.authz.pg-test.ts
packages/zero-cache/src/services/mutagen/mutagen.pg-test.ts
packages/zero-cache/src/services/mutagen/mutagen.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts

Adds plumbing for naming upstream schemas by an `appID` rather than forcing `"zero"` and `"zero_{*}"`.
The `appID` value is still hard-coded to `"zero"` at the top-level, so this PR should not result in a behavioral change.
Configurability and migration is forthcoming.
https://www.notion.so/replicache/Zero-Upstream-Organization-1a33bed8954580e9a03fdddf81690fcc

chore(zero-cache): plumb an `appID` and use it for naming upstream PG schemas

---

packages/zero-cache/src/server/main.ts
packages/zero-cache/src/services/view-syncer/cvr-store.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/row-record-cache.ts
packages/zero-cache/src/services/view-syncer/schema/cvr.ts
packages/zero-cache/src/services/view-syncer/schema/init.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

Changes the name of the CVR schema from `cvr_{SHARD_ID}` to `{APP_ID}_{SHARD_ID}/cvr`.
This allows zero-cache's from multiple apps and shards to use the same DB for the CVR.
The appID is still hardcoded to "zero", but will eventually be configurable.
Note that there is no migration for this change; new view-syncer use the new schema and notify clients with unknown CVRs to refresh. This is necessary because there can be multiple view-syncers, and new and old ones must be able to coexist.
https://www.notion.so/replicache/Zero-Upstream-Organization-1a33bed8954580e9a03fdddf81690fcc

feat(zero-cache): scope the cvr schema within the appID

---

packages/zero-pg/package.json
packages/zero-pg/src/mod.ts
packages/zero/package.json
packages/zero/src/pg.ts
packages/zero/tool/build.ts
packages/zero/tsconfig.server.json

So users can `import {createPushHandler} from '@rocicorp/zero/pg'`
Usage example to follow in zbugs update(s).

feat(zero-pg): add the zero-pg package to `zero`

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/server/multi/config.test.ts
packages/zero-cache/src/services/change-streamer/storer.ts

Fixes an initialization-time race condition in which results in a deadlock if the first subscriber (the backup replicator) is ahead of the change DB. In this case, the lookup for the initial watermark gets into a deadlock with the catchup transaction if the client only has a single connection.
Though this should only happen in development, it's good to guard against nevertheless.
The fixes are to: 
* remove the lookup of the last watermark when doing catchup. this is informational only anyway.
* set the default connection count to 5 instead of 1. this also speeds up catchup when multiple view-syncers are subscribing at the same time.

fix(zero-cache): fix deadlocking race condition in change streamer

---

package-lock.json
packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zql/src/ivm/exists.push.test.ts
packages/zql/src/ivm/exists.ts

Rework the logic in Exist that currently results in a "split push" to push a single Change.

fix(zql): Remove split-push from exists

---

packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/pg/decommission.pg-test.ts

Get the publications from the upstream shard instead of the replica. The latter may be out of sync (if litestream doesn't back up a new replica in time), which we will need to detect in a different way.

fix(zero-cache): get publications from the upstream shard

---

packages/zero-cache/src/services/change-streamer/change-streamer-service.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.ts
packages/zero-cache/src/services/change-streamer/storer.pg-test.ts
packages/zero-cache/src/services/change-streamer/storer.ts

Force a resync if the `replication-manager`'s own replica is behind the change db.

fix(zero-cache): auto-reset if the replication-manager is behind the change db

---

packages/zero-cache/src/services/change-streamer/storer.pg-test.ts
packages/zql/src/ivm/exists.fetch.test.ts
packages/zql/src/ivm/exists.push.test.ts
packages/zql/src/ivm/exists.ts
packages/zql/src/ivm/join.ts

The overlay solution to split push results in relationship's being inconsistent between Nodes at the same level of the tree during push.  This means its not correct to reuse cached sizes across rows during push. 
With this change initial hydration is really the only time that the cross row cache optimization is having an impact.

fix(zql): Exist operator: remove cached size reuse across rows during push 

---

packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/services/change-source/custom/change-source.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.ts
packages/zero-cache/src/services/change-streamer/schema/init.pg-test.ts
packages/zero-cache/src/services/change-streamer/schema/tables.pg-test.ts
packages/zero-cache/src/services/change-streamer/schema/tables.ts
packages/zero-cache/src/services/change-streamer/storer.pg-test.ts
packages/zero-cache/src/services/replicator/schema/replication-state.ts

The change db clears its data if it sees a replica with a different `replicaVersion` that what it was last initialized with. However, this can only safely be done right after an initial-sync. For any other scenarios, we cannot guarantee that the change db can correctly catch up subscribers, so auto-reset to get the systems back in line with each other.

fix(zero-cache): resync if the change db cannot service the replica

---

packages/zero-cache/src/services/change-source/pg/decommission.ts
packages/zero-cache/src/services/change-source/pg/schema/ddl.ts

There's no need to manually remove event triggers. Because they invoke functions defined in the shard schema, dropping the shard schema (with cascade) results in removing the functions and triggers. The unit test continues to pass unchanged.

chore(zero-cache): simplify decommission logic

---

packages/zero-client/src/client/zero.ts

This makes it consistent with what we do for `WebSocket` and makes it a little easier to use Zero in SSR environments.
Surprisingly commonly people don't even want to actually sync server-side they just want to be able to _isntantiate_ Zero server-side to avoid too much branching.
I'm not entirely sure this is a great idea, but at least it is consistent for now.

Emit a warning if no IDB instead of hard crash.

---

packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts

The stack trace is now logged at debug level when the client is closed.
This allows associating errors that happens during close.
https://bugs.rocicorp.dev/issue/3598

feat(zero-client): log stack on close

---

packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-cache/src/workers/connection.ts
packages/zero-cache/src/workers/syncer-ws-message-handler.ts
packages/zero-client/src/client/test-utils.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/close-connection.ts
packages/zero-protocol/src/up.ts

When Zero close is called we send a special close reason that is interpreted by the view syncer.
We send this close reason on pagehide when persisted is false. This websocket send goes through in unload when the tab is closed or reloaded. Different browsers deals with navigation differently.
https://replicache.notion.site/Close-Beacon-Yes-or-no-1ab3bed895458060bf8ad19603a2979f
In the view syncer, when we get this clean close we delete the client which means that it will no longer make queries desired by that client.

feat(zero): WebSocket close beacon

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/db/migration-lite.test.ts
packages/zero-cache/src/db/migration-lite.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/multi/config.test.ts
packages/zero-cache/src/server/replicator.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.pg-test.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.ts
packages/zero-cache/src/services/replicator/schema/replication-state.test.ts
packages/zero-cache/src/services/replicator/schema/replication-state.ts
packages/zero-cache/src/workers/replicator.ts

`VACUUM` is a heavyweight operation that takes:
* 150% the time it takes to copy rows in initial sync (on NVMe)
* 50% the time it takes to copy rows in initial sync (on EBS)
It is particularly unnecessary right after initial-sync, where fragmentation should be very low (and can be forced to 0 by limiting to a single table copy worker). Indexes in particular should be completely contiguous now that they are created post-copy (#3835)
VACUUM-ing on every server restart can also be considered a premature optimization, and without empirical evidence that VACUUM-ing is needed, it does not justify slowing down server startup, particularly for large databases.
Automatic VACUUMs are replaced with manual policies. 
* The currently implemented policy is a periodic interval (defaulting to never). 
* …

feat(zero-cache): faster sync+startup with manual vacuum policy

---

packages/zero-cache/src/services/view-syncer/database-storage.ts
packages/zqlite/src/db.test.ts
packages/zqlite/src/db.ts

Tune operator storage to operate more like memory (with "unsafe" settings such as `journal_mode = OFF`), and prevent runaway storage usage by using incremental vacuum to reclaim space (above 50 MB) when client groups closed.

feat(zero-cache): compact operator storage with incremental vacuum

---

packages/zero-cache/src/db/pg-to-lite.test.ts
packages/zero-cache/src/db/pg-to-lite.ts
packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/pg/schema/published.pg-test.ts

SQLite has limited constraints on what DEFAULT values it accepts when adding a column:
https://www.sqlite.org/lang_altertable.html#altertabaddcol
Detect when an added column violates those constraints and initiate an `--auto-reset` in response. (The alternative an status quo is replication getting stuck)
User reports:
https://discord.com/channels/830183651022471199/1346154873661554768/1346562509024530463
https://bugs.rocicorp.dev/issue/3359

feat(zero-cache): auto-reset on an unsupported ADD COLUMN schema change

---

packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/mod.ts
packages/zero-pg/src/custom.pg-test.ts
packages/zero-pg/src/custom.ts
packages/zero-pg/src/db.ts
packages/zero-pg/src/mod.ts
packages/zero-pg/src/query.pg-test.ts
packages/zero-pg/src/query.ts
packages/zero-pg/src/test/util.ts
packages/zero-pg/src/web.ts
packages/zql/src/mutate/custom.ts

Mutator code should be able to run on the client or server.
This:
1. Moves `ServerTransaction` types out of the `pg` library and into `ZQL` which is shared on client and server
2. Create a `type Transaction = ServerTransaction | ClientTransaction`
The latter type lets the transaction be correctly narrowed for mutators:
```ts
myMutator(tx: Transaction) {
if (tx.location === 'server') {
// `token` only exists on `tx` in the server.
verifyToken(tx.token);
}
}
```
Here is some example usage in zbugs:
https://github.com/rocicorp/mono/blob/eaed250073db4528e1506ff9671f47c9fe0645ac/apps/zbugs/mutators.ts

feat(custom-mutators): re-work transaction types to allow code sharing

---

packages/zero-protocol/src/protocol-version.test.ts

This is similar to the analogous one in `ast.test.ts`

chore(zero-protocol): flag when PROTOCOL_VERSION might need to be bumped

---

apps/zbugs/src/pages/issue/issue-page.tsx

the comparison:
```ts
displayed?.shortID !== undefined
```
would cause a navigate loop since `shortID` gets set to `null` not `undefined` optimistically.
You can repro this error by using `zbugs` offline.
Found when testing custom mutators e2e with an offline api server.

chore(zbugs): shortID is null optimistically

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/schema/cvr.ts
packages/zero-cache/src/services/view-syncer/schema/init.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

We used to delete the desired queries of a client when the client was
deleted. This was causing the queries and its rows to be removed from
the client group and when a client is re-added the rows had to be
fetched again.
Instead, when a client is deleted, we inactive the desired queries of
the deleted client. This way, the queries will use the ttl to determine
if the queries and its rows should be kept or removed.

feat(zero): Inactive desired queries when deleting a client 

---

packages/replicache/src/db/rebase.test.ts
packages/replicache/src/db/rebase.ts
packages/replicache/src/persist/persist.ts
packages/replicache/src/persist/refresh.ts
packages/replicache/src/replicache-impl.ts
packages/replicache/src/replicache-options.ts
packages/replicache/src/transactions.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/replicache-types.ts
packages/zero-client/src/client/zero.ts

zeroOption is a minimal interface that Replicache will call when:
- pullEnd
- persist
- refresh
- mutate
happen. Replicache will invoke
- `advance` whenever it's main head moves forward.
- `getTxData` to fork IVM sources whenever it needs to rebase
- `init` on construction to populate the IVM sources
Invoking the above three methods in `persist.ts`, `refresh.ts`, `replicache-impl.ts::mutate`, `replicache-impl.ts::maybeEndPull` will happen in the next PR.

feat(replicache): add `zeroOption` to allow Zero to hook into Replicache events

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/protocol/current/data.ts
packages/zero-cache/src/services/change-source/protocol/version.test.ts
packages/zero-cache/src/services/replicator/change-processor.test.ts
packages/zero-cache/src/services/replicator/change-processor.ts
packages/zero-cache/src/services/replicator/test-utils.ts
packages/zero-cache/src/types/lite.test.ts
packages/zero-cache/src/types/lite.ts

When a table is configured with `REPLICA IDENTITY FULL`, the full rows are sent as the "keys", and all of the columns are considered the "keyColumns". 
However, these rows/columns cannot safely be used as keys because they may contain `NULL` values.
To handle these replication messages, create keys from the full rows using the primary key / unique index information from the replicated table schema.
User request: https://discord.com/channels/830183651022471199/1288232858795769917/1347172642507063368

feat(zero-cache): support replication of tables with REPLICA IDENTITY FULL

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/protocol/current/data.ts
packages/zero-cache/src/services/replicator/change-processor.test.ts
packages/zero-cache/src/services/replicator/change-processor.ts
packages/zero-cache/src/services/replicator/schema/change-log.test.ts
packages/zero-cache/src/services/replicator/schema/change-log.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts

Support introducing rows that were not originally synced to the replica during initial sync via `UPDATE` operations. This is termed "resumptive replication" and is used for operations in which new tables/rows are introduced into the replica after initial sync, including:
* when altering a publication to include new tables or columns
* [resharding](https://www.notion.so/replicache/Zero-Sharding-1903bed89545803a9345dffc1e781048?pvs=4#1913bed8954580458202fb378ffffaba) (future feature)
In such operations, the rows in the new tables are "touched" with an innocuous update to push the data through the replication stream, e.g.
```sql
BEGIN;
ALTER PUBLICATION my_zero_pub ADD TABLE my_table;
UPDATE my_table SET id = id;
COMMIT;
```
User report: …

fix(zero-cache): support "resumptive" replication

---

packages/shared/src/objects.ts

Based on benchmarks: https://gist.github.com/arv/1b4e113724f6a14e2d4742bcc760d1fa

chore(shared): use fastest (for chrome/v8) strategies for object helpers

---

packages/zql/src/builder/builder.ts
packages/zql/src/ivm/take.push.test.ts

Part of larger effort to update ivm unittests to use `buildPipeline`.
Fixes bug in `buildPipeline` around limit 0 exposed by this change.

refactor(zql): update take.push.test to use runPushTest/buildPipeline

---

packages/zql/src/query/query-impl.ts

This is purposely done in a non-configurable way to make it easy to patch to 0.16. Will make configurable on main in a followup.

feat(zero): Isolated logging of slow queries in client.

---

packages/zql/src/builder/builder.test.ts
packages/zql/src/builder/builder.ts
packages/zql/src/ivm/exists.ts
packages/zql/src/ivm/join.push.test.ts
packages/zql/src/ivm/join.ts
packages/zql/src/ivm/memory-source.ts
packages/zql/src/ivm/source.test.ts
packages/zql/src/ivm/source.ts
packages/zql/src/ivm/take.push.test.ts
packages/zql/src/ivm/take.ts
packages/zqlite/src/table-source.ts

This slightly simplifies take and join logic, but more importantly it avoids having to add fairly complex overlay logic in take and join to correctly handle split pushes.  Instead the overlay logic for edits split into a remove and add is centralized at the source layer.  
This is done by gathering the join keys and partition keys in builder and passing them to the source connection as a set called splitEditKeys.  If the an edit modifies the values of any of these keys, then the source will push it as a remove followed by an add instead of as an edit.
Added asserts in join and take ensuring no unexpected edits are received.

refactor(zql): move splitting of edits up to source

---

packages/z2s/src/compiler.output.test.ts
packages/z2s/src/compiler.ts
packages/z2s/src/test/chinook/chinook.pg-test.ts
packages/z2s/src/test/chinook/get-deps.ts

The tests that compare ZQL vs ZQLite vs PG output only tested hydration.
Add `push` tests that push:
- add
- remove
events into sources.
`edit` to come shortly.
---
The motivation to do this now is to support testing the tldraw fix so we can have the most confidence that it works in all environments.

test(zql): impl `push` tests for pg vs zql vs zqlite

---

packages/zql/src/ivm/catch.ts
packages/zql/src/ivm/exists.push.test.ts
packages/zql/src/ivm/exists.ts
packages/zql/src/ivm/join.push.test.ts
packages/zql/src/ivm/join.ts
packages/zql/src/ivm/test/push-tests.ts

Adds overlay logic to join for when join splits a push from its child input, in to multiple pushes to its output (because the child matches/matched multiple parents).

fix(zql): split push overlay logic for join

---

packages/replicache/src/db/write.ts
packages/replicache/src/mutation-recovery-test-helper.ts
packages/replicache/src/persist/persist.test.ts
packages/replicache/src/persist/persist.ts
packages/replicache/src/persist/refresh.test.ts
packages/replicache/src/persist/refresh.ts
packages/replicache/src/replicache-impl.ts
packages/replicache/src/replicache-options.ts
packages/replicache/src/sync/pull.ts
packages/zero-client/src/client/context.test.ts
packages/zero-client/src/client/context.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/ivm-branch.test.ts
packages/zero-client/src/client/ivm-branch.ts
packages/zero-client/src/client/zero-rate.test.ts
packages/zero-client/src/client/zero-rep.ts
packages/zero-client/src/client/zero.ts

Persist requires some more invasive changes and will be in a separate PR.
Calls to `advance` are the key thing to review. `advance` replaces our use of `experimentalWatch` to update the main IVM sources. The main difference from experimentalWatch is that `advance` sends in the expected hash we're advancing from and the hash we're advancing to. This allows `advance` to set an invariant that we always advance in order. The IVMBranch also keeps track of its current hash so it can compute diffs to use to patch forks in `forkToHead(hash)`.
I'm surprised we never ran into problems with `experimentalWatch` as I would imagine there would have been cases where a `refresh` diff against HEAD-1 jumps ahead of a `pullEnd` diff against HEAD-0 (due to awaits) or vice-versa.

feat(custom-mutators): maintain and fork ivm through pull, mutate, refresh

---

packages/zero-pg/src/web.ts

Zero wraps the args in an array. This was done to make it easier to transition to support varags to mutators but we have not done that yet.

fix(zero-pg): zero receives args as an array

---

packages/z2s/src/test/schema-gen.ts
packages/zero-client/src/client/context.ts
packages/zero-client/src/client/custom.bench.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/zero.ts

When users have really large schemas it gets expensive to create all the `schemCRUD` and `schemaQuery` objects up-front.

feat(zero-client): 100x speedup: lazy creation of queries and crud for mutators

---

packages/zql/src/ivm/view-apply-change.test.ts
packages/zql/src/ivm/view-apply-change.ts

The edit branch was incomplete.
We replace the old object with the new object transferring the ref count.
If we edit the value of a non primary column, we transfer the ref count to the new object.
If we edit the value of a primary column, we need to decrement the ref count of the old object and increment the ref count of the new object.

fix(zql): Fix ref count for edit in applyChange

---

packages/replicache/src/dag/lazy-store.test.ts
packages/replicache/src/dag/lazy-store.ts
packages/replicache/src/persist/persist.ts
packages/zero-client/src/client/ivm-branch.ts
packages/zero-client/src/client/test/create-db.ts

Persist.ts persists the mutations from the current client onto the perdag. Mutations can do reads so we need to create IVM sources at the same head we'll be rebasing onto.
To get IVM into the right state, we diff from `ivmMain.hash` to `perdagHead.hash`.
When doing this diff, `perdagHead` is not loaded into the memdag yet so `LazyStore` must do a "source read" against the persistent store. See below "_getSourceRead()":
https://github.com/rocicorp/mono/blob/148b1608c353e49c934cf6edd26950eeafb03bc3/packages/replicache/src/dag/lazy-store.ts#L249-L254
The problem with this is that we already have a write transaction open against the persistent store when going to do the diff.
https://github.com/rocicorp/mono/blob/148b1608c353e49c934cf6edd26950eeafb03bc3/packages/replicache/src/persist/persist. …

feat(custom-mutators): patch IVM sources in `persist.ts`, allow providing a `sourceRead` to `LazyRead`

---

packages/zero-cache/src/services/replicator/change-processor.test.ts
packages/zero-cache/src/services/replicator/change-processor.ts

The change to support resumptive replication (#3937) assumed that Postgres always sends the full row for UPDATE messages. However, this is not true for rows with large values that are TOASTed, in which unchanged values are sent with an "unchanged" tag, but the value is otherwise not included:
https://www.postgresql.org/docs/current/protocol-logicalrep-message-formats.html#PROTOCOL-LOGICALREP-MESSAGE-FORMATS-TUPLEDATA
To restore support for updates of these rows, revert to using `UPDATE` statements by default, and only falling back to an `INSERT` / `UPSERT` if the former did not modify any rows (i.e. resumptive replication).
It is a TODO to figure out how to make resumptive replication work for rows with TOASTed values.

chore(zero-cache): restore support for partial updates

---

packages/zero-cache/src/server/replicator.ts
packages/zero-cache/src/services/change-source/custom/sync-schema.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.ts
packages/zero-cache/src/services/change-source/replica-schema.ts
packages/zero-cache/src/workers/replicator.ts

Perform post-initial-sync upgrades on a replica in the view-syncer, so that a new view-syncer can theoretically restore a backup from an old replication-manager.
User report: https://discord.com/channels/830183651022471199/1349521451169874012/1349923954474881026

fix(zero-cache): perform replica upgrades in view-syncer

---

.github/workflows/js.yml

By using `needs` in the CI workflow, we can avoid running the `install` job multiple times.

chore: Improve CI caching

---

.github/workflows/bencher-benchmarks-pr.yml
.github/workflows/bencher-benchmarks.yml
.github/workflows/js.yml
.github/workflows/perf-smoke.yml
.github/workflows/perf-v2.js.yml
package-lock.json
packages/replicache-perf/package.json
packages/replicache/package.json
packages/zql/package.json
packages/zqlite/package.json

The cache only caches the browser which are stored in `~/.cache/ms-playwright`. Playwright also needs system libraries. Even if we get a cache hit we need to ensure the libraries are installed.

chore: Playwright CI caching

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.ts
packages/zero-cache/src/services/change-source/protocol/current/data.ts
packages/zero-cache/src/services/change-source/protocol/version.test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.ts
packages/zero-cache/src/services/replicator/change-processor.ts
packages/zero-cache/src/types/lite.test.ts
packages/zero-cache/src/types/lite.ts
tools/load-generator/src/main.ts

This is the first step to adding support for unparsed JSON in the change stream, which is the equivalent of the optimization done for initial-sync (#3919), applied to incremental replication.
Avoiding JSON parsing and instead ferrying values directly as JSON strings from Postgres (through the change-streamer, to the replicator,) to the replica improves performance by 20 ~ 25% in the change-streamer and 25 ~ 30% in the replicator:
Rolling this out is a two-step process. 
1. In the first step (this PR), an option is introduced into the change protocol to declare, per transaction, the format of the JSON values in the comprising changes, and a client (i.e. view-syncer) supporting this protocol connects to the change-streamer at `v1`. The server (replication-manager), however, starts off …

chore(zero-cache): add support for unparsed json values in the change stream

---

packages/zero-cache/src/services/view-syncer/client-handler.test.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/cvr-store.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-client/src/client/zero-poke-handler.test.ts
packages/zero-protocol/src/poke.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

Bumps to minimum supported `/sync/v.../connect` wire protocol version to `v6`, released in zero v0.16, which made the `pokeStart.cookie` optional and in favor of `pokeEnd.cookie`. (#3832)
With that minimum supported version, the `cookie` field can be removed from the `PokeStart` message and the server no longer sends it.
The logic which skips empty flushes (to avoid quadratic writes) is now also unconditional, since clients started supporting that protocol from v5. (#3735)

chore(zero-protocol): bump min protocol to v6 and clean up obsolete code

---

.github/workflows/js.yml
package.json
vitest.workspace.ts

This changes how we run the JS tests on the CI.
We are no longer using turbo for this. Instead we use vitest workspaces.
Also, we use `--changed origin/main` to only run tests for the files that have changed.

chore: Only run relevant tests

---

.github/workflows/sst-gigabugs-deploy.yml
.github/workflows/sst-prod-deploy.yml
.github/workflows/sst-sandbox-deploy.yml.disabled
apps/zbugs/README.md
apps/zbugs/api/index.ts
apps/zbugs/api/tsconfig.json
apps/zbugs/package.json
apps/zbugs/playwright/README.md
packages/zero-cache/src/auth/jwt.test.ts
packages/zero-cache/src/auth/jwt.ts
packages/zero-cache/src/scripts/create-jwk.ts
prod/sst/sst.config.ts

This will allow the client and server to share jwt verification code by relying on the public key for jwt verification.
Given that verification code can be shared, custom mutator definitions become much shorter
---
Add the following to your `.env` for local development:
```ini
PRIVATE_JWK='{"kty":"RSA","n":"6g6Jm7gd1CFEa57jTt1lsBTNdNNkixrGi8yUVTBOKitojBN-Hrf2GPC1vaR4MfMJnh6Exk8JRP4bs3cGuws3I4xpTR6N0jaBKYKOeFbOEmWavKAmZb92wRF2zKLX6K1_69IRnXOqsjvRngiz5utVH6ttKKYdnoOHQZGJGQuiKea9zApVtFafoh4NYBFEsncgvEdLJ1SwgfHnaRm6LzWDw8IvJc2iBqPKOZ7FNqlZnZnyzuBDlAcYDVLPBrc1J5TCsn_5jHsUo1oTXZnxuFT7OlzlzQj1ihHuGTNY-fEpBZBbwor1bZgByDHcjzmRFlItF_jJbC2kd0bGNwU1iHQaUw","e":"AQAB","d":"Dq5CwLBXuUqCOXiJ1r8u9aXDDU-FFZnkV43JcAkg81GDCTuKbvAoUNV9pht-09iOreBJgQwhZLZw6Qd6Ne6KKCynyN01wA2zJEtlbEmQO2SBbtC3bS0JNyrv7Kik1O9Xqrm …
```

chore(zbugs): swap to using a `jwk`

---

packages/zero-cache/src/services/replicator/change-processor.ts

As suggested in https://github.com/rocicorp/mono/pull/3935/files#r1993637868

chore(zero-cache): reduce allocations when making keys for replica identity full

---

package-lock.json
packages/zero-cache/package.json
packages/zero/package.json

By modifying package-lock.json, we can force the version of pg-types

chore: Force pg-types version to 4

---

packages/replicache/src/replicache-impl.ts
packages/replicache/src/replicache-options.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/zero-rep.ts
packages/zql/src/mutate/custom.ts

This reduces the amount of boilerplate we need to write by allowing the server and client to share more code.

chore(mutators): make auth token available on the client transactions

---

packages/zql/src/builder/builder.test.ts
packages/zql/src/ivm/take.push.test.ts
packages/zql/src/ivm/take.ts

`applyViewChange` asserts that when format is singular, there is only ever a single node.  When this assert fails the error message is `single output already exists`. 
This change https://github.com/rocicorp/mono/commit/b453073597931d53d12d259f64ba14f05dab1c88 introduced a regression that caused this assert to fail for queries or subqueries with limit 1 (and thus format singular), when the view had one node for the query/subquery, and a new node was pushed that was less than the existing node, and thus should replace it.
The above change made Take first push the `add` of the new node, temporarily increasing its output size to `limit + 1`, before pushing the `remove` of the old  node, brining its size back to `limit`.  This was done because it allowed take to maintain the correct …

fix(zql): fix `single output already exists`

---

packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

This should have been together with #4005

chore(zero-protocol): bump protocol to v8 to safely drop support for v5

---

packages/z2s/src/compiler.output.test.ts
packages/z2s/src/compiler.pg-test.ts
packages/z2s/src/compiler.ts
packages/z2s/src/test/chinook/chinook.output.test.ts
packages/z2s/src/test/chinook/chinook.pg-test.ts
packages/zero-cache/bench/benchmark.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-cache/src/auth/write-authorizer.ts
packages/zero-cache/src/scripts/run-query.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zero-client/src/client/context.ts
packages/zero-pg/src/query.ts
packages/zql/src/builder/builder.ts
packages/zql/src/builder/test-builder-delegate.ts
packages/zql/src/query/test/query-delegate.ts
packages/zql/src/query/test/test-schemas.ts
packages/zqlite/src/query.test.ts
packages/zqlite/src/test/source-factory.ts

z2s needs to understand how to map to/from server names as `pg` will be using server names for its columns and tables. `z2s.compile` now takes the schema as a parameter so it can map names as it builds queries.
The `z2s` test suite is an integration test that:
1. Creates a PG DB
2. Uses `initialSync` to create a replica
Due to (2), that replica will be using server names so this PR also adds support for server names in zqlite tests. This more faithfully reproduces our production setup.

chore(zqlite,z2s): map to/from server names in z2s

---

apps/zbugs/src/components/filter.tsx
apps/zbugs/src/components/user-picker.tsx
apps/zbugs/src/pages/issue/issue-page.tsx
apps/zbugs/tsconfig.json
packages/replicache-perf/tsconfig.json
packages/shared/src/find-last-index.test.ts
packages/shared/src/find-last-index.ts
packages/shared/src/has-own.test.ts
packages/shared/src/has-own.ts
packages/shared/src/to-sorted.test.ts
packages/shared/src/to-sorted.ts
packages/shared/tsconfig.json
packages/zero-advanced/tsconfig.json
packages/zero-react/tsconfig.json
packages/zero-solid/tsconfig.json
tools/client-simulator/src/main.ts
tsconfig.json
turbo.json

This changes zbugs to compile to es2022, and updates all packages to use
es2022 lib. The latter is so that we do not end up using builtins that
are not supported in es2022.

chore: Use es2022 in all packages

---

packages/z2s/src/compiler.output.test.ts
packages/z2s/src/compiler.pg-test.ts
packages/z2s/src/compiler.ts
packages/z2s/src/test/chinook/chinook.output.test.ts
packages/z2s/src/test/chinook/chinook.pg-test.ts
packages/z2s/src/test/chinook/schema.ts
packages/z2s/src/test/comparePg.ts
packages/z2s/src/test/discord-repro.pg-test.ts
packages/zqlite/src/test/source-factory.ts

Updates `chinook/schema.ts` to use different names for server and client names are snaked-cased. E.g., `track_id` => `trackId`
Also uncovered some z2s errors since Postgres does not allow using a column alias in `order by`, `on` or `where`.
E.g., we must do:
```sql
SELECT track_id as id FROM track WHERE track.track_id = 1
```
Not:
```sql
SELECT track_id as id FROM track WHERE track.id = 1
```

chore(z2s): more alias fixes

---

packages/zero-cache/src/db/transaction-pool.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/multi/run-worker.ts
packages/zero-cache/src/services/life-cycle.ts
packages/zero-cache/src/services/replicator/change-processor.ts
packages/zero-cache/src/services/runner.ts
packages/zero-cache/src/services/view-syncer/schema/types.ts

Remove the confusing readiness timeout at startup. Readiness can take arbitrarily long for large initial syncs, and should be handled by a production parameter such as `healthCheckGracePeriodSeconds`. There is no point in responding to health checks if the server is not fully ready.
Instead, periodically log which workers are still being awaited.

chore(zero-cache): remove readiness timeout

---

apps/zbugs/api/push.ts
apps/zbugs/api/tsconfig.json
apps/zbugs/shared/mutators.ts
apps/zbugs/shared/schema.ts
apps/zbugs/shared/validators.ts
apps/zbugs/src/comment-query.ts
apps/zbugs/src/components/avatar-image.tsx
apps/zbugs/src/components/emoji-panel.tsx
apps/zbugs/src/components/user-picker.tsx
apps/zbugs/src/emoji-utils.test.ts
apps/zbugs/src/emoji-utils.ts
apps/zbugs/src/hooks/use-user-pref.ts
apps/zbugs/src/hooks/use-zero.ts
apps/zbugs/src/pages/issue/comment-composer.tsx
apps/zbugs/src/pages/issue/comment.tsx
apps/zbugs/src/pages/issue/issue-composer.tsx
apps/zbugs/src/pages/issue/issue-page.tsx
apps/zbugs/src/zero-setup.ts
apps/zbugs/tsconfig.json
packages/zero-client/src/client/custom.ts
packages/zero-pg/src/custom.ts
packages/zero-pg/src/query.ts

We're ready to port zbugs to custom mutators.
Missing features:
- threading mutation errors from the api server back to the client
- adding an auth error type to the protocol so the api server can cause the token to be refreshed on the client
Bugs:
- `related` does not do type conversion in `z2s` (zql 2 sql). E.g., dates come back as strings rather than milliseconds when doing reads, which contain `related` calls, on the server via ZQL. This doesn't impact zbugs at the moment.
Setting `created` and `modified` for an issue in the custom mutator does indeed cause an i-loop until the API server responds.
The steps are as follows:
1. Mutation runs to create the issue
2. UI navigates to the issue page
3. `useQuery` runs to set up `j/k` queries
4. This writes a new query
5. This causes the …

feat(zbugs): swap to custom mutators

---

packages/shared/src/ref-count.test.ts
packages/shared/src/ref-count.ts
packages/zero-solid/src/use-query.test.ts
packages/zero-solid/src/use-query.ts

In 0.17 we started reusing views when the query is the same. This caused an issue where we ended up calling destroy on the view multiple times.
Now we keep a ref count on the view and only destroy it when the ref count reaches zero.

fix(zero-solid): Fix issue with reused views

---

packages/zero-solid/src/use-query.test.ts
packages/zero-solid/src/use-query.ts

We were using the ref count to determine when to destroy the materialized view but we were not clearing the cached view so we end up using the destroyed view.

fix(zero-solid): fix useQuery ref count

---

apps/zbugs/api/index.ts
packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-pg/src/custom.ts
packages/zero-pg/src/web.pg-test.ts
packages/zero-pg/src/web.ts

Placed them into the query string so a user can route based on `app_id`.

chore(mutators): pass schema and app-id to push endpoint

---

package-lock.json
packages/zero-cache/package.json
packages/zero-cache/src/services/change-source/pg/logical-replication/binary-reader.ts
packages/zero-cache/src/services/change-source/pg/logical-replication/pgoutput-parser.ts
packages/zero-cache/src/services/change-source/pg/logical-replication/pgoutput.types.ts
packages/zero-cache/src/services/change-source/pg/logical-replication/stream.pg-test.ts
packages/zero-cache/src/services/change-source/pg/logical-replication/stream.ts
packages/zero-cache/src/services/change-source/pg/lsn.test.ts
packages/zero-cache/src/services/change-source/pg/lsn.ts
packages/zero-cache/src/types/streams.ts

This grafts the protocol parsing logic from [pg-logical-replication](https://github.com/kibae/pg-logical-replication/tree/main/src/output-plugins/pgoutput) onto a connection managed by a `postgres.js` client rather than a `pg` client.
The benefits of this rewrite include:
* **Better connection handling**: postgres.js supports an `ssl: prefer` option that automatically detects if ssl is supported. We currently have to mimic this on the `pg` client by trying SSL first and falling back to non-SSL
* **Flow control**: The new implementation uses the postgres.js `.readable()` API to pipeline the replication stream to the application's change Subscription, allowing the change-streamer to exert backpressure on the postgres. (This reuses the flow control mechanism for the websocket connection to …

chore(zero-cache): rewrite logical replication on postgres.js

---

packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/mutation-tracker.ts
packages/zero-protocol/src/push.ts

Start threading mutation results back to the client. This class tracks in-flight mutations on the client.
Next up:
1. Return a stream from `pusher`, on the server, to be proxied down to the client --
https://github.com/rocicorp/mono/blob/06697185aea4770c5aa7063e2f2012d0136ebe5f/packages/zero-cache/src/workers/connection.ts#L184-L192
2. Update `makeReplicacheMutator` so the mutator invokes the `mutation-tracker` on `initial` run of the mutation and that promise is returned to the caller
https://github.com/rocicorp/mono/blob/06697185aea4770c5aa7063e2f2012d0136ebe5f/packages/zero-client/src/client/custom.ts#L119-L129
3. Deal with client side edge cases: connection closed, connection not open.
- Probably neither of these reject the mutation since they'll be retried in those cases.

chore(mutators): `mutation-tracker` to track mutation status

---

packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/pg/logical-replication/stream.ts

Move the logic for retrying the `START_REPLICATION` command into the logical-replication library.
This is a more precise place to put it, and it also reduces flakiness in the library's unit test.

chore(zero-cache): move the start replication retry logic into the library

---

packages/zero-cache/src/services/change-streamer/change-streamer-service.ts
packages/zero-cache/src/services/change-streamer/storer.ts

Protect the `replication-manager` from being overwhelmed by a highly active replication stream by exerting back pressure from the change-streamer when the queued changes exceeds a threshold.
Currently this threshold is based on a simple count. It can later be improved to be memory-size based. This works for both postgres and custom change sources.
Loadtests confirm that a change-streamer without this protection eventually crashes, while the back-pressure-protected change-streamer continues humming along.
Without back-pressure:
With back-pressure:

feat(zero-cache): protect the replication-manager with back pressure

---

packages/shared/src/arrays.test.ts
packages/shared/src/arrays.ts
packages/z2s/src/compiler.ts
packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-cache/src/workers/connection.ts
packages/zero-cache/src/workers/syncer-ws-message-handler.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/down.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts
packages/zero-protocol/src/push.ts

Just like `ViewSyncer` returns an `OutboundStream` which is proxied down to the client, follow the same pattern for passing mutation responses back to the client.
https://github.com/rocicorp/mono/blob/06697185aea4770c5aa7063e2f2012d0136ebe5f/packages/zero-cache/src/workers/connection.ts#L184-L192

chore(mutators): add an `OutboundStream` for `pusher`

---

packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/mutation-tracker.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/push.ts

Mutators now return a:
```ts
export type PromiseWithServerResult<T, S> = Promise<T> & {server: Promise<S>};
```
The `server` property allows waiting for authoritative results.
Usage looks like:
```ts
const close = z.mutate.issue.close();
// optionally await the local write
await close;
// optionally await/get/catch the server result
close.server.catch((e) => toast.showError(e));
```

feat(mutators): allow waiting for server results on the client

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts

This will facilitate debugging persistent OwnershipError loops like https://discord.com/channels/830183651022471199/1347991012123082833

chore(zero-cache): include the last connect time in OwnershipErrors

---

packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

Fix race conditions in which a CVR fails to load due to an erroneous OwnershipError.
The view-syncer is only started up in response to a connection, so initialization time should be considered a `lastConnectTime`. This will remedy the situation in which the CVR gets loaded (because the replica is considered ready) before the `initConnection` message is received.
Also add handling in the case that _any_ client message is received before the `initConnection` message. We don't expect this to happen, but are now resilient to it and will log a warning.
User report: https://discord.com/channels/830183651022471199/1347991012123082833

fix(zero-cache): fix CVR ownership takeover race conditions

---

packages/zero-cache/src/services/view-syncer/client-schema.test.ts
packages/zero-cache/src/services/view-syncer/client-schema.ts

Include a tip on how to sync non-public schemas is the missing table is from a non-public schema.
https://discord.com/channels/830183651022471199/1288232858795769917/1352746725777084517

chore(zero-cache): include tip for syncing tables from non-public schemas

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts

Fix an edge case that was discovered in a stress test, whereby a row that was not previously in the CVR was added during an IVM advancement, and then removed in a different batch (of 10,000 rows).

chore(zero-cache): fix add-then-remove edge case

---

packages/zero-cache/src/db/transaction-pool.ts
packages/zero-cache/src/services/change-source/pg/logical-replication/stream.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.ts
packages/zero-cache/src/services/change-streamer/storer.ts
packages/zero-cache/src/services/life-cycle.ts
packages/zero-cache/src/services/replicator/change-processor.ts
packages/zero-cache/src/services/runner.ts
packages/zero-cache/src/services/view-syncer/schema/types.ts

Fix two issues discovered while stress-testing the change-streamer with very large transactions.
1. If the replication stream disconnects, the change-streamer will loop around and reconnect. Before doing so, wait for any pending changes to flush to the change db in order to resume from the correct watermark. Otherwise, a duplicate key error can occur:
2. The replication stream may disconnect if the change-streamer is applying back pressure and thus not responding to the periodic keepalives from postgres. To signal to postgres that the subscriber is still alive, manually send keepalive responses if none have been sent for longer than postgres's 30-second keepalive interval. This prevents postgres from disconnecting when the replication-manager is busy processing messages.

chore(zero-cache): better handling of large upstream transactions

---

tools/client-simulator/src/main.ts

Add a `--millis-between-messages` option to the client simulator to simulate slow connections using tcp back pressure.

chore(load-harness): simulate slow connections in the client-simulator

---

apps/zbugs/README.md
apps/zbugs/api/discord.ts
apps/zbugs/api/notify.ts
apps/zbugs/api/push-handler.ts
apps/zbugs/api/server-mutators.ts
apps/zbugs/shared/mutators.ts
apps/zbugs/src/zero-setup.ts
packages/zero-cache/src/auth/jwt.ts

There are a few issues here though:
1. We are awaiting on the notification within the PG tx :-|. I had to do this because the notification wasn't getting sent if I didn't. Need to figure out what's going on there.
2. I observed that if there was not a matching mutator name, the mutation retries forever. It should be silently skipped.
At the same time refactored how created/modified dates are set. This seems slightly nicer?

feat(zbugs): Add discord notifications.

---

package.json

You can now run `npm run test:watch` and `npm run check-types:watch` from the mono root and it will do the right thing. to watch for changes and re-run tests and type checks.

chore: Add test:watch and check-types:watch to root

---

packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

NodeJS timers have a maximum limit of 2^31-1 milliseconds, which is about 24.8 days. This commit fixes the issue by setting the timer to 1h which will then reschedule the expiration work again.
https://bugs.rocicorp.dev/issue/3645

fix(zero-cache): Fix too large timer exception

---

packages/zero/tool/create-canary.js

It was reporting success even when docker push failed.

chore: fix create-canary

---

packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/push.ts

Problem 1:
- custom mutators did not close the connection on `InvalidPush` errors (OOO mutation, bad push version).
Problem 2:
- custom mutators would resolve client promises for a mutation on `InvalidPush` errors. This was wrong since these mutations will be retried later. No longer resolve these promises. We do that by not sending a response for mutations that fail with `InvalidPush` errors and instead close the connection.
--- 
Removed 'token' error type as that is unused. Left protocol version unchanged since it was unused.

chore(mutators): close connection on fatal errors

---

packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-cache/src/services/view-syncer/client-handler.test.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-cache/src/workers/connection.ts

Use TCP backpressure to protect the zero-cache against memory blowup from either slow downstream connections or over-zealous upstream messages (e.g. DOS).
By simulating a large download (#4080) over a slow connection (#4076), the load harness is able to create a scenario in which a zero-cache (without downstream backpressure) crashes with an OOM.
With back-pressure applied, the zero-cache eventually succeeds in the streaming the large download to the client:
This works by having IVM wait for downstream messages to be flushed to the connection before computing the next batch of data to be sent. For mutations, the Pusher similarly waits for responses to be sent before computing the next batch of results.
Upstream flow control is similarly enforced by only pulling messages from the …

feat(zero-cache): protect zero-cache with client-side back-pressure

---

packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/mutation-tracker.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts
packages/zero-protocol/src/push.ts

Adds a `JSON` field to `error` and `ok` responses to allow the user to return any sort of extra data required.

chore(mutators): deal with extra properties in mutator responses

---

packages/zero-cache/src/auth/load-permissions.ts

User report: https://discord.com/channels/830183651022471199/1288232858795769917/1353875570211029052

fix(zero-cache): improve "no permissions message" with --app-id flag

---

packages/shared/src/sentinels.ts
packages/zero-client/src/client/custom.bench.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/mutation-tracker.ts
packages/zero-client/src/client/zero.ts

Problem:
> if a user checks permissions on the client in a custom mutator, nothing prevents the queries that provided the permission data from being deregistered before the mutator is rebased.
>
> It’d be a weird interaction to:
>
> 1. Have the mutator succeed
> 2. Navigate to a new page
> 3. Have the mutator rebase and fail because the queries it used are gone
This implement's @arv's idea:
> That is a good point. We should keep queries in the mutators alive until mutator has been confirmed
>
> I don’t think we need to change ref counting… we just need to add the queries to the desired set when the mutator is run the first time and removed when the mutator is acknowledged
https://rocicorp.slack.com/archives/C013XFG80JC/p1742815429158529

chore(mutators): register read queries in mutators

---

packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/decommission.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/ddl.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/ddl.ts
packages/zero-cache/src/services/change-source/pg/schema/init.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/init.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.ts

Adds support for `ALTER SCHEMA ...` ddl changes, which essentially map to one or more table renames on the replica.
This is necessary to implement (one strategy of) non-disruptive resyncs, but is technically also a user-usable feature given that non-public schemas are supported.
Also clean up / simplify the trigger logic as it is now based on a simple diff. The new format deprecates the unused `table` and `index` fields and does not constrain the `tag` values, thus improving forwards compatibility.

feat(zero-cache): support ALTER SCHEMA ddl changes

---

packages/z2s/src/compiler.ts
packages/zero/tool/build.ts

Since '@databases/sql' references `node:fs` which causes headaches when people are bundling.

chore(zero-client): Build zero with '@databases/sql/web'

---

packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/mutation-tracker.ts

If we've enqueued messages to the stream, wait for those messages to be consumed before closing the connection.
Previously a failure in a batch of mutations could cause the connection to close before the success responses ever got sent.
```
m1 : success
m2 : success
m3 : success
m4 : fail
```
^-- this would close the stream before responses to m1 -> m3 could be processed.

chore(mutators): await pushed messages before failing the stream

---

package-lock.json
packages/replicache/package.json
packages/zero-client/package.json
packages/zero/package.json

It was not needed any more.
Verified by looking at the output files.

chore: Remove tsc-alias

---

packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts

Pending mutations were being pushed on page load but not on reconnect of the websocket after initial page load.
Found this by injecting code to fail mutations 50% of the time.

chore(zero-client): call `push` when reconnecting

---

packages/zero-client/src/client/custom.bench.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/mutation-tracker.ts
packages/zero-client/src/client/query-manager.test.ts
packages/zero-client/src/client/query-manager.ts
packages/zero-client/src/client/zero.ts

This goes back to the problem of having different data on `initial` run of the mutator than in a rebase.
The original idea was to register any read queries that are used in the mutator. 
That is less stable and less easily understood than freezing the active query set so queries cannot be removed until all outstanding mutations are committed. This approach will also cause less query churn on the backend.

feat(mutators): prevent query removal while there are pending mutations

---

packages/z2s/src/compiler.pg-test.ts
packages/zero-cache/src/test/db.ts

Demonstrates that the sql generated by the z2s compiler is not dependent on these configured type conversions.

chore(z2s): Don't use postgres.js type config in compiler test

---

packages/z2s/src/sql.test.ts
packages/z2s/src/sql.ts
packages/z2s/src/test/chinook/chinook.pg-test.ts
packages/z2s/vitest.config.ts

z2s is going to be sender a large JSON blob that contains all args.
We don't want to bind this JSON blob for each time it is referenced in the SQL but rather only a single time.
This adds a format function (mostly copied from the internal implementation here: https://github.com/ForbesLindesay/atdatabases/blob/cb1b783ad9aafd85461ef7f4b86160b94b717468/packages/sql/src/web.ts#L212) that de-dupes values and reuses placeholders.

chore(z2s): use a single placeholder for identical values

---

packages/z2s/src/sql.test.ts
packages/z2s/src/sql.ts

Allows us to control type conversion by JSON packing the arguments to the query then extracting from JSON where they're used.
example:
```ts
expect(
formatPgJson(
sql`SELECT * FROM "user" WHERE "id" = ${jsonPackArg('number', 1)} `,
),
).toMatchInlineSnapshot(`
{
"text": "SELECT * FROM "user" WHERE "id" = ($1->>0)::numeric",
"values": [
"[1]",
],
}
`);
```

chore(z2s): bind from json packed args

---

packages/zero-cache/src/services/replicator/change-processor.ts
packages/zero-cache/src/workers/replicator.ts

Avoid crashing the replicator when it is unable to obtain the SQLite lock. `litestream` can hold the lock for an arbitrary amount of time (e.g. when checkpointing a large commit), and crashing can cause corruption or inhibit forward progress.
Instead, retry indefinitely, in the same way that litestream retries its checkpointing indefinitely.
User report: https://discord.com/channels/830183651022471199/1354595802332401845/1354595877301260511

fix(zero-cache): avoid crashing on busy-timeout

---

packages/z2s/src/sql.test.ts
packages/z2s/src/sql.ts
packages/zero-pg/src/custom.pg-test.ts
packages/zero-pg/src/custom.ts
packages/zero-pg/src/test/schema.ts
packages/zero-schema/src/table-schema.ts

All args are now passed to sql queries as text. We then convert that text to the appropriate type. This is to bypass any specific type conversions a user may have installed that would not be compatible with Zero.
Mutagen can now write to timestamp columns.

chore(z2s): convert args internally via SQL in Mutagen

---

packages/z2s/src/compiler-bigint.pg-test.ts
packages/z2s/src/compiler.ts
packages/zero-cache/src/types/bigint-json.ts

Throws an error when a bigint value exceeds the safe integer range of JavaScript numbers.

chore(z2s): handle bigints

---

packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/pg/decommission.pg-test.ts
packages/zero-cache/src/services/change-source/pg/decommission.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.ts
packages/zero-cache/src/services/change-source/pg/schema/init.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/init.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.pg-test.ts
packages/zero-cache/src/types/shards.ts

`zero-cache` previously used a constant replication slot named `{app-id}_{shard-num}`, requiring a previously synced `zero-cache` instance to be shut down (and the replication slot dropped and re-created) in order for the new `zero-cache` to perform initial sync. This can result in a lot of downtime when resyncing large databases.
With non-disruptive resync, an initial-syncing `zero-cache` creates a replication slot of the form `{app-id}_{shard-num}_{timestamp}` and records it in a `replicas` upstream table when initial-sync completes. This allows the old replication slot to continue servicing the old `zero-cache` while the new one performs initial-sync.
Once initial-sync is complete, all subscribers to any replication slot for the shard are shutdown, and all but the new replication slot …

feat(zero-cache): non-disruptive resync

---

package-lock.json
packages/z2s/package.json
packages/z2s/src/compiler-bigint.pg-test.ts
packages/z2s/src/compiler.pg-test.ts

It should be possible to extend this approach to the chinook tests as well.

chore(z2s): run z2s compiler tests again postgres.js and node-postgres

---

packages/z2s/src/sql.pg-test.ts
packages/z2s/src/sql.ts

The ZQL query builder allows the use of `IN` and passing arrays so we need to support that in z2s too.
E.g.,
`SELECT * FROM foo WHERE bar = ANY [1,2,3,4]`

chore(z2s): deal with arrays of values in the query builder

---

packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/replicator/change-processor.test.ts
packages/zero-cache/src/services/replicator/change-processor.ts

Even though SQLite does not support non-constant defaults, zero can support _changes_ of column defaults to arbitrary expressions, e.g.
```sql
ALTER TABLE foo ALTER COLUMN bar SET DEFAULT now();
```
because changing a column's defaults in Postgres does not modify existing values.
https://www.postgresql.org/docs/current/sql-altertable.html#SQL-ALTERTABLE-DESC-SET-DROP-DEFAULT
> The new default value will only apply in subsequent INSERT or UPDATE commands; it does not cause rows already in the table to change.
and so column values will continue to come through the replication stream.
This was handled correctly most of the time; the `change-streamer` ignores changes to column defaults. 
However, if a change to a column default was followed by a subsequent change that _is_ relevant to zero …

fix(zero-cache): fix handling of column default value changes

---

apps/zbugs/server/push-handler.ts
packages/zero-pg/src/mod.ts
packages/zero-pg/src/postgres-connection.ts

This way if user just wants to use postgres() they don't need to implement the adapter.

chore(zero-pg): Adds a PostgresConnection adapter.

---

apps/zbugs/api/index.ts
apps/zbugs/server/push-handler.ts
packages/zero-pg/src/mod.ts
packages/zero-pg/src/web.pg-test.ts
packages/zero-pg/src/web.ts
packages/zero-protocol/src/push.ts

* Make type of params and body unknown so user doesn't have to validate.
* Move mutators to arg of process() so PushProcessor can be shared.

chore(zero-pg): Few dx niceties for PushProcessor.

---

packages/shared/src/deep-merge.ts
packages/zero-client/src/client/zero.ts

The intersection operator was creating overloaded functions.

chore(zero): DeepMerge custom mutator type.

---

apps/zbugs/src/components/markdown.tsx
apps/zbugs/src/index.css

- Nested checklists now display properly.
- New typographical scale on detail view (Perfect fourths, 1.333)

chore(zbugs): Fixing nested checklists. New detail view typographic scale

---

packages/replicache/src/replicache-impl.ts
packages/replicache/src/replicache-options.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/mutation-tracker.ts
packages/zero-client/src/client/query-manager.test.ts
packages/zero-client/src/client/zero-rep.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/push.ts

Nobody was a fan of:
```ts
type Result = Promise<{
server: Promise<MutationResult>
}>
```
Refactor things so we can do:
```ts
type Result = Promise<void> & {server: Promise<MutationResult>}
```
Or, if we add 1 more layer of wrapping in Zero, we can do:
```ts
type Result = {client: Promise<void>, server: Promise<void>};
```
although it seems more appropriate to return the "thing that should be awaited" as a top level promise.
Why was this so hard to pull off? Because the mutator implementation is buried deep within an async callstack and each async function will wrap its result in a promise automatically. We also needed information about the `mutationID`, in order to create the server promise, which can only be gotten from deep inside the call stack from `withWrite`.
Example of the issue: …

feat(mutators)!: move `sever` promise up a level

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr-store.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

This builds on (and completes) the intent of #3736, which is to avoid flushing the CVR and sending pokes to clients for which an advancement did not result in any material changes.
The hole in the logic of the original PR was that an advancement is associated with a new version, and that version was eagerly set in the CVRUpdater, thus counting as a "material change" and bypassing the flush-skipping logic. The unit test also verified this incompletely by not properly waiting for the no-op change to propagate to the replica and view-syncer before committing the affecting change.
In this fix, the CVR update / put is delayed until checking for material changes (i.e. to the rows or query tables), correctly implementing the intent of the first PR. The test is also corrected to verify that the …

feat(zero-cache): eliminate quadratic writes/pokes (take 2)

---

packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts

Fix a test that verifies an error condition that can happen in either of two pokes, depending on the order in which things get processed in the view-syncer.

chore(zero-cache): fix flaky test

---

packages/zero-cache/src/services/replicator/change-processor.test.ts
packages/zero-cache/src/services/replicator/schema/change-log.test.ts
packages/zero-cache/src/services/replicator/schema/change-log.ts
packages/zero-cache/src/test/lite.ts
packages/zero-cache/src/workers/replicator.ts

Removes `O(table-size)` change log operations that were previously used to save space after a table-wide operation, such as truncating a table or replicating a schema change.
For schema changes over large tables, this ends up in a lot of SQLite I/O operations (i.e. `O(table-size)`) that can delay subsequent replication processing for many minutes, which on balance is not worth the space savings.
With this change, the changeLog cleanup is removed from the critical replication path, and instead moved to the maintenance vacuum task which happens at startup if configured, allowing the operation to be performed, if desired, without affecting availability.  
User report: https://discord.com/channels/830183651022471199/1354595802332401845/1356307016196296744

feat(zero-cache): improve replication performance for schema changes

---

packages/zero-schema/src/table-schema.ts
packages/zero-schema/vitest.config.ts
packages/zql/src/query/query-impl.ast.test.ts
packages/zql/src/query/query-impl.query-kitchen-sink.test.ts
packages/zql/src/query/query-impl.query.test.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.test.ts
packages/zql/src/query/test/test-schemas.ts

This adds a limit 1 to the query when using one in the relation. This is fixes an issue where we end up sending multiple rows down where only one is expected.

fix(zql): When using one in the relation we should add a limit 1

---

packages/zql/src/query/query-impl.ts

Bit unclear on why TypeScript didn't catch that the implementations of this abstract method did not except undefined for Format but the abstract signature did. 
Regression was introduced here https://github.com/rocicorp/mono/commit/19e5a333e8e43e4e50e8b46336939013d21c322b

fix(zql): fix potentially undefined format

---

packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts

The dropping of a replication slot is non-transactional, and sometimes it takes a bit for pg to update the `pg_replication_slots` table.
Swap the order of the PG calls and add a `sleep()` to reduce false positive failures.

chore(zero-cache): reduce flakiness in test

---

packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts

Fix the unit test query so that the test only queries replication slots relevant to the test.

chore(zero-cache): fix test failures due to unrelated tests

---

packages/zero-cache/src/types/streams.ts
packages/zero-cache/src/types/ws.ts

Send pings at 30 second intervals to keep websockets alive in the face of connection idle timeouts (which defaults to 60 seconds on AWS).
Also use them to determine liveness, closing connections if not.
This is used both for the replicator <-> change-streamer connection and for custom change sources.
User report: https://discord.com/channels/830183651022471199/1357355649905987635/1357392133815931122

feat(zero-cache): send pings to check and signal websocket liveness

---

packages/z2s/src/collate.pg-test.ts
packages/z2s/src/compiler-bigint.pg-test.ts
packages/z2s/src/compiler.pg-test.ts
packages/z2s/src/compiler.ts
packages/zero-pg/src/query.pg-test.ts
packages/zero-pg/src/query.ts

https://bugs.rocicorp.dev/issue/3715

fix(z2s): return `undefined` for empty result set and `one` format

---

apps/zbugs/api/index.ts
apps/zbugs/server/push-handler.ts
packages/zero-pg/src/web.test.ts
packages/zero-pg/src/web.ts

Users do not know what types to provide and keep getting errors about missing properties.
https://bugs.rocicorp.dev/issue/3704?f=1&d=2
https://bugs.rocicorp.dev/issue/3711
https://discord.com/channels/830183651022471199/1357260393176895508/1357835830256734381
While not fully typed (as in, not asking for the exact shape of the query string and body) we at least now specify that the query params need to be a record or a URLSearchParams object. We also specify that the request body must be provided as JSON.

feat!(mutators): re-add types to `push-processor`

---

apps/zbugs/server/notify.ts
apps/zbugs/server/server-mutators.ts
apps/zbugs/shared/auth.ts
packages/analyze-query/src/bin-analyze.ts
packages/z2s/src/compiler.pg-test.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-pg/src/query.pg-test.ts
packages/zero-schema/src/builder/schema-builder.test.ts
packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/collate.pg-test.ts
packages/zql-integration-tests/src/compiler-bigint.pg-test.ts
packages/zql/src/query/query-impl.query.test.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.test.ts
packages/zql/src/query/query.ts
packages/zqlite/src/query.test.ts

Users can now:
```ts
await z.query.issue.limit(5);
```
rather than
```ts
await z.query.issue.limit(5).run();
```

feat(zql): make queries thenable

---

.gitignore
package-lock.json
packages/replicache-doc/package.json
packages/replicache/src/error-responses.ts
packages/replicache/src/kv/idb-store.ts
packages/replicache/src/kv/store.ts
packages/replicache/src/persist/collect-idb-databases.ts
packages/zero-client/package.json
packages/zero-client/scripts/generate-docs.ts
packages/zero-client/src/client/zero.ts
packages/zero-client/src/mod.ts
packages/zql-integration-tests/package.json
packages/zql/src/ivm/operator.ts
packages/zql/src/query/query.ts

This started as adding JSDoc to zero-client Query but ended up adding a simple doc server generated with Co-Pilot.
Usage
cd packages/zero-client
npm run docs:server
Then go ahead and open http://localhost:3000 in your browser.
Edit your JSDoc and see changes on save.

chore(zero-client): Doc dev server and JSDoc for zero

---

.gitignore
packages/zero-pg/src/query.ts
packages/zql-integration-tests/src/chinook/chinook.pg-test.ts

`zpg` removes some manual steps when using the z2s compiler

chore(test): use `zpg` instead of manual compiler invocation

---

packages/zql-integration-tests/src/helpers/data-gen.ts
packages/zql/src/query/test/data-gen.ts
packages/zql/src/query/test/query-gen.ts

this is in support of cleaning up all the various overlapping tests we created in the last mile of custom mutators:
- compiler.pg-test.ts
- chinook.pg-test.ts
- collate.pg-test.ts
- compiler-bigint.pg-test.ts

chore(zql): generate test data based on schema(s)

---

packages/zql-integration-tests/src/helpers/runner.ts

this is in support of cleaning up all the various overlapping tests we created in the last mile of custom mutators:
compiler.pg-test.ts
chinook.pg-test.ts
collate.pg-test.ts
compiler-bigint.pg-test.ts
They all compare their results against pg, sqlite, memory and they all currently hand craft their own setup and comparisons.
They all need (should) test the push path too. Push is not yet implemented in this pr.
usage looks like:

chore(test): factor out a common test runner for zpg/zqlite/zql

---

packages/zero-pg/src/custom.pg-test.ts
packages/zero-pg/src/custom.ts

crud mutators would fatal if someone passed in a present optional column. E.g.,:
```ts
const row = {
id: 1,
optional: undefined,
};
```
instead of:
```ts
const row = { id: 1 };
```
update to handle both forms of "missing" / "undefined" in JS

fix(mutators): allow keys that are set to `undefined`

---

packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zero-cache/src/services/view-syncer/snapshotter.test.ts
packages/zero-cache/src/services/view-syncer/snapshotter.ts

Fix processing of updates where a non-primary-key column, that can be part of a key, is changed.
The update logic now takes into account the eventual union-key with which the row(s) are keyed, representing the update as a `remove` + `add` if the union-key values differ.
User report: https://discord.com/channels/830183651022471199/1359294559393157120/1359460401900687390

fix(zero-cache): fix incremental updates of key-able columns

---

packages/zero-cache/src/services/change-source/custom/change-source.test.ts
packages/zero-cache/src/services/change-source/custom/change-source.ts
packages/zero-cache/src/services/change-source/protocol/current/control.ts
packages/zero-cache/src/services/change-source/protocol/version.test.ts

Handle the change-source protocol message:
```js
['control', {tag: 'reset-required', message: ...}]
```
during initial sync of custom change sources, responding by auto-resetting and running initial sync from scratch.
User request: https://discord.com/channels/830183651022471199/1356728897085112411/1359618257983766609
@cbnsndwch 
@DAlperin

chore(zero-cache): allow custom change source to force an auto-reset in initial sync

---

packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

Improve tracking of hydration time by taking IVM time-slicing into account (e.g. and not over-counting the time when the process has been yielded).
This is otherwise a no-op change that subsequent PRs will build off of to add overload-handling logic based on the hydration time.
Context: https://discord.com/channels/830183651022471199/1358875333243179039/1359568739544207371

chore(zero-cache): make hydration timing more precise

---

packages/zero-cache/src/services/view-syncer/view-syncer.ts

Add IVM time slicing to the (rare) scenario in which a non-CVR-updating hydrating is run.

chore(zero-cache): time-slice non-update hydration

---

packages/ast-to-zql/src/ast-to-zql.test.ts
packages/ast-to-zql/src/ast-to-zql.ts

```json
{
"limit": 50,
"table": "email_message",
"where": {
"type": "and",
"conditions": [
{
"op": "EXISTS",
"type": "correlatedSubquery",
"related": {
"system": "client",
"subquery": {
"alias": "zsubq_member_states",
"table": "email_message_member_state",
"where": {
"type": "and",
"conditions": [
{
"op": "=",
"left": {
"name": "direction",
"type": "column"
},
"type": "simple",
"right": {
"type": "literal",
"value": "OUTBOUND"
}
},
{
"type": "simple",
"left": {
"type": "column",
"name": "workspace_id"
},
"right": {
"type": "literal",
"value": null
},
"op": "="
}
]
},
"orderBy": [
[
"id",
"asc"
]
]
},
"correlation": {
"childField": [
"message_id"
],
"parentField": [
"id"
]
}
}
},
{
"type": "simple",
"left": {
"type": "column",
"name": "workspace_id"
},
"right": {
"type": "literal", …
```

fix(ast-to-zql): remove extraneous paren

---

packages/ast-to-zql/src/ast-to-zql.test.ts
packages/ast-to-zql/src/ast-to-zql.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-cache/src/auth/read-authorizer.test.ts
packages/zero-pg/src/query.ts
packages/zero-react/src/use-query.test.ts
packages/zero-react/src/use-query.tsx
packages/zero-solid/src/solid-view.test.ts
packages/zero-solid/src/solid-view.ts
packages/zero-solid/src/use-query.ts
packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/collate.pg-test.ts
packages/zql-integration-tests/src/compiler-bigint.pg-test.ts
packages/zql-integration-tests/src/helpers/runner.ts
packages/zql/src/ivm/array-view.test.ts
packages/zql/src/ivm/array-view.ts
packages/zql/src/ivm/test/push-tests.ts
packages/zql/src/ivm/view.ts
packages/zql/src/query/query-impl.ast.test.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.ts
packages/zql/src/query/static-query.ts
packages/zql/src/query/test/query-gen.ts
packages/zql/src/query/test/util.ts
packages/zql/src/query/typed-view.ts

BREAKING CHANGE. Bindings need to be updated.
Instead of hanging this of off the Query we add it to the View that materialize returns. This allows us to remove the updateTTL method from the Query interface and the QueryImpl class.

chore(zql)!: Deprecate Query updateTTL

---

packages/zero-cache/src/server/runner/config.test.ts
packages/zero-cache/src/server/runner/config.ts
packages/zero-cache/src/server/runner/run-worker.ts
packages/zero-cache/src/server/runner/zero-dispatcher.ts

Rename the former `TenantDispatcher` to the `ZeroDispatcher` and always use it for dispatch to the zero-cache(s), even when there is only a single "tenant".
This will facilitate building top-level process management features that can apply to all scenarios.

chore(zero-cache): always run through the top-level dispatcher

---

packages/shared/src/options.ts
packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/server/runner/config.test.ts
packages/zero-cache/src/server/runner/run-worker.ts
packages/zero-cache/src/server/runner/zero-dispatcher.ts
packages/zero-cache/src/services/dispatcher/websocket-handoff.test.ts
packages/zero-cache/src/services/dispatcher/websocket-handoff.ts

Adds a `--run-lazily` (or `ZERO_RUN_LAZILY`) option to delay starting the zero-cache processes until the receiving the first (websocket) request:
`--run-lazily` usage documentation:
```
Delay starting the zero-cache processes until the first request.
Note: This works as expected in single-node mode. While it is technically usable
in a multi-node setup, there is a bootstrapping complication in that the
view-syncer must first restore the replica from litestream before connecting to
the replication-manager (to know where to continue replication from). If the
replication-manager has never run, there will be no replica file to restore, and
the view-syncer will fail to start up, never connecting to the replication-manager.
As such, it is not recommended to run a replication-manager lazily.
``` …

feat(zero-cache): option to run the zero-cache lazily

---

packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.ts
packages/zero-cache/src/services/change-source/pg/schema/init.ts

Recover from upstream corruption that stopped being detected when resyncs were made to be non-disruptive.
Extra checks are performed before initial sync and replication subscription to ensure that the expected publications still exist upstream. If they are missing, a full (disruptive) resync is used to recover.
User report: https://discord.com/channels/830183651022471199/1358765533545369842/1359925435902726336

fix(zero-cache): resync when publications are missing

---

packages/zero-pg/src/web.test.ts
packages/zero-pg/src/web.ts

Almost all the framework (Next.js, SolidStart, TanStack Start) pass in a Request in their POST handlers. This is a standard Web API interface that is popular in FE servers.

chore(zero-pg): Support Request param ion PushProcessor

---

packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql/src/query/expression.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.ts

By using the one from the protocol these now have a single source of truth.

chore(zql): Fix missing NOT LIKE operators in type

---

packages/zero-cache/src/services/change-streamer/change-streamer-http.ts
packages/zero-cache/src/services/dispatcher/websocket-handoff.test.ts
packages/zero-cache/src/services/dispatcher/websocket-handoff.ts
packages/zero-cache/src/workers/syncer.ts

Discovered by the load harness. The socket handle is `undefined` if it was closed before is it handed off to the subprocess.
Failing to check this will otherwise crash the server.

chore(zero-cache): handle socket closures during websocket handoff

---

packages/z2s/src/compiler.output.test.ts
packages/z2s/src/compiler.ts
packages/z2s/src/sql.test.ts
packages/z2s/src/sql.ts

Currently if you have a `timestamptz` column, and the server timezone is `Europe/London`, when a timestamp is written it's an hour out 😱, because they query ends up being
```sql
INSERT INTO "table" ("id","createdAt") VALUES ($1::text::character varying, to_timestamp($2::text::bigint / 1000.0) AT TIME ZONE 'UTC')
```
where
- `to_timestamp($2::text::bigint / 1000.0)` returns a timestamp with timezone, where the timezone is `Europe/London`
- `AT TIME ZONE 'UTC'` then converts it to a timestamp without the timezone, representing the time in UTC
- Then the insert happens into the column that does want a timezone. It interprets the timestamp as being a timestamp in `Europe/London`, not `UTC`, and therefore it ends up being an hour out
So in this PR I've adjusted it so that if the column is a …

Fix issue with timestamps and `timestamptz` data types

---

packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

User report: https://discord.com/channels/830183651022471199/1358875333243179039/1359565864273186939
Bound the time allowed to process an incremental advancement.
* If it takes more than half of the total hydration time to get through half of the advancement, abort and hydrate at the head of the database.
This solves two problems:
* Bounds the time it takes to handle very large transactions; no need to go through all changes incrementally when re-running the queries is probably faster.
* Avoids runaway wal growth that can happen due to an old transaction holding a lock on the inactive wal file.
In [wal2 mode](https://sqlite.org/cgi/src/doc/wal2/doc/wal2.md), writes alternate between two wal files to allow for increased concurrency between readers and writers. However, it can only …

fix(zero-cache): bound advancement processing and wal(2) growth

---

packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

Pass the `Timer` object into `PipelineDriver.addQuery(...)` as it is done for `advance()` to obviate the need for the `setHydrationTime()` method.

chore(zero-cache): pass the timer into addQuery()

---

packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/mutation-tracker.ts

Discussed with @aboodman --
Any errors returned by the remote endpoint now resolve, rather than reject, the promise and set an error field on the result.

feat(mutators)!: no longer reject server promise on errors

---

apps/zbugs/src/zero-setup.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-cache/src/workers/connection.ts
packages/zero-cache/src/workers/syncer-ws-message-handler.ts
packages/zero-cache/src/workers/syncer.ts
packages/zero-client/src/client/options.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-pg/src/web.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/connect.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

- We previously had no way to initialize the pusher service with custom parameters from the client. This adds an `initConnection` method to `pusher` and extra arguments to the `initConnection` protocol message. 
- Responses to `initConnection` previously could only return a single value but now we must return two: the pusher stream and the view syncer stream.
- The logic to determine if a user had opted into custom mutators was based around the presence of `pushURL` in the config but this can now come from the client itself.

feat(mutators): allow custom headers and query string params

---

packages/z2s/src/compiler.output.test.ts
packages/z2s/src/compiler.ts
packages/zql-integration-tests/src/compiler.pg-test.ts

Reported on discord: https://discord.com/channels/830183651022471199/1288232858795769917/1360371961141661936
Relationships nested in a junction relationship were not working correctly.
Additionally, `#selectCol` conversion logic for date and timestamp types were not being applied to columns of junction relationships.

fix(z2s): junction relationship fixes

---

apps/zbugs/api/index.ts
packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts

If the user's API server returns a 401 we will close the websocket connection with an `AuthInvalidated` error.
This forces the `auth` callback to be called on the client and the ws to be reconnected.
We currently do not have a way to update the JWT without tearing down and restarting the WS connection. That seems like a good future improvement, however. If we do that, we could also skip re-hydration of queries that do not use the modified fields of the JWT.

feat(zero-cache): re-auth on 401s returned by the user's push endpoint

---

packages/analyze-query/src/bin-analyze.ts
packages/zero-cache/bench/benchmark.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-client/src/client/context.test.ts
packages/zero-client/src/client/context.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/test-utils.ts
packages/zero-client/src/client/zero.json.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-client/src/mod.ts
packages/zero-solid/src/create-query.test.ts
packages/zql/src/ivm/array-view.ts
packages/zql/src/query/query-impl.query.test.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.ts
packages/zql/src/query/test/query-delegate.ts
packages/zqlite/src/test/source-factory.ts

BREAKING CHANGE!
```ts
type RunOptions = {
type: 'complete' | 'unknown';
}
interface Query<...> {
...
run(options?: RunOptions): Promise<...>;
}
```
Defaults to `complete` for all queries except for the query used inside
custom mutations which defaults to `unknown`.
This is breaking because the `run` method of the `Query` class now waits
for `complete` results by default. This can lead to the promise returned
never resolving if the `server` is not set (or we are offline).
Another gotcha is that if you call run with `unknown` you get both
unknown and complete results but there is no way to tell which is
which.

feat(zero)!: Add options to Query run

---

packages/zero-client/src/client/context.ts

Not used outside the ZeroContext class.

chore(zero-client): Make some properties private

---

packages/analyze-query/src/bin-analyze.ts
packages/zero-cache/bench/benchmark.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-client/src/client/context.test.ts
packages/zero-client/src/client/context.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/zero.json.test.ts
packages/zero-client/src/client/zero.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.ts
packages/zql/src/query/test/query-delegate.ts
packages/zqlite/src/test/source-factory.ts

BREAKING CHANGE -- This is a breaking change from a previous change but it restores the old 0.18 behavior of running the default query to unknown.
This simplifies the code since run always defaults to unknown now.
We still throw if you try to pass complete to a run inside a custom mutator.

chore(zero-client)!: Change run default to unknown

---

packages/zero-client/src/client/inspector/inspector.test.ts
packages/zero-client/src/client/inspector/inspector.ts
packages/zero-client/src/client/zero.ts

Inspect should be used lazily but if someone creates it eagerly then they can run into issues where zero is not yet connected.

chore(zero-client): inspect should wait for connect

---

packages/zero-cache/src/services/change-source/pg/initial-sync.ts

Purely for debugging convenience, create the internal replica tables before creating the user tables. This results in them getting earlier pages in the `sqlite_schema` table and makes it easier to work with the sqlite internals.
This is also more consistent with how the replica is initialized for custom change sources.

chore(zero-cache): create internal tables first

---

packages/zero-cache/src/services/view-syncer/cvr-store.pg-test.ts
packages/zero-cache/test/pg-15.ts
packages/zero-cache/test/pg-16.ts
packages/zero-cache/test/pg-17.ts
packages/zero-cache/test/pg-container-setup.ts
packages/zql-integration-tests/src/discord-repro.pg-test.ts
packages/zql/src/query/test/test-schemas.ts

Followup for https://github.com/rocicorp/mono/pull/4216
I tested (`zql-integration-tests`) with the patch in the above PR reverted and things broke, so this adds some coverage

Put db in `UTC+1` for integration tests

---

packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-cache/src/workers/connection.ts
packages/zero-cache/src/workers/syncer.ts

JB is hitting a case where a refresh of a tab never produces any logs at all. We're bailing out before we get to any logger calls, pokes, hydrations, etc.
Theories:
- an exception is thrown and swallowed
- `if (client?.wsID !== wsID) {` is always true causing us to early return
- we never acquire the cvr lock and thus never run `initConnection`
this adds more debug logs up the call stack to figure out where things break down.

chore(zero-cache): more debug logs

---

packages/zqlite/src/db.ts

Happening because LoggingIterableIterator doesn't always have iterate() called.
As in *#mapFromSQLiteTypes in table-source.ts.

chore(zero): Not seeing Slow SQLite query warnings for type=total.

---

packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/mutation-tracker.ts
packages/zero-pg/src/web.pg-test.ts
packages/zero-pg/src/web.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts
packages/zero-protocol/src/push.ts

Return "mutation already processed" as an error from the server. In mutation tracker, no longer throw if an ephemeral id is missing for a mutation that says it has already been processed.

fix(zero): deal with receiving many responses for the same mutation

---

packages/zero-cache/test/pg-17.ts

We need to make a few fixes to existing tests before we can incorporate this change.
Some fixes in progress: https://github.com/rocicorp/mono/compare/mlaw/test-fix?expand=1

chore(zero-cache): put all dbs in utc for now

---

packages/zero-cache/src/services/life-cycle.ts

Discord thread w/ original context: https://discord.com/channels/830183651022471199/1361448930058965023
Recently I ran into a pathological shutdown loop in prod, where my replication manager was doing an expensive operation against sqlite and then immediately shutting itself down, even though nothing seemed to actually be wrong. Because this expensive sqlite operation was being done as part of catching up to upstream on every node startup, it was infinitely looping through failed restarts. Logs revealed that shutdown was being triggered by HeartbeatMonitor, which believed it had not received a keepalive request from the load balancer recently. This seemed to be false — the LB was sending keepalives at the normal rate.
The theory at the time was that something was funky with the ordering …

fix(zero-cache): fix incorrect shutdown under initial CPU load

---

packages/zero/Dockerfile

Use a git tag to specify the commit to build the `litestream` executable from. This avoids a stale cache from a (tagless) `git clone`, which may not necessarily contain the subsequent hash in `git checkout <hash>`.
For posterity, this was first run in our litestream repo:
```sh
git tag zero@v0.0.2 zero
git push origin zero@v0.0.2
```

fix(zero): make litestream build in Dockerfile cache-friendly

---

packages/zql-integration-tests/src/helpers/runner.ts

The default of `unknown` causes `run` to return no data in tests.
related: #4234

chore(zql): `run` now needs an option for "complete" vs "unknown"

---

packages/zql-integration-tests/src/helpers/runner.ts

Revert "chore(zql): `run` now needs an option for "complete" vs "unknown""

---

packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/collate.pg-test.ts
packages/zql-integration-tests/src/helpers/runner.ts

TS didn't catch this surprisingly.

chore(z2s): call TestQueryDelegate correctly

---

packages/zero/Dockerfile

Bump to zero@v0.0.3 litestream which contains the fix (https://github.com/rocicorp/litestream/pull/4) for an unreleased bug (https://github.com/benbjohnson/litestream/issues/621).

chore(zero-cache): bump to litestream version with region fix

---

packages/z2s/src/compiler.ts
packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/chinook/get-deps.ts
packages/zql-integration-tests/src/compiler.pg-test.ts
packages/zql-integration-tests/src/helpers/runner.ts

Deletes all the special case code for `chinook` and uses the common integration test runner.
Also expands test coverage now that we've fixed z2s type conversion handling.

chore(z2s): ports `chinook` to `runner`

---

packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts

User reports:
*
Fixes the failure to send row-delete patches in certain scenarios (when IVM generates an add and subsequent remove of a row that will ultimately be removed). In these cases, the row-delete patches were tagged with the wrong `patchVersion`, causing them in to be incorrectly classified as "old" patches and filtered before being sent.

fix(zero-cache): fix incorrect suppression of row-del patches

---

packages/zql-integration-tests/src/chinook/chinook.pg-test.ts

We were getting a different random operator for each backend (pg, sqlite, memory)

chore(z2s): cache random operator generation

---

packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

Fix the row patch deduping logic in #4285 to handle the possibility that multiple versions of a row can be produced by the IVM pipeline.
Also add more end-to-end tests for these multiple-row-appearance scenarios.

chore(zero-cache): account for multiple row versions with deduping

---

packages/shared/src/tool/vitest-config.ts
packages/zero-client/src/client/server-option.ts

There are valid reasons in real apps to have no serverURL, e.g., trial users.

chore(zero): Clarify warning when no serverURL supplied.

---

packages/shared/src/arrays.ts
packages/z2s/src/compiler.output.test.ts
packages/z2s/src/compiler.ts
packages/zero-pg/src/query.ts
packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/collate.pg-test.ts
packages/zql-integration-tests/src/compiler-bigint.pg-test.ts
packages/zql-integration-tests/src/helpers/runner.ts

When server name mappings were added, the compiler got way out of hand. Fixing the `self join` bug would have made everything even more complicated because the fix required introducing aliasing for every table. This PR refactors the compiler so table and column mapping and aliasing only happen in a single place. Qualified column names are also passed everywhere via a `QualifiedColumn` structure so there is never confusion about what "string" a function is dealing with.
---
Two bugs were found when adding more tests to z2s:
1. `self join`
2. `not exists`
Self join failed because we did not auto-alias tables.
Before auto-aliasing we would generate this SQL:
```sql
SELECT (SELECT * FROM employee WHERE employee.reports_to = employee.id) as reports_to FROM employee;
```
which would return no …

fix(z2s): handle self join, not exists

---

packages/zero-cache/src/auth/read-authorizer.test.ts
packages/zero-pg/src/query.ts
packages/zql/src/query/assert-no-not-exists.test.ts
packages/zql/src/query/assert-no-not-exists.ts
packages/zql/src/query/query-impl.ast.test.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/static-query.ts

`NOT EXISTS` can't work reliably on client because:
- Zero only syncs a subset of data to the client
- Client can't distinguish between non-existent rows vs. non-synced rows
- Correct `NOT EXISTS` requires complete knowledge of data
Added `assertNoNotExists()` function to validate conditions and throw
errors when `NOT EXISTS` is used in client queries. Updated `query-impl.ts`
to check conditions after DNF conversion.
https://bugs.rocicorp.dev/issue/3438

fix(zql): Do not allow NOT EXISTS in client queries

---

packages/zero-cache/src/server/start-otel.ts
packages/zero-cache/src/server/syncer.ts

Factor it out into its own function.
- We need to start it for the replication manager too
- We need to start it before creating the log sink as we'll be updating the log sink to sink to otel

chore(zero-cache): factor otel startup out

---

packages/zero-cache/src/server/logging.ts
packages/zero-cache/src/server/otel-log-sink.ts
packages/zero-cache/src/server/otel-start.ts
packages/zero-cache/src/server/syncer.ts

We should still log to console even if the OTEL collector is up.
OTEL allows adding a console exporter but the log format is not the same as our prior format and would require some messaging to make it the same.
Seems easier to just do it this way.

chore(zero-cache): composite sink to keep console logs

---

packages/analyze-query/src/bin-analyze.ts

This definitely used to work but the command line parser is dropping any text after a newline. I tracked this down to being a bug inside the `commandLineArgs` library.
I did not see any options to enable multiline args.

fix(analyze-query): replace newlines with spaces in args for `bin-analyze.ts`

---

packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/mutation-tracker.ts

server errors used to resolve and client errors would reject.
now they both reject.

feat!(zero-client): reject server mutator promise in all error cases

---

packages/zero-protocol/vitest.config.ts

It was missing making npm run test not work from the packages/zero-protocol directory.

chore(zero-protocol): add vitest config

---

packages/shared/src/tool/vitest-perf-json-to-bmf.ts
packages/zero-client/src/client/zero.bench.ts

For some reason `setup` time is contributing to the total benchmark time giving us bad results. Doing setup once results in 10x faster benchmarks as we're now only measuring the thing we intend to measure.
More importantly, the benchmarks now provide meaningful information when changing the value of `N`. Before, the time was dominated by setup time so it was hard to figure out how a query scaled as `N` changed.
Discovered this while investigating a user report: https://bugs.rocicorp.dev/issue/3793
Before:
After:
https://github.com/rocicorp/mono/pull/4313/commits/91c4058dd538b765f504a069f9f08042c37abe87
Bencher expects throughput (e.g., QPS). Vitest outputs a timing per run. Divide 1 second by time per run to get QPS.

chore(bench): remove setup and teardown, invert metric

---

packages/zero-cache/src/types/pg.ts
prod/sst/sst.config.ts

Stop hardcoding the `connect_timeout` on the postgres.js client so that it can be dynamically configured via the `PGCONNECT_TIMEOUT` environment variable, as per https://github.com/porsager/postgres?tab=readme-ov-file#environmental-variables

chore(zero-cache): make the pg connect timeout configurable via PGCONNECT_TIMEOUT

---

packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts

In the case of a stuck Postgres change-source, which has been observed with a Neon upstream (example logs below), 
the replication-manager will continually kill other replication slots, preventing a new resyncing instance from taking over (as its replication slot continually gets deleted by this looping change-streamer).
Change the replication slot logic to only stop-and-drop _new_ replication slots, which allows a newly syncing replication slot to eventually take over the problematic one.
```
",/service/replication-manager/abff0535675e4d3bbbd3d00313e12394
2025-05-03 18:02:58.007,INFO,change-streamer,change-streamer,retrying change-streamer in 25 ms,"{""level"":""INFO"",""worker"":""change-streamer"",""pid"":95,""component"":""change-streamer"",""code"":""CONNECTION_CLOSED"",""errno"":""CO …
```

chore(zero-cache): handle pathological change-source disconnects

---

packages/zero-cache/src/workers/connection.ts

User report: 
https://discord.com/channels/830183651022471199/1367957671621296190/1367958626488160337
This may be the (other?) uncaught exception that can kill the server.

fix(zero-cache): catch exceptions during handle-close

---

packages/analyze-query/src/bin-analyze.ts
packages/zero-cache/src/config/network.ts
packages/zero-cache/src/config/normalize.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/replicator.ts
packages/zero-cache/src/server/runner/run-worker.ts
packages/zero-cache/src/server/runner/runtime.ts
packages/zero-cache/src/server/runner/zero-dispatcher.ts
packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/statz.ts

(with the exception of `bin-analyze`  😉 )
Also adds network interface lookup which will be used for change-streamer discovery. Currently it is simply logged for analysis of interface names in different runtimes.

chore(zero-cache): consolidate config normalization logic into one place

---

packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql/src/ivm/constraint.test.ts
packages/zql/src/ivm/constraint.ts
packages/zql/src/ivm/memory-source.ts
packages/zql/src/query/test/util.ts

No more full table scans to do a point query by primary key on the client.
https://bugs.rocicorp.dev/issue/3793
Before:
After:

fix(zql): O(logn) point queries

---

package-lock.json
packages/zql-benchmarks/package.json
packages/zql-benchmarks/src/chinook.bench.ts
packages/zql-benchmarks/tsconfig.json
packages/zql-benchmarks/vitest.config.pg-17.ts
packages/zql-benchmarks/vitest.config.ts
packages/zql-integration-tests/src/helpers/runner.ts

Since I already created the integration test harness, might as well re-use it for benchmarks too.
- Benchmarks below run without this fix -- https://github.com/rocicorp/mono/pull/4327

chore(zql): hydration benchmark harness

---

packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/ast.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zql-integration-tests/src/helpers/runner.ts
packages/zql/src/query/query-impl.ts

`not(exists(` should be testable as it is used on the server.

chore(zql): fix chinook tests

---

packages/zql-benchmarks/src/chinook-hydration.bench.ts
packages/zql-benchmarks/src/chinook-push.bench.ts
packages/zql-integration-tests/src/helpers/runner.ts

Seemed most efficient for me to knock this out while I was in there.
There are many more benchmarks to write but for another time.
Pushing into a limited query inside the bound is a 40% reduction in speed for zql but not zqlite... I wonder if the time to convert rows to server names via table mapper is dominating??? Seems odd.
`tinybench` seems riddled with bugs (it does not respect any warmup and iterations options, it includes setup and tear down time in its benchmark). Considering swapping to: https://github.com/evanwashere/mitata or opening PRs against tinybench.

chore(zql): harness to benchmark pushes

---

packages/zero/Dockerfile

node:22.15.0 fixes 3 high severity vulnerabilities in node:22.11.0
New litestream version contains a [minor fix](https://github.com/rocicorp/litestream/pull/5) (that didn't affect zero).

chore(zero): update litestream and node

---

packages/zero-pg/src/custom.ts
packages/zero-pg/src/push-processor.ts

User report: https://discord.com/channels/830183651022471199/1367519188851228758/1369351714884423721
some users are ending up with extra junk in the objects they pass to `insert` / `update`, causing exceptions.
They don't know what they're doing wrong since we do not output:
1. the bogus column
2. what table they're tring to access

fix(mutators): assert provided columns actually exist

---

packages/zero-cache/src/services/change-streamer/backup-monitor.ts

Fixes a "circular object" error when trying to log the timeout objects.

chore(zero-cache): fix backup monitor logging

---

packages/shared/src/options.test.ts
packages/shared/src/options.ts

Use the ZERO_OPTION_NAME when outputting errors from flag / env option parsing.

chore(zero-cache): improve messaging for flag/env parse errors

---

packages/zero-cache/src/types/websocket-handoff.test.ts
packages/zero-cache/src/types/websocket-handoff.ts

This will allow more flexible routing of websockets passed between workers. (To be used in an upcoming PR)

chore(zero-cache): include the IncomingMessage in the websocket receiver API

---

.github/workflows/sst-gigabugs-deploy.yml
packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/replicator.ts
packages/zero-cache/src/server/worker-dispatcher.test.ts
packages/zero-cache/src/server/worker-dispatcher.ts
packages/zero-cache/src/services/change-streamer/backup-monitor.test.ts
packages/zero-cache/src/services/change-streamer/backup-monitor.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.ts
packages/zero-cache/src/services/change-streamer/change-streamer-service.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer.ts
packages/zero-cache/src/services/change-streamer/snapshot.ts
packages/zero-cache/src/services/litestream/commands.ts
packages/zero-cache/src/services/replicator/incremental-sync.test.ts
packages/zero-cache/src/services/replicator/incremental-sync.ts
packages/zero-cache/src/services/replicator/replicator.ts
packages/zero-cache/src/types/streams.ts
prod/sst/sst.config.ts

* The new `replication-manager` must be rolled out before `view-syncer`s are rolled out
* The `ZERO_LITESTREAM_BACKUP_URL` is no longer needed by `view-syncers`. 
* Specifying it is fine but it will be ignored.
* This means that initiating a resync (by updating the backup url) only requires updating the `replication-manager`. The `view-syncers` will pick this up and reset when signaled by the `replication-manager`; there is no need to update them manually.
Better backup protocol and cleanup logic
This feature was inspired by @tantaman's idea for more reliably pausing change-log cleanup when a `litestream` restore is in progress: https://github.com/rocicorp/mono/pull/4263#discussion_r2060297645
* The `replication-manager` (i.e. `change-streamer`) exports a new `/snapshot` websocket handler …

feat(zero-cache)!: improved backup protocol and change-log cleanup logic

---

packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/helpers/runner.ts

had a user report about something like this not working. Double checking.
https://github.com/AkshayPathak/zero-reproduction/blob/c024fe28a0099a10be7157646a03cf486aa4ca87/packages/zero/src/mutators.ts#L10

chore(z2s): test `.one` on primary key lookup

---

packages/zero-cache/src/services/change-streamer/storer.ts

See if this addresses the liveness failures between the change-streamer and backup-replicator process during a large catchup.
User report:
https://discord.com/channels/830183651022471199/1370057107814088796/1370196000152752178

chore(zero-cache): reduce catchup batch size

---

packages/zero-cache/src/config/zero-config.ts

Ensure that users don't accidentally run servers with the old flags, as it would unintentionally result in running a replication-manager in a view-syncer node.

chore(zero-cache): refuse to start if deprecated option is found

---

packages/zero-cache/src/db/transaction-pool.ts

Only log every 1000 executed statements. Adjust nomenclature so as not to get confused with other contexts.

chore(zero-cache): refine tx pool logging

---

packages/zero-cache/src/services/change-source/pg/change-source.ts

The `columns` field can be large for tables with many columns. They are not used downstream, so removing them from the change-stream can significantly reduce the amount of downstream I/O (i.e. change-db writes, change-streamer -> subscriber websocket)

chore(zero-cache): avoid sending the `columns` field in pg MessageRelations

---

packages/zero-cache/src/db/transaction-pool.ts

Avoid awaiting the results of previously executed transactions if we are going to fail the transaction anyway.

chore(zero-cache): fail the transaction pool fast(er)

---

packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/init.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/init.ts
packages/zero-cache/src/services/change-source/pg/schema/published.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/published.ts

User report:
https://discord.com/channels/830183651022471199/1370898291721506876/1371170647241265293
Fixes replicated indexes to respect the column ordering of the upstream index.
Tangential: Also corrects the logic that excludes `INCLUDE`d (i.e. stored but not indexed) columns. 
To fully apply this fix, a resync is required. 
A resync is thus recommended for any app with compound indexes (including primary keys).

fix(zero-cache): fix ordering of columns in replicated indexes

---

packages/analyze-query/src/bin-analyze.ts
packages/zero-cache/bench/benchmark.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-cache/src/auth/write-authorizer.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zero-client/src/client/context.ts
packages/zql-benchmarks/src/chinook-hydration.bench.ts
packages/zql/src/builder/builder.ts
packages/zql/src/builder/test-builder-delegate.ts
packages/zql/src/ivm/destroy.test.ts
packages/zql/src/ivm/exists.fetch.test.ts
packages/zql/src/ivm/exists.push.test.ts
packages/zql/src/ivm/exists.ts
packages/zql/src/ivm/fan-in.ts
packages/zql/src/ivm/fan-out-fan-in.test.ts
packages/zql/src/ivm/fan-out.ts
packages/zql/src/ivm/filter-operators.ts
packages/zql/src/ivm/filter.test.ts
packages/zql/src/ivm/filter.ts
packages/zql/src/ivm/join.fetch.test.ts
packages/zql/src/ivm/operator.ts
packages/zql/src/ivm/snitch.ts
packages/zql/src/query/test/query-delegate.ts
packages/zqlite/src/test/source-factory.ts

**Problem**
Fetching a pipeline with an OR is very inefficient if one or more branches are sparse or empty.  
This is because of how `FanIn` merges fetch `Stream`s.  It essentially uses merge-sort, asking each `Stream` for its next `Node `to determine the next `Node` in sort order.  A sparse or empty branch may process every (or nearly every) row in its source table to answer that its `Stream` is empty, even if another branch could satisfy the limit of the query processing far fewer rows.
For example lets say the condition of a query is `or(cmp('foo', 'bar'), and(cmp('fuzzy', 'wuzzy'), exists('baz')))`, where `cmp('foo', 'bar')` is always false but `and(cmp('fuzzy', 'wuzzy'), exists('baz'))` has many matches early in the sort order.  We need a complex query with exists, cause otherwise we …

perf(zql): optimization for sparce/empty OR branches

---

packages/zero-cache/src/services/change-source/pg/logical-replication/stream.ts

User report:
https://discord.com/channels/830183651022471199/1370057107814088796/1370245009219260599
Neon appears to use a `wal_sender_timeout` that is shorter than the default 60 seconds (with evidence of it being 30 seconds).
Shorten the manual keepalive timeout to account for this to see if this prevents the sender timeouts when processing large transactions.
(Also removed some unnecessary logging that turns out to be unnecessary.)

fix(zero-cache): use a shorter keepalive timeout for the PG replication stream

---

packages/zero-cache/src/db/transaction-pool.pg-test.ts
packages/zero-cache/src/db/transaction-pool.ts
packages/zero-cache/src/services/change-streamer/storer.ts

Refactors the TransactionPool to allow callers to optionally block on write tasks.
This will be used in an upcoming change that allows the ChangeDB to exert back-pressure in the face of a large replication stream backlog. (Revealed by stress tests while investigating https://discord.com/channels/830183651022471199/1370057107814088796/1370245009219260599).
A related optimization in this change is to only await the result of the last statement, rather than holding all of the statements in memory. This allows most completed statements to be garbage collected; only the result of the last statement need be awaited to satisfy transactional semantics.

chore(zero-cache): allow Transaction pool users to block on write tasks

---

packages/zero-cache/src/services/change-streamer/change-streamer-service.ts
packages/zero-cache/src/services/change-streamer/storer.ts

Respond to back pressure from the change db for very large transactions by awaiting (the execution of) every 10,000th statement. This builds off of the new Promise API for Transaction Pool writes in https://github.com/rocicorp/mono/pull/4367.
This was verified in a stress test that performs a 2M row update. Previously this would result in crashing the replication-manager with an OOM, and now it successfully process the transaction as quickly as the change-db is able to store the changes.
User report:
https://discord.com/channels/830183651022471199/1370057107814088796/1370245009219260599

fix(zero-cache): add flow control for large change DB transactions

---

package-lock.json
packages/zql-benchmarks/package.json
packages/zql-integration-tests/src/helpers/runner.ts

problems with tinybench:
- setup/teardown methods do not work
- params to tune warmup and test iterations do not work
mitata seems more robust and it gives us insights into GC and CPU cycles.
Notes to self:
- We should change the benchmarks to allow comparing different queries rather than comparing zql vs zqlite vs pg perf.
- We should bump counters for fetch calls and print those too
- We should warn if a fetch does not use an index in zqlite

chore(zql): migrate benchmarks to mitata

---

packages/zero-client/src/client/options.ts

- Clarified why Zero client keeps retrying tokens that don't change
- Explicitly mention `sub` claim in JWT for `userID` field
- Explicitly mention JWT

docs: improve client auth JSDoc

---

packages/shared/src/iterables.ts
packages/zql-benchmarks/src/frontend-analysis.pg-test.ts
packages/zql/src/ivm/memory-source.ts

**60x faster** (of course this depends on the size of the collection. ~3,500 rows in this case)
Before:
After:

fix(zql): return after first row for point queries (60x speedup)

---

packages/zero-cache/src/services/view-syncer/cvr-store.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/schema/types.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

We'll support both custom queries and legacy queries for some time. This means the query structure has three types:
1. internal
2. client
3. custom
change from 
```ts
internal: boolean
``` 
to
```ts
type: 'internal' | 'client' | /*coming soon: */'custom'
```

chore(custom-queries): change from `internal: boolean` to `type:`

---

packages/zero/Dockerfile

Bump to new litestream version with the fix for large uploads:
https://github.com/rocicorp/litestream/pull/6
User report:
https://discord.com/channels/830183651022471199/1334697671021035590/1373130883489464342

fix(zero-cache): bump to new litestream with upload fix

---

packages/zero-cache/src/types/pg.ts

Instead of trying to cover every query-string option related to SSL, this just unblocks my use case, [Neon Local](https://neon.tech/docs/local/neon-local).

Add support for `sslmode=no-verify`

---

packages/zero-cache/src/services/change-source/pg/copy-runner.pg-test.ts
packages/zero-cache/src/services/change-source/pg/copy-runner.ts

CopyRunner is a special-case "drop-in" replacement for TransactionPool specifically intended for running a single `COPY` command and either reusing or discarding the connection based on whether it is healthy after the copy.
This works around a bug in Postgres in which certain types / sequences of `COPY` commands cause it to be unresponsive on the connection after it completes.
The unit test recreates the Postgres hang issue on the TransactionPool, and verifies that the CopyRunner successfully processes the same logic.

chore(zero-cache): CopyRunner substitute for TransactionPool

---

packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/chinook/schema.ts
packages/zql/src/ivm/memory-source.ts
packages/zql/src/query/query-impl.query.test.ts

Primary key filters in `related` calls would fail and return no results.
```ts
z.issue.related(
'comments',
q => q.where('id', id)
);
```
`req.constraint` in memory source should have been replaced everywhere by the primary key constraint if/when it existed. This moves the primary key constraint definition up to the top of the function and replaces all references to `req.constraint`
---
- https://discord.com/channels/830183651022471199/1374349312888147968/1374349316902359132
- https://discord.com/channels/830183651022471199/1334350942304206919/1374073823934156861
---
These query forms pass in `chinook.pg-test.ts`. Figuring that out separately.

fix(zql): pk lookup on `related`: `related(x, q => q.where('id', y))`

---

packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/helpers/runner.ts
packages/zql/src/ivm/memory-source.ts
packages/zql/src/query/query-impl.query.test.ts

The primary key constraint that we build from the connection's filters should not take the place of `req.constraint` everywhere.
The reason is that the primary key constraint must be ANDED with the fetch constraint. 
Example:
An album node could `fetch(constrating: artistID = 2)`. The connection may have a primary key filter on it `artistID = 1` but it would be wrong to return that artist since it was not `artistID = 2`.
---
I was able to get the chinook test to fail with this query pattern which uncovered the push bug since `chinook.pg-test.ts` tests add, remove and edit pushes.

fix(zql): pk constraint is a filter, not the constraint

---

packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.ts
packages/zero-cache/src/services/http-service.ts

Revert the behavior of announcing health at `/` early.
This was previously needed to allow the `replication-manager` to have an arbitrarily long startup time even if not monitored by an elastic load balancer.
The AWS docs for [`healthCheckGracePeriodSeconds`](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_parameters.html#sd-networkconfiguration) have since been updated to indicate that it works for container health checks as well as ELB health checks.
> **healthCheckGracePeriodSeconds**
>
> The period of time, in seconds, that the Amazon ECS service scheduler ignores unhealthy Elastic Load Balancing, VPC Lattice, and container health checks after a task has first started. If you do not specify a health check grace period value, the default value of 0 is …

chore(zero-cache): revert split-health check behavior

---

prod/sst/sst.config.ts

Run gigabugs-ebs with 16 vCPU and 15000 IOPS on the ebs volume, the maximum performance achievable on Fargate as per https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ebs-fargate-performance-limits.html

chore(prod): run gigabugs-ebs with max IOPS

---

prod/sst/sst.config.ts

At 20 gb and 15000 IOPS, AWS fails with:
```
Encountered 'InvalidParameterValue' error from AmazonEC2: "Iops to volume size ratio of 750.000000 is too high; maximum is 500"
```
Bumping to 30 gb to achieve the maximum allowed ratio of 500.

chore(prod): fix ebs volume

---

packages/z2s/src/compiler.ts
packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/helpers/runner.ts

junction edges were referring to the wrong ast to pull `where` conditions from in the compiled sql.
Next up:
- disable `limit` over junction edges in ZQL
- disable `orderBy` over junction edges in ZQL
Both of those things are not yet supported by ZQL.

fix(z2s): apply where to junction edges

---

packages/zql-integration-tests/src/chinook/chinook-fuzz-hydration.pg-test.ts
packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/helpers/data-gen.ts
packages/zql-integration-tests/src/helpers/runner.ts
packages/zql/src/query/test/query-gen.ts

Running
```
npm run test -- chinook-fuzz --project=zql-integration-tests/pg-17 --silent=false
```
Will use the query generator to generate 30 random queries and run them all through zql, zqlite, z2s and compare their output against one another.
Failures will print the seed that caused the failure (`mismatch. repro seed: xxxx`). You can then run with a specific seed which will print the query that was used and the data that was fetched.
Running with seed `733566003` shows this query fails:
```ts
employee
.where(({exists, not}) =>
not(
exists('reportsTo', q =>
q
.where(({exists, not}) =>
not(
exists('reportsTo', q =>
q
.orderBy('birthDate', 'desc')
.orderBy('postalCode', 'desc')
.orderBy('firstName', 'asc')
.orderBy('id', 'asc')
.limit(81),
),
),
)
.orderBy('country', 'desc') …
```

chore(zql): fuzz zql hydration

---

packages/zql-integration-tests/src/chinook/check-zql-string.pg-test.ts
packages/zql-integration-tests/src/chinook/chinook-fuzz-hydration.pg-test.ts
packages/zql-integration-tests/src/helpers/static.ts

Fuzz testing creates failing queries but debugging those failing queries can be hard.
Allow testing an arbitrary query string so we can iterate on debugging a failing query.
Usage:
1. replace `QUERY_STRING` with the failing query. E.g., `QUERY_STRING = 'customer.related("invoice")'`
2. `npm run test -- check-zql-string --project=zql-integration-tests/pg-17`

chore(zql): test an arbitrary query string

---

packages/z2s/src/compiler.output.test.ts
packages/z2s/src/compiler.ts
packages/zql-integration-tests/src/chinook/check-zql-string.pg-test.ts

SQLite and ZQL considers null to be smaller than all values. Postgres considers null to be larger than all values.
Modify postgres order-by to match sqlite.
Found by the fuzzer.

fix(z2s): NULLS FIRST vs NULLS LAST

---

packages/zero-schema/src/builder/schema-builder.ts
packages/zql-integration-tests/src/chinook/check-zql-string.pg-test.ts
packages/zql-integration-tests/src/chinook/chinook-fuzz-hydration.pg-test.ts
packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/chinook/schema.ts

If a relationship name matches a column name and we try to sort by that column, we end up trying to sort on the relationship iterable.
E.g.,
```ts
employee.related('reportsTo').orderBy('reportsTo', 'asc');
```
would fail
Found by the fuzzer.

fix(zql)!: throw if a relationship name matches a column name

---

packages/z2s/src/compiler.output.test.ts
packages/z2s/src/compiler.ts
packages/zql-integration-tests/src/chinook/check-zql-string.pg-test.ts

the compiler defaulted `singular` to `limit(1)` but `limit(0)` should take precedence here.
Found by the fuzzer.

fix(z2s): handle `limit(0)` against `singular` relationships

---

packages/zql-integration-tests/src/chinook/check-zql-string.pg-test.ts
packages/zql/src/builder/builder.ts

```ts
foo.whereExists('x', q => q.limit(0))
```
should always evaluate to false.
```ts
foo.whereNotExists('x', q => q.limit(0))
```
should always evaluate to true.
Found by the fuzzer.

fix(zql): handle `whereExists('x', q => q.limit(0))`

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/services/litestream/commands.ts
packages/zero-cache/src/services/litestream/config.yml
packages/zero/Dockerfile

Apply the `--multipart-concurrency` and `--multipart-size` options to litestream uploads as well as downloads, making the memory usage (and ideally, speed gains) symmetric for restores and backups.
This leverages a new feature in our litestream fork: https://github.com/rocicorp/litestream/pull/7

chore(zero-cache): use multipart config for litestream uploads

---

packages/zero-cache/src/server/logging.ts

Also remove vestigial `tenantID` stuff.

chore(zero-cache): narrow input type of createLogContext()

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/view-syncer/client-handler.test.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-client/src/client/query-manager.test.ts
packages/zero-client/src/client/query-manager.ts
packages/zero-client/src/client/test-utils.ts
packages/zero-client/src/client/zero-poke-handler.test.ts
packages/zero-client/src/client/zero-poke-handler.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/change-desired-queries.ts
packages/zero-protocol/src/connect.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts
packages/zero-protocol/src/queries-patch.ts

1. It is extra information that does not need to be sent
2. Custom queries will not send their AST to the client
**edit** -- double check this is safe given we do push some queries back up on reconnect which could have had their AST fields nuked via poke.

chore(zero): remove `ast` from downstream query patch messages [cust-queries]

---

packages/zero-cache/src/server/otel-start.ts
packages/zero/src/zero-cache-dev.ts

using `npx` to start a script is not portable between package managers.
https://bugs.rocicorp.dev/issue/3888

feat(zero-cache): move auto-instrumentations to NODE_OPTIONS

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/schema/types.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

Before we had:
- internalQueryRecordSchema
- clientQueryRecordSchema
this adds
- customQueryRecordSchema
The difference between `client` and `custom` is that `custom` has `name` and `args` whereas `client` has an `ast`.

chore(zero-cache): add a type for custom query records

---

packages/analyze-query/src/bin-analyze.ts
packages/analyze-query/src/bin-transform.ts
packages/zero-cache/src/auth/read-authorizer.ts
packages/zero-cache/src/custom-queries/transform-query.test.ts
packages/zero-cache/src/custom-queries/transform-query.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

We use the name `ast` instead of `query` in the view syncer. Also be clear about which hash this is as future versions of the code will include the original hash in the response as well.

chore(zero-cache): rename TransformedAndHashed fields

---

packages/zql/src/query/named.test.ts
packages/zql/src/query/named.ts

```ts
const q = query.bindTo(schema);
q('issue', (tx, id: string) => tx.issue.where('id', id));
// or
query(schema, 'issue', (tx, id: string) => tx.issue.where('id', id));
```
The API is expected to evolve as I start using it in zbugs and other places.

chore(zql): named/custom query wrapper

---

packages/analyze-query/src/bin-analyze.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zqlite/src/runtime-debug.ts
packages/zqlite/src/table-source.ts

Default to false.
These are useful for understanding if a query is returning the expected results, and how the query is working.  
Output looks like
```
greg zero [grgbkr/analayze-debug]$ node out/analyze-query/src/bin-analyze.js --replica-file /tmp/zbugs-sync-replica.db   --schema-path='../../apps/zbugs/shared/schema.ts' --query='issue.related("comments").limit(5)' --apply-permissions --auth-data='{"userId":"user-123"}' --output-vended-rows --output-synced-rows
[MISSING_ENV_FILE] missing .env file (/Users/greg/github/mono/packages/zero/.env)
[MISSING_ENV_FILE] https://github.com/dotenvx/dotenvx/issues/484
[dotenvx@1.39.0] injecting env (0)
=== Query After Permissions: ===
issue
.where(({ and, cmp, or }) =>
or(
and(cmp(null, "IS NOT", null), cmp(null, "crew")),
cmp("visibility", …
```

feat(analyze-query): add --output-vended-rows and --output-synced-rows options

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts

Use existing flag log-slow-hydrate-threshold as the threshold for query-hydration-stats rather than hardcoded 200ms.

feat(zero-cache): make threshold for query-hydration-stats configurable

---

packages/analyze-query/src/bin-analyze.ts
packages/zero-cache/bench/benchmark.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-client/src/client/context.test.ts
packages/zero-client/src/client/context.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/zero.ts
packages/zero-pg/src/query.ts
packages/zql/src/query/named.test.ts
packages/zql/src/query/named.ts
packages/zql/src/query/query-impl.query-kitchen-sink.test.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.ts
packages/zql/src/query/static-query.ts
packages/zql/src/query/test/query-delegate.ts
packages/zqlite/src/query-delegate.ts
packages/zqlite/src/test/source-factory.ts

A custom query will have `name` and `args` filled in in addition to the AST.
- the AST is used for client execution
- name and args are sent to the server
The first commit in this PR is only kept around for historical interest / documentation of another approach.

chore(zql): add query name and args to builder interface

---

packages/zql/src/query/named.test.ts
packages/zql/src/query/named.ts

The return type of a custom query needs to be threaded back through so callers know what data they're receiving.

chore(zql): stronger return type on custom queries

---

packages/zql-integration-tests/src/chinook/check-zql-string.pg-test.ts
packages/zql-integration-tests/src/chinook/chinook-fuzz-hydration.pg-test.ts
packages/zql-integration-tests/src/helpers/static.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/static-query.ts
packages/zql/src/query/test/util.ts

This will allow building queries without first having access to a Zero instance.
E.g., a user can define queries by only referencing their schema and then run those queries later by binding them to a delegate on the client or server.
```ts
const q = schema.query;
const issues = q.issue;
const issueOne = q.issue.where('id', 1);
// inside the useQuery hook we would call `asRunnable`
issueOne.asRunnable(z).materialize();
```

chore(zql): allow static queries to be converted to runnable queries

---

apps/zbugs/shared/schema.ts
apps/zbugs/src/components/filter.tsx
apps/zbugs/src/components/label-picker.tsx
apps/zbugs/src/components/nav.tsx
apps/zbugs/src/components/user-picker.tsx
apps/zbugs/src/hooks/use-can-edit.ts
apps/zbugs/src/hooks/use-user-pref.ts
apps/zbugs/src/pages/issue/issue-page.tsx
apps/zbugs/src/pages/list/list-page.tsx
apps/zbugs/src/zero-setup.ts
packages/zero-client/src/client/zero.ts
packages/zero-client/src/mod.ts
packages/zero-react/src/use-query.test.ts
packages/zero-react/src/use-query.tsx
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.ts

trying this on for size before converting zbugs to custom queries.
Feels nice.
- less generics (<Schema, Mutators> being passed around
- slightly less to type (queries.issue vs z.query.issue)
- no `const z = useZero();` just to then `z.query.issue`

feat(zbugs): no need to call `useZero` to build queries in React

---

packages/zero-client/src/client/alive-clients-manager.test.ts
packages/zero-client/src/client/alive-clients-manager.ts

A class that lists the alive clients in a client group. It uses the `navigator.locks` API to manage locks for each client. The class is designed to be used in a browser environment where the `navigator.locks` API is available.
When navigator.locks is not available (node.js, deno, bun), it will return a set only containing the current clientID.
It uses one lock per client, identified by a combination of `clientGroupID` and `clientID`. Then the `query` method is used to get the list of all clients that hold or are waiting for locks in the same client group.

chore(zero-client): add alive clients manager

---

packages/zero-client/src/client/active-clients-manager.test.ts
packages/zero-client/src/client/active-clients-manager.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/connect.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

This sends the active clients on connect.
The active clients will later be used to determine what desired queries can be inactivated

chore(zer-client): Send active clients on connect

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/custom-queries/transform-query.test.ts
packages/zero-cache/src/custom-queries/transform-query.ts
packages/zero-cache/src/custom/fetch.ts
packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-cache/src/workers/connect-params.ts
packages/zero-cache/src/workers/syncer-ws-message-handler.ts
packages/zero-cache/src/workers/syncer.test.ts

Allows users to forward cookies sent from the browser to zero-cache along to their API server when calling push/pull.
This is configurable and disabled by default since it has security implications.

feat(zero-cache): forward cookies from request to API server (disabled by default)

---

vitest.config.ts

Looks like tests with `.pg-VV` were not getting picked up unless the package was listed as "special"

chore(zero): get zql-integration-tests running in ci

---

packages/zql-integration-tests/src/chinook/chinook-fuzz-hydration.pg-test.ts

Too many timeouts. This isn't great for running in CI. We'll need to come up with another plan.
Options:
a. limit the complexity of queries created in CI
b. disable in CI and run on a dedicated machine outside of CI
c. kick timeouts up to 30 seconds?

chore(zql): disable fuzzer for now..

---

packages/zql/src/mutate/custom.ts

Mutators only ever query within a transaction. This simplifies the interface for our users slightly.

feat(mutators): db connection does not need to be queryable

---

packages/zero-client/src/client/alive-clients-manager.test.ts
packages/zero-client/src/client/alive-clients-manager.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/connect.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

Reverts rocicorp/mono#4510
No need to have this incomplete feature in the release

Revert "chore(zer-client): Send active clients on connect"

---

packages/zero-pg/src/push-processor.pg-test.ts
packages/zero-pg/src/push-processor.ts

If we catch an error in error mode (that is not OoO or MutationAlreadyProcessed) we should re-throw and stop processing mutations.
The previous code was also technically correct but would run mutations that could not possibly pass. The reason is that if we fail in error mode (with something other than MutationAlreadyProcessed) then all subsequent mutations will fail with OutOfOrderMutation or with the same (db down, bad password, whatever) error the current mutation failed with.
Might as well bail early rather than trying the remaining mutations.

chore(mutators): re-throw unknown errors that were caught in error mode

---

packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/connect.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

This is a revert of the revert:
Revert "Revert "chore(zer-client): Send active clients on connect (#4510)" (#4522)"
This reverts commit 789b8dcad91ba5ac6e930b838c53a8d432b56cea.
The ActiveClientsManager changed to an async class, so we need the construction changed slightly.

chore(zero): Add activeClients to initConnection

---

packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

19 was reverted and bumping to 20 to fix build issues

chore(zero-protocol): bump protocol version to 20

---

packages/zero-schema/src/builder/schema-builder.test.ts
packages/zero-schema/src/builder/table-builder.ts

Correctly handle an explicit `public` schema by dropping it, to be in line with how the tables are named on the replica.
User report:
* https://discord.com/channels/830183651022471199/1288232858795769917/1386082154613575793

fix(zero-schema): handle explicit `from("public.table")` schema inputs

---

packages/zqlite/src/runtime-debug.ts
packages/zqlite/src/table-source.ts

It was zeroing everytime a particular query template was fetched, which we don't want, since we want cumulative rows for that particular query across multiple fetches.

chore(analyze-query): fix broken zeroing of query counts.

---

packages/zero-cache/src/services/view-syncer/cvr-store.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-client/src/client/inspector/inspector.test.ts
packages/zero-client/src/client/inspector/inspector.ts
packages/zero-client/src/client/inspector/types.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/inspect-down.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

When we added custom queries we changed the type of the ast column to nullable but the inspector code was not updated to handle that. This commit updates the inspector code to handle the nullable ast column as well as the name and args columns that were added when custom queries were added.

fix(zero): Inspector queries were broken

---

packages/shared/src/logarithmic-histogram.test.ts
packages/shared/src/logarithmic-histogram.ts

This is extracted from #4493 since it is not generally clear if we will use these as used in that PR.
Adding these to shared in case we need them in the future.

chore(shared): Add logarithmic histogram implementation

---

prod/sst/sst.config.ts

This reverts #4389 in preparation for reverting automatic replication-manager discovery (#4335)

chore(prod): bring back the internal load balancer

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/replicator.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.ts
packages/zero-cache/src/services/litestream/commands.ts
prod/sst/sst.config.ts

Restore the `ZERO_CHANGE_STREAMER_URI` option and recommend it as the standard routing mechanism from the `view-syncer` to `replication-manager`.
Auto-discovery via `ZERO_CHANGE_STREAMER_MODE` is still supported but no longer the recommended configuration. An explicit routing component, while requiring additional setup on the developer's part, works for a wider range of production environments.
User report:
* https://discord.com/channels/830183651022471199/1389157062881050686/1389253989404512326

feat(zero-cache): restore the ZERO_CHANGE_STREAMER_URI option

---

packages/zero-client/src/client/worker-test.ts

https://github.com/rocicorp/mono/pull/4576 updated to editing nodes in place in the view. See why that is safe in that pr.

chore(tests): fix `worker-test.ts`

---

packages/replicache/src/worker.test.ts
packages/zero-client/src/client/worker.test.ts

To correctly have Vite bundle the worker files, the `new URL` call must be inside the `new Worker` constructor. This change ensures that the worker test files are correctly loaded in both the Replicache and Zero Client packages.
https://github.com/rocicorp/mono/pull/4587

chore(replicache, zero-client): fix worker test URL handling

---

packages/analyze-query/src/bin-analyze.ts
packages/analyze-query/src/bin-transform.ts
packages/ast-to-zql/src/bin.ts
packages/shared/src/options.test.ts
packages/shared/src/options.ts
packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/scripts/deploy-permissions.ts
packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/server/mutator.ts
packages/zero-cache/src/server/replicator.ts
packages/zero-cache/src/server/runner/run-worker.ts
packages/zero-cache/src/server/syncer.ts
packages/zero/src/zero-cache-dev.ts
tools/client-simulator/src/main.ts
tools/load-generator/src/main.ts

Adds a `deprecated` field to Options definitions that emits a warning when the value is present:
Also (finally) changed the `parseOptions()` function to take an options object instead of a list of params.

chore(zero-cache): emit deprecation warnings for deprecated options

---

apps/zbugs/shared/queries.ts
apps/zbugs/src/pages/issue/issue-page.tsx
packages/zero-protocol/src/connect.test.ts
packages/zero-protocol/src/connect.ts

Fixes https://bugs.rocicorp.dev/issue/4008
We encode queries registered early in startup in the sec protocols and they have to be URL-encoded. To save space we also base64 encode, but btoa doesn't support non-latin chars.
Queries can contain any arbitrary string so that means we need to encode these non-latin chars. So add another layer of encoding!

fix(zero-client): Queries containing non-latin queries break startup.

---

apps/zbugs/server/get-query.ts
apps/zbugs/server/server-queries.ts
apps/zbugs/shared/queries.ts
apps/zbugs/src/components/filter.tsx
apps/zbugs/src/components/label-picker.tsx
apps/zbugs/src/components/nav.tsx
apps/zbugs/src/components/user-picker.tsx
apps/zbugs/src/hooks/use-can-edit.ts
apps/zbugs/src/hooks/use-user-pref.ts
apps/zbugs/src/pages/issue/issue-page.tsx
apps/zbugs/src/pages/list/list-page.tsx
apps/zbugs/src/zero-preload.ts
packages/zql/src/query/named.test.ts
packages/zql/src/query/named.ts

To reduce repetition of a query's name.
Before:
```ts
export const foo = named('foo', () => ...)
```
after:
```ts
export queries = named({
foo: () => ...
});
```

chore(zero): update `named` to take an object

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/custom-queries/transform-query.test.ts
packages/zero-cache/src/custom-queries/transform-query.ts
packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/workers/syncer.test.ts

To support previews we'll need to support an array of possible mutate/query urls.
For this iteration, we just pick the first URL.
The client can send a URL to use. If that URL matches one in the list, it is used. If it does not match, an error is thrown.
For the final iteration, the URL can have a star in the subdomain position. E.g., `https://*.example.com` and the client can insert a subdomain.
After doing some testing, it looks like the existing `.env` format will correctly parse into a string array.
e.g.,
```
ZERO_PUSH_URL = 'http://example.com'
```
get parsed to:
```ts
{ url: ['http://example.com'] }
```
Given that, this is not a breaking change for our users.

chore(zero): allow an array of urls for query/mutate

---

packages/zero-cache/src/custom-queries/transform-query.test.ts
packages/zero-cache/src/custom-queries/transform-query.ts
packages/zero-cache/src/custom/fetch.test.ts
packages/zero-cache/src/custom/fetch.ts
packages/zero-cache/src/services/mutagen/pusher.ts

To support previews we need to check a dynamic URL provided by the client against a static URL whitelist provided by the zero config.
Rules:
1. Query parameters are ignored
2. Strings that exactly match (after removing query params) are allowed
3. A wildcard may be present in the static set. Each wildcard matches a single subdomain. A wildcard must be followed by a `.`
Valid wildcard patterns:
- "https://\*.example.com" matches "https://api.example.com" and "https://www.example.com"
- "https://\*.example.com" does not match "https://example.com" (no subdomain)
- "https://\*.example.com" does not match "https://api.example.com/path" (no trailing path)
- "https://\*.\*.example.com" matches "https://api.v1.example.com" and "https://www.v2.example.com"
- "https://\*.\*.example.com" does not …

chore(zero): check URL against whitelist in `fetchFromAPIServer`

---

packages/zero-cache/src/config/normalize.ts
packages/zero-cache/src/server/main.ts

This allows subprocesses know now many sync workers are running (for analytics logic).

chore(zero-cache): pass the computed `numSyncWorkers` to subprocesses

---

packages/zero-cache/src/services/view-syncer/cvr-store.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

Fix the `inspectQueries` method to properly use the provided `ttlClock` parameter instead of `now()` for determining query expiration. This ensures consistent expiration logic throughout the system.

chore(zero): Fix inspectQueries TTL clock handling

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/view-syncer-ttl.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

This initialized the TTL clock to start at 0 instead of Date.now().
We still increment it the same way as before.

chore(zero-cache): Make the TTL clock zero based

---

packages/zero-cache/src/services/change-streamer/change-streamer-http.pg-test.ts
packages/zero-cache/src/services/change-streamer/change-streamer-http.ts

Have the change-streamer (i.e. replication-manager) verify that the protocol version in the snapshot reservation url is within the support range of change-streamer protocol versions.
This allows the snapshot request to verify that the replication-manager will support the subsequent change stream request from the view-syncer, and be used in a subsequent PR to coordinate rollouts of replication-managers and view-syncers when the protocol changes.

chore(zero-cache): check the protocol version on snapshot reservation requests

---

packages/zero-cache/src/services/view-syncer/view-syncer-ttl.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

The main issue was that we were using `#getTTLClock` in `handleConfigUpdate` before we had initialized `#ttlClock`. By always reading the ttlClock from the CVR we can simplify the logic and avoid the assertion failure.

chore(zero-cache): Fix assertion related to TTL clock

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/init.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/init.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.ts
packages/zero-cache/src/services/view-syncer/client-handler.test.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/view-syncer-test-util.ts

- adds a table to track mutation responses to upstream
- adds an internal query to sync that table to zero-cache
- currently ignores those rows in client-handler

chore(zero-cache): server side scaffolding for mutation responses [1/n]

---

packages/zero-cache/src/services/view-syncer/client-handler.test.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/mutation-tracker.ts
packages/zero-client/src/client/zero-poke-handler.test.ts
packages/zero-client/src/client/zero-poke-handler.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/mutations-patch.ts
packages/zero-protocol/src/poke.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts
packages/zero-protocol/src/push.ts

Add to the `poke` protocol so updates to the `mutations` table can be poked down to the client.
On poke end, the client uses the merged poke result to resolve mutation promises. This happens after Replicache has been updated so a user can issue a read after their promise resolves and get the latest state.

chore(zero): wire client and server together for mutation results  [2/n]

---

packages/otel/src/enabled.ts
packages/zero-cache/src/server/logging.ts
packages/zero-cache/src/server/otel-start.ts

Modify the `otel-start` logic to support exporting subsets of otel traces, metrics, and logs by understanding the `OTEL_EXPORTER_OTLP_{METRICS,LOGS,TRACES}_ENDPOINT` environment variables.
Also fix the `server.version` attribute to reference the zero-version, rather than the instrumentation scope version (that's appropriate for annotating traces).

chore(zero-cache): support exporting subsets of otel exports

---

packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-cache/src/services/view-syncer/cvr.test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

There are two paths the check if queries are expired:
1. `hasExpiredQueries` in view-syncer.ts
2. `getInactiveQueries` in cvr.ts
(1) only returns queries that are expired for all clients. (2) was returning queries if they were expired for 1 or more clients.
On reading, it appears that both paths should caluclate expiration the same way. The second path should not return a query as inactive if one of its client has not inactivated it.
It looks like this was addressed before here: https://github.com/rocicorp/mono/pull/3843 but it did not take into account the `undefined` case. Or I'm missing something.
before (re-schedules eviction every 50ms because it thinks a query is expired but it is not):
https://github.com/user-attachments/assets/42459a6a-2716-4a94-b843-53aa37475206
after (stable): …

fix(ttl): fix incorrect calculation of expired queries

---

packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts

This allows for smoother backwards compatible changes.  A new server version can introduce a new field to messages, that new clients will use and old clients can safely ignore.

chore(zero-client): parse messages with valita 'passthrough'

---

packages/zero-cache/src/server/logging.ts
packages/zero-cache/src/server/otel-start.ts
packages/zero-cache/src/server/syncer.ts

Surface diagnostic messages from the otel client to the debug logs, which include otel usage warnings and export errors. The messages otherwise go into the ether.

chore(zero-cache): surface diagnostic otel messages to debug logs

---

packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-cache/src/services/view-syncer/client-handler.test.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-client/src/client/keys.test.ts
packages/zero-client/src/client/keys.ts
packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/mutation-tracker.ts
packages/zero-client/src/client/query-manager.test.ts
packages/zero-client/src/client/zero-poke-handler.test.ts
packages/zero-client/src/client/zero-poke-handler.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/mutations-patch.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

We need to persist mutator responses since:
1. Two clients can connect
2. Client A disconnects
3. Client B syncs Client A's mutations
4. Server pokes down results
5. Client B syncs to IBD
6. Client A refreshes from IDB
7. Client A comes online
8. Client A will not receive pokes for its mutations since they were already synced for the client group
Client A can only get its response if the mutation results are persisted to replicache.

chore(zero): persist mutator responses into replicache

---

packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

The `zero_0.mutations` table is written by the API server in the mutator's transaction, with the exception of cleanup. Cleanup of mutations that the client has acknowledged receiving is done by zero-cache.
This is a problem since if the upstream is custom we cannot delete mutation results from it.
This PR is a temporary workaround to not break users with custom upstreams.
Alternatives:
1. Send a message to the API server when a mutation is acked, client is deleted or client group is deleted. 
2. Add more to the custom upstream interface and poke that. 
3. Have the API server clean the table on some interval given zero is not expected to run for prolonged periods offline.

chore(mutators): workaround for custom upstream

---

packages/zero/package.json
packages/zero/src/adapters/drizzle-pg.ts
packages/zero/src/adapters/postgresjs.ts
packages/zero/tsconfig.server.json

drizzle adapter was not being built into the final zero package.

chore(zero): fix exports of adapters

---

packages/zero-cache/src/services/change-source/custom/change-source.test.ts
packages/zero-cache/src/services/change-source/custom/change-source.ts

Updates the custom change-source test to document / reflect the new tables expected of custom upstreams, starting from: https://github.com/rocicorp/mono/pull/4650
Context: https://discord.com/channels/830183651022471199/1399802770223005857/1399805526748954694
@cbnsndwch 
@DAlperin

chore(zero-cache): update custom change source test with new required tables

---

packages/zero-cache/src/services/change-source/pg/initial-sync.ts

The COPY hang bug that is fixed in Node v22+ for Linux/MacOS is still present in the latest version of Node on Windows.
User report: https://discord.com/channels/830183651022471199/1400629013105475634/1401009565931147267
Work around this for `win32` only, by running running enough copy workers (i.e. connections) for each table to have its own connection, and avoiding waiting for connections to close.

fix(zero-cache): workaround the COPY hang bug in Windows

---

packages/zero-cache/src/server/otel-start.ts
packages/zero/Dockerfile
packages/zero/src/zero-cache-dev.ts

The [fix to surface otel diagnostic messages](https://github.com/rocicorp/mono/pull/4670) to the Logger revealed existing errors of the form:
```
Error: @opentelemetry/api: Attempted duplicate registration of API: {trace,context,propagation}
```
This is due to the duplicate registration of the otel libraries:
* first by`--require=@opentelemetry/auto-instrumentations-node/register`
* then explicitly in [`otel-start.ts`](https://github.com/rocicorp/mono/blob/a1a46d6c0b793ad21978cf3360d2dcea9a418bc1/packages/zero-cache/src/server/otel-start.ts#L71) 
Remove the former and rely on the latter, which affords additional options such as setting the `service.version` attribute.

chore(zero-cache): fix otel duplicate registration errors

---

apps/zbugs/server/server-mutators.ts
apps/zbugs/shared/mutators.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/options.ts
packages/zero-client/src/client/test-utils.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-react/src/components/inspector.tsx
packages/zero-react/src/components/zero-inspector.tsx
packages/zero-react/src/zero-provider.tsx
packages/zero-solid/src/use-zero.ts

resurrects https://github.com/rocicorp/mono/pull/4449 to solve type depth issues.
users must now explicitly type their `Transaction` argument in their mutator definitions.

feat(zero): drop `schema` from `tx` type

---

packages/analyze-query/src/bin-analyze.ts
packages/shared/src/centroid.ts
packages/shared/src/tdigest.ts
packages/zero-cache/bench/benchmark.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-client/src/client/context.test.ts
packages/zero-client/src/client/context.ts
packages/zero-client/src/client/custom.bench.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/inspector/inspector.test.ts
packages/zero-client/src/client/inspector/inspector.ts
packages/zero-client/src/client/inspector/types.ts
packages/zero-client/src/client/mutation-tracker.test.ts
packages/zero-client/src/client/query-manager.test.ts
packages/zero-client/src/client/query-manager.ts
packages/zero-client/src/client/query-materialization-metrics.test.ts
packages/zero-client/src/client/test-utils.ts
packages/zero-client/src/client/zero.ts
packages/zql/src/query/metrics-delegate.ts
packages/zql/src/query/query-delegate.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/test/query-delegate.ts
packages/zqlite/src/query-delegate.ts
packages/zqlite/src/test/source-factory.ts

This PR introduces metrics collection to track query materialization performance in Zero, accessible through the Zero Inspector.
- Automatically tracks query materialization time with zero performance overhead
- Collects client-side and end-to-end performance metrics using T-Digest for percentile calculations
- Adds `metrics` property to Inspector and Query objects for performance analysis
```typescript
const inspector = await zero.inspect();
const clientMetrics = inspector.metrics['query-materialization-client'];
console.log(`Total queries: ${clientMetrics.count()}`);
console.log(`P50 latency: ${clientMetrics.quantile(0.5)}ms`);
console.log(`P90 latency: ${clientMetrics.quantile(0.9)}ms`);
```
```typescript
const queries = await inspector.client.queries();
const slowQueries = …
```

feat(zero-client): Expose client materialize time in inspector

---

packages/analyze-query/src/bin-analyze.ts
packages/zero-cache/bench/benchmark.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-cache/src/auth/write-authorizer.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zero-client/src/client/context.ts
packages/zero-client/src/client/inspector/inspector.test.ts
packages/zero-client/src/client/inspector/inspector.ts
packages/zero-client/src/client/inspector/types.ts
packages/zero-client/src/client/measure-push-operator.test.ts
packages/zero-client/src/client/measure-push-operator.ts
packages/zero-client/src/client/query-manager.ts
packages/zql/src/builder/builder.test.ts
packages/zql/src/builder/builder.ts
packages/zql/src/builder/test-builder-delegate.ts
packages/zql/src/ivm/operator.ts
packages/zql/src/ivm/test/push-tests.ts
packages/zql/src/query/metrics-delegate.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/test/query-delegate.ts
packages/zqlite/src/query-delegate.ts
packages/zqlite/src/test/source-factory.ts

This PR adds metrics tracking for query update performance on the client side by measuring how long individual query updates take to propagate through the IVM pipeline.
We could measure query materialization time but lacked visibility into query update performance, making it difficult to identify bottlenecks in the update pipeline.
- **New `MeasurePushOperator`**: Wraps push operations to measure execution time and record `query-update-client` metrics
- **Enhanced `QueryDelegate`**: Added `decorateSourceInput` method to enable measurement decoration
- **Updated `buildPipeline`**: Now requires `queryID` parameter for proper query identification
Metrics are exposed through existing inspector infrastructure via `getMetrics()` and `getQueryMetrics(queryID)`.

chore(zero): Add metrics for client side update to query

---

packages/zero-protocol/src/connect.test.ts
packages/zero-protocol/src/connect.ts

We were using `String.fromCharCode(...s)` which throws on large strings.
However, it is very unlikely that Zero will work correctly if the auth token is this large (64k or something like that) since Web Socket Sec Protocol header is usually limited to 8/16KB.

fix(zero-client): Large connection headers should not throw

---

packages/zero-cache/src/server/inspect-metrics-delegate.ts
packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.test.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts
packages/zero-cache/src/services/view-syncer/view-syncer-test-util.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-client/src/client/context.ts
packages/zero-client/src/client/inspector/inspector.test.ts
packages/zero-client/src/client/inspector/inspector.ts
packages/zero-client/src/client/inspector/types.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/inspect-down.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts
packages/zql/src/query/measure-push-operator.test.ts
packages/zql/src/query/measure-push-operator.ts
packages/zql/src/query/metrics-delegate.ts

This PR adds inspector metrics for `query-update-server`, enabling measurement of update times per query (`queryID`) and globally across all updates. Metrics are collected via a `MeasurePush` operator in the IVM pipeline, similar to the client-side approach. Inspector responses now include these metrics. Also includes a test fix for metric integration.### Summary
Adds inspector metrics for `query-update-server`, allowing measurement of update times both per query (`queryID`) and globally.
- Collects update time metrics via `MeasurePush` operator in the IVM pipeline (mirroring client-side).
- Inspector responses now include these new metrics.

feat(zero): Add inspector metrics for query-update-server

---

packages/zero-cache/vitest.config.ts

Disable vitest isolation so that a single worker can run multiple files. Increase default timeouts.

chore(zero-cache): increase vitest timeouts, disable isolation

---

packages/zero-cache/src/db/transaction-pool.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts

Use `vi.waitFor()` to deflake a cvr test.
Skip (flakey) transaction pool tests that cover unused functionality.

chore(zero-cache): fix flake, skip obsolete

---

packages/zero-cache/src/services/change-source/pg/initial-sync.ts

This should correctly fix the initial snapshot issue by ensuring that all copy workers start up (and set their snapshots) before the replication session is closed.
Keep the no-wait workaround for win32 only (to address the COPY hang bug in Node win32).

chore(zero-cache): wait for copiers to close before closing replication

---

packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts

Snapshot flakiness was fixed with https://github.com/rocicorp/mono/pull/4767

chore(zero-cache): reenable change-source.pg tests

---

packages/zero-cache/src/custom-queries/transform-query.test.ts
packages/zero-cache/src/custom-queries/transform-query.ts
packages/zero-cache/src/services/view-syncer/client-handler.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/custom-queries.ts
packages/zero-protocol/src/down.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts
packages/zql/src/query/query-impl.ts

If we get an error transforming a custom query, send that error back down to the client.

chore(zero): thread query transform errors down to client

---

apps/zql-viz/package.json

It's blocking create-canary.js from working and I can't figure out why.

chore(zql-viz): Remove zql-viz build step.

---

packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.ts
packages/zero-cache/src/services/change-source/pg/schema/validation.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/validation.ts

User report:
* https://discord.com/channels/830183651022471199/1407339469077745664/1407548096308580454
Error at initial-sync, or halt incremental replication, when a table:
* has `REPLICA IDENTITY NOTHING`
* has `REPLICA IDENTITY INDEX` without an index ([which is equivalent to `NOTHING`](https://www.postgresql.org/docs/current/sql-altertable.html#SQL-ALTERTABLE-REPLICA-IDENTITY))

fix(zero-cache): refuse or halt replication for unsupported replica identities

---

packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

I was getting tons of API calls once I started forcing zbugs to fail transformation.
Makes sense because the queries are not removed from "desired" so we keep trying them.
If a query fails to transform, remove from desired.
We'll need to make a change on the client to track failure and not re-request unless explicitly re-requested (e.g., component unmount and re-mount or a `retry()` call).

chore(zero-cache): remove queries from `desired` if they fail to transform

---

packages/zql/src/builder/builder.ts
packages/zql/src/query/named.test.ts
packages/zql/src/query/named.ts

```ts
const paramSchema = v.tuple([v.string(), v.number()]);
const def = syncedQueryWithContext(
'myQuery',
paramSchema.parse.bind(paramSchema),
(ctx: object, ownerId, createdAt) => {
expect(ctx).toEqual({});
return builder.issue
.where('ownerId', ownerId)
.where('createdAt', '>', createdAt);
},
);
let q = def({}, '123', 123);
expect(q.customQueryID).toEqual({
name: 'myQuery',
args: ['123', 123],
});
const validated = withValidation(def);
q = validated({}, '321', 321);
```
Some weird typing errors I need to work through when using withValidation(withContext( in zbugs -- https://github.com/rocicorp/mono/pull/4784

fix(zero): zod/valita/whatever validator functions take a single arg

---

.github/workflows/bencher-benchmarks-pr.yml
.github/workflows/bencher-benchmarks.yml
.github/workflows/perf-v2.js.yml

Turns out the self hosted runner is more stable as seen in the screenshots

chore: Switch back perf runner to self-hosted

---

apps/zbugs/api/index.ts
apps/zbugs/server/get-query.ts
apps/zbugs/shared/queries.ts
packages/zql/src/query/named.test.ts
packages/zql/src/query/named.ts

This is basically accomplishing two things at a high level:
- Allow callers to treat the results of `syncedQuery` and `syncedQueryWithContext` generically
- Reduce number of concepts related to synced queries and clean up naming
Details:
* Get rid of the concept of "named query". This was confusing me because the thing we were calling a "named query" didn't actually have a name. It's just a function that returns a ZQL query.  Replace with `QueryFn` That ended up being useful to have defined.
* Get rid of separate withContext and withValidation functions. It was nice to have them decomposed, but all these types are gnarly and it's not worth the complexity. In practice, people only need to generalize for this validation case.
* Combine SyncedQuery and SyncedQueryWithContext type into just …

API polish for custom queries

---

packages/analyze-query/src/bin-analyze.ts
packages/analyze-query/src/run-ast.ts
packages/zero-cache/src/db/lite-tables.ts
packages/zero-cache/src/services/analyze.ts
packages/zero-cache/src/services/view-syncer/pipeline-driver.ts

Another step towards making analyze-query's behavior more perfectly match zero-cache.
Without this change some queries that would succeed against zero-cache would fail with an exception with analyze-query.
In particular, if 
1. zero-cache determine that a column C should be part of a table T's primary key because it has a unique index on it
2. column C does not appear in schema.ts for table T
This caused queries involving the 'user' table of zbugs to fail, because of the `githubID` column, which has a unique index on it, but is not in schema.ts.

fix(analyze-query): use replica based tablespecs TableSource schemas to match zero-cache behavior

---

packages/zero-cache/src/auth/jwt.test.ts
packages/zero-cache/src/auth/jwt.ts
packages/zero-cache/src/workers/syncer.test.ts
packages/zero-cache/src/workers/syncer.ts

This is a reapply of https://github.com/rocicorp/mono/pull/4793, with fixes for zbugs.
The `auth` config defaults to an empty string in Replicache here:
https://github.com/rocicorp/mono/blob/842c0d5e6f7f588b3f5cfe7ca3fc6fcbc1879c51/packages/replicache/src/replicache-impl.ts#L444-L447
So `auth` is never `undefined`. This [commit](https://github.com/rocicorp/mono/commit/d5642c1131cb730ab340b826433ac49659ff2e7c) fixes handling this.
---
Changes zero-cache to allow pass-through of a token passed to `auth` without validation if no JWT configs are set, and a mutate & get queries URL are defined. It will also print a warning to the user: `One of jwk, secret, or jwksUrl is not configured - the auth token must be manually verified by the user`.
On the client:
```tsx
import { expoClient } from …
```

feat(zero-cache): added passthrough of auth (again)

---

packages/zero-react/src/mod.ts
packages/zero-react/src/use-query.test.tsx
packages/zero-react/src/use-query.tsx

`useSuspenseQuery` takes the same options as useQuery, plus a new `'suspendUntil'` option.
```
/**
* Whether to suspend until:
* - 'non-empty': the query has non-empty results (non-empty array or defined
*   value for singular results) which may be of result type 'unknown'
*   or the query result type is 'complete' (in which case results may be
*   empty).  This is useful for suspending until there are non-empty
*   optimistic local results, or the query has completed loading from the
* server.
* - 'complete': the query result type is 'complete'.
*
* Default is 'non-empty'.
*/
```
Based on @lewisl9029's contribution https://github.com/rocicorp/mono/pull/4747

feat(zero-react): support for suspense via useSuspenseQuery

---

packages/zero-cache/src/server/inspector-delegate.ts
packages/zero-cache/src/server/syncer.ts
packages/zero-cache/src/services/view-syncer/view-syncer-inspect.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer-test-util.ts
packages/zero-cache/src/services/view-syncer/view-syncer-ttl.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-client/src/client/inspector/inspector.test.ts
packages/zero-client/src/client/inspector/inspector.ts
packages/zero-client/src/client/test-utils.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/inspect-down.ts
packages/zero-protocol/src/inspect-up.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

I decided to revert this temporarily because it's such an important debug feature and I really think we need some way for it to be default-on. Let's talk about what we should do at next team meeting. Can imagine a number of options.
This reverts commit cc32e9efbf533d4ed2d2a5d5aebfcfe9b3233584.

Revert "feat(zero-client): Use admin password for inspector (#4825)"

---

apps/zql-viz/package.json

It got re-enabled in https://github.com/rocicorp/mono/pull/4837 - i think accidentally.

chore(api-viz): disable api-viz again.

---

apps/zbugs/shared/schema.ts
apps/zbugs/src/pages/issue/issue-page.tsx
packages/zero-client/src/client/crud.ts
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/options.ts
packages/zero-client/src/client/zero.ts
packages/zero-client/src/client/zero.type.test.ts
packages/zero-schema/src/builder/schema-builder.ts
packages/zero-schema/src/schema-config.ts

We recently added `enableLegacyMutators` and `enableLegacyQueries`. They disable the relevant features at runtime. But they don't affect the mutators types.
This changes how they are implemented to disable the types too.
I considered putting `enableLegacyMutators` in mutators.ts, which at first seems reasonable, but alas all fields of the mutators object are reflected into namespaces in the API so there's no place for us to put it. This seems fine, anyway this flag is not long for the world.

Fix type hints with `enableLegacyMutators: false`

---

packages/replicache/src/expo/store.ts
packages/replicache/src/kv/sqlite-store.test.node.ts
packages/replicache/src/kv/sqlite-store.ts
packages/replicache/src/persist/collect-idb-databases.ts

This fixes a few issues around close and destroy for the SQLite KV store and the Expo wrapper for it.
The expo wrapper now makes sure it does not call close on an already closed database.
The database manager manages multiple instances to ensure the database behaves as a RWLock. It use multiple connections to do this. These connections are handled by the `SQLiteReadConnectionManager` and the `SQLiteWriteConnectionManager`. However, there was a confusion who owned what and the code ended up trying to finalize (cleanup) prepared statements that belonged to a closed db. The database manager now manages all the cleanup and closing.
The instances managed by the database manager can be in one of two states; open or closed. Since we keep the instances around until the database is destroyed we …

fix(react-native): Fix bugs in close and destroy

---

.github/workflows/bencher-benchmarks-pr.yml
.github/workflows/bencher-benchmarks.yml

I misunderstood. Closer to 1 allows more noise

chore: Bencher perf boundaries

---

packages/zero-cache/src/config/normalize.test.ts
packages/zero-cache/src/config/normalize.ts
packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts

In case adminPassword is not set we generate a cryptographically secure random password and log it.

feat(zero-cache): Generate admin password if not provided

---

packages/replicache/src/expo/store.ts
packages/replicache/src/kv/sqlite-store.ts

The `SQLiteDatabaseManager` has a map of instances that it keys by database name. When someone tells the SQLiteDBManager to close a db by name, it looks up all connections that exist for that DB and closes them.
This was a problem when one Zero instance was being destroyed and another was being created. Both instances use the `replicache_dbs_v0` database so we could get into cases where a closing Zero would nuke the connections of an opening Zero. 
**Example:**
Zero Instance 1 would be closing.
Zero Instance 2 would be opening.
(note: zero.close is async but it is not / can not be awaited in useEffect in ZeroProvider)
The `replicache_dbs_v0` would be opened by Zero Instance 2. The close from Zero Instance 1 would come in.
The SQLiteDBManager would close all connections associated with …

fix(expo-sqlite): do not close a db we're trying to open

---

packages/zero-cache/src/db/lite-tables.test.ts
packages/zero-cache/src/db/lite-tables.ts
packages/zero-cache/src/db/specs.ts
packages/zero-cache/src/services/view-syncer/client-schema.test.ts
packages/zero-cache/src/services/view-syncer/client-schema.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/client-schema.test.ts
packages/zero-protocol/src/client-schema.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts
packages/zero-schema/src/builder/schema-builder.test.ts
packages/zero-schema/src/builder/schema-builder.ts

Include the `primaryKey` from the client's schema in the `ClientSchema` message validated by the zero-cache (and used as part of the IDB hash).
The zero-cache will validate that the `primaryKey` corresponds to an upstream index over non-null columns (order agnostic).
Note that in order to be backwards compatible with old client versions, the `primaryKey` field is optional, and can be made non-optional when bumping the min-supported protocol version to 30+

fix(zero-cache): include and validate the client's primaryKey

---

packages/zero-cache/src/custom-queries/transform-query.test.ts
packages/zero-cache/src/custom-queries/transform-query.ts
packages/zero-cache/src/custom/fetch.test.ts
packages/zero-cache/src/custom/fetch.ts
packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-cache/src/workers/syncer-ws-message-handler.ts
packages/zero-client/src/client/options.ts
packages/zero-client/src/client/zero-idbname.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/connect.ts
packages/zero-protocol/src/protocol-version.test.ts

This PR allows users to customize the `mutate` and `get-queries` URLs on the client.
This functionality was always envisioned but it was broken in the current build and therefore not documented. 
The `mutate` version just wasn't wired up. But the `get-queries` version had a more fundamental problem: `get-queries` happens on behalf of a client-group, not a client. But we are configuring a client with the constructor param. So it was possible for `zero-cache` to get into a situation where it's doing a GET query fetch, but there are multiple clients having different values for the GET query customization URL. 
To fix this on the client, we incorporated the mutate URL, and the get-queries URL into the IDB name. The result is that changing these URLs gives a zero client a different client …

feat(zero): Allow customization of mutate and get-queries URLs on the client

---

apps/zbugs/src/root.tsx

We should probably remove the supporting code too?

chore(zbugs): Remove inspector icon since we're not using it anymore.

---

apps/zbugs/src/debug/query-users.tsx
packages/zero-client/src/client/query-manager.test.ts
packages/zero-client/src/client/query-manager.ts
packages/zero-client/src/client/zero.ts
packages/zero-react/src/use-query.test.tsx
packages/zero-react/src/use-query.tsx
packages/zql/src/ivm/array-view.test.ts
packages/zql/src/ivm/array-view.ts
packages/zql/src/query/query-delegate.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/typed-view.ts

```ts
const [data, details] = useQuery(...);
if (details.type === 'error') {
// do something with result.error
}
```
Coming next is a way to let the user `retry` failed queries. E.g.,
```ts
datails.retry();
```
Might go with a shape more like TanStack's --
https://tanstack.com/query/v4/docs/framework/react/reference/useQuery
which would look like:
```ts
const [data, {type, error, retry}] = useQuery(...);
```

feat(zero-client)!: surface query transform errors to callers of `useQuery`

---

packages/analyze-query/package.json
packages/analyze-query/src/bin-analyze.ts
packages/analyze-query/src/explain-queries.ts
packages/analyze-query/src/run-ast.ts
packages/zero-cache/src/server/inspector-delegate.ts
packages/zero-cache/src/services/analyze.test.ts
packages/zero-cache/src/services/analyze.ts
packages/zero-cache/src/services/view-syncer/view-syncer-test-util.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-client/src/client/inspector/inspector.test.ts
packages/zero-client/src/client/inspector/inspector.ts
packages/zero-client/src/client/inspector/types.ts
packages/zero-protocol/src/analyze-query-result.test.ts
packages/zero-protocol/src/analyze-query-result.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/inspect-down.ts
packages/zero-protocol/src/inspect-up.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts
packages/zql/src/builder/debug-delegate.ts

Add Query Analyse to Inspector
---
This PR adds a new `analyze()` method to Query objects in the Zero inspector, enabling detailed performance analysis of queries.
This uses the server side AST to analyze the query.
What's New
---
- **Query.analyze() method**: New async method that returns query analysis including timing, row counts, execution plans, and warnings
- **Server-side analysis**: New `analyzeQuery()` service function that leverages the existing `analyze-query` package
- **Protocol support**: Extended inspect protocol with `analyze-query` RPC (protocol version 32)
- **Development mode**: Inspector authentication bypassed in dev mode for easier debugging
Usage
---
```typescript
const inspector = await zero.inspect();
const query = await inspector.client.queries()[0];
const result …
```

chore(zero): Add analyze to inspector query

---

packages/shared/src/sentinels.ts
packages/zql/src/ivm/fan-in.ts
packages/zql/src/ivm/push-accumulated.test.ts
packages/zql/src/ivm/push-accumulated.ts

`fan-in` and `union-fan-in` will do nearly identical things in push accumulated changes. Factor the code out.
The one big change is that `union-fan-in` will merge relationships. Added two arguments to handle relationship merging

chore(zql): factor out `push-accumulated`

---

packages/zql/src/ivm/constraint.ts
packages/zql/src/ivm/flipped-join.ts
packages/zql/src/ivm/memory-source.ts
packages/zql/src/ivm/source.test.ts

Pass the connectionComparator rather than the indexComparator to genereateWithStart.
To understand the bug consider this test case
```
function t(c: {
columns?: Record<string, SchemaValue> | undefined;
startData: Row[];
start: Start;
constraint: Constraint;
reverse?: boolean | undefined;
}) {
const sort = [['a', 'asc']] as const;
const s = createSource(
lc,
testLogConfig,
'table',
c.columns ?? {
a: {type: 'number'},
b: {type: 'boolean'},
},
['a'],
);
for (const row of c.startData) {
s.push({type: 'add', row});
}
const out = new Catch(s.connect(sort));
return out.fetch({
constraint: c.constraint,
start: c.start,
reverse: c.reverse,
});
}
test('c1', () => {
expect(
t({
startData: [
{a: 1, b: '1000'},
{a: 2, b: '3000'},
{a: 3, b: '2000'},
{a: 5, b: '1000'},
{a: 6, b: '4000'},
{a: 7, b: …
```

fix(zql): use correct comparator for generateWithStart in MemorySource

---

packages/zero-cache/src/services/view-syncer/cvr-purger.ts

Log `SHOW statement_timeout` to help investigate when cvr gc results in postgres timeouts

chore: log statement_timeout

---

packages/zero/Dockerfile
packages/zero/tool/create-canary.js

Attach [labels](https://docs.docker.com/reference/dockerfile/#label) to the docker image indicating the supported protocol versions of the server to facilitate production / release management.

chore(zero): add build labels to surface protocol version information

---

packages/zero/tool/create-canary.js

Importing asserts.ts would require us to run `npx tsx tool/create-canary.js`. Keep it simple instead.

chore(create-canary): remove dep on asserts.ts

---

packages/zero-cache/src/services/replicator/incremental-sync.test.ts
packages/zero-cache/src/services/replicator/replication-status.test.ts
packages/zero-cache/src/services/replicator/replication-status.ts
packages/zero-events/src/status.ts

Add a `state` field to hold structured data describing the state of a `component` in a StatusEvent, and put the replication state (`tables`, `indexes`, `replicaSize`) in that field.
This will facilitate handling of component events in a generic manner.

chore(zero-event): add a generic "state" field to status events

---

package-lock.json
packages/replicache/package.json
packages/zero-cache/package.json
packages/zero/package.json
packages/zqlite/package.json

- updates to sqlite 3.50
- enables support for scanstat which we need for join planning

chore(zero): update zero-sqlite3 version
