packages/zero-client/src/mod.ts

See: https://discord.com/channels/830183651022471199/1316099148490997841/1319744139591553134

feat(zero): Export Schema type.

---

packages/zero-cache/src/services/view-syncer/view-syncer.ts

Handle errors thrown in the shutdown callback by propagating them to the main `run()` loop.
They otherwise kill the Node process (and in turn, the server).

fix(zero-cache): handle errors in the shutdown callback

---

prod/templates/template.yml

Worked for sandbox (#3432). Rolling out to prod.

fix(prod): disable timeouts for requests to change-streamer

---

prod/templates/template.yml

Apply sandbox changes from #3434 to prod

fix(prod): reduce health check interval

---

packages/zero-cache/src/services/change-streamer/change-streamer-service.ts

Delay accessing the change db until the replication stream has been successfully subscribed to.
This provides the single writer guarantee that the new change-streamer does not miss any changes written by the old change-streamer.

fix(zero-cache): fix changedb race in rep-manager handoff

---

package-lock.json
packages/zero/src/zero-cache-dev.ts

feat(zero): log zero-cache url from zero-cache-dev

---

packages/zero-cache/src/services/change-streamer/pg/change-source.ts

The postgres `max_slot_wal_keep_size` configuration option bounds the amount of WAL kept for replication slots. When replication slots are too far behind, they are invalidated by postgres. This prevents unbounded WAL usage from replication slots that are not kept up to date.
This change detects this scenario and responds by resyncing the replica from scratch.
This allows developers to have partial zero-cache connectivity (e.g. dev instances) by setting a `max_slot_wal_keep_size`, at the expense of resyncing replicas and downstream clients when slots get too far behind.

feat(zero-cache): support invalidation of replication slots via `max_slot_wal_keep_size`

---

apps/zbugs/src/avatar-url-with-size.tsx
apps/zbugs/src/components/avatar-image.tsx
apps/zbugs/src/components/emoji-pill.tsx
apps/zbugs/src/components/nav.tsx
apps/zbugs/src/components/user-picker.tsx
apps/zbugs/src/pages/issue/comment.tsx
apps/zbugs/src/pages/issue/issue-page.tsx

https://bugs.rocicorp.dev/issue/3270

feat(zbugs): Add size to avatar image URLs

---

packages/zql/src/ivm/take.fetch.test.ts
packages/zql/src/ivm/take.ts

If during hydrate, fetching from take's input throws an error this error was masked by take's finally throwing an error with the message 'Unexpected early return prevented full hydration'.
Update the code to only throw 'Unexpected early return prevented full hydration' only in the case of an early return, not in the case of an exception.

fix(zql): prevent take's early return assert from swallowing errors

---

packages/zero-client/src/client/zero-poke-handler.test.ts
packages/zero-client/src/client/zero-poke-handler.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/protocol-version.ts
packages/zero-protocol/src/row-patch.ts

Need to think about this a bit more.

Revert "chore(zero-protocol): bump to v4, start renaming delPatch.id to delPatch.value"

---

packages/zero/README.md

And include instructions on how to build and install locally.

docs(zero): Add README.md

---

packages/zero/Dockerfile
packages/zero/package.json

Package the `litestream` executable and `zero-cache` config.yml template in `@rocicorp/zero` Docker image

feat(zero): add litestream and config.yml to @rocicorp/zero Docker image

---

packages/zero-cache/src/server/main.ts

Fix a bug introduced in #3496 which results in running a `backup-replicator` in the `view-syncer`. The bug itself doesn't affect correctness, but it's certainly a waste of work / space.
Clean up the main logic now that litestream is first-class part of the code. This includes removing some superfluous subscription logic to the backup replicator.

fix(zero-cache): stop running backup-replicator in view-syncers

---

apps/zbugs/src/components/link.tsx
apps/zbugs/src/hooks/use-softnav.ts

A few things were broken:
- j/k were busted because I didn't remember that data- attributes have to be strings.
- the logo no longer soft-nav'd because it was an image nested inside a link.

fix(zbugs): Playing how many times can we fix the same tiny bug.

---

apps/zbugs/schema.ts
apps/zbugs/src/components/filter.tsx
apps/zbugs/src/components/user-picker.tsx
apps/zbugs/src/pages/issue/issue-page.tsx

- for 'creator' show only users who have created a bug
- for 'assignee' show only crew members

fix(zbugs): Show narrower set of users in user pickers:

---

packages/zero-cache/src/services/change-source/pg/initial-sync.ts

This is similar to the usual replication-manager handoff, and is necessary to make an auto-reset work while another replication-manager is still running.

fix(zero-cache): kill the existing PG subscriber before resync

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.pg-test.ts

Increase test timeouts for some of the bigger tests that occasionally timeout in the CI.

chore(zero-cache): increase timeouts for heavy pg tests

---

packages/zqlite/src/table-source.ts

From #3552, presumably put in just for debugging.

chore(zqlite): remove debug console logging

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts

Avoid filling the row record cache for config-only CVR changes.
Although this currently just an optimization, it will be necessary for correctness when we start relying on the replica / schema to rewrite row record keys. In particular, we want continue responding to config-only changes regardless of whether the replica is ready.

chore(zero-cache): avoid fetching rows for config-only CVR changes

---

packages/zero-cache/src/services/view-syncer/cvr-store.ts

Use the same mechanism write-back/write-through cache mechanism for flushing row deletes as we do for row puts. Although the efficiency is not critical since row deletes only happen for row key schema changes, updating the in-memory cache is important, and the cleanest way to do it is to share the same mechanism.

fix(zero-cache): use the RowRecordCache for deletes

---

packages/zero-cache/src/services/change-source/pg/initial-sync.ts

Google Cloud SQL has two roadblocks in initial-sync:
1. `CREATE PUBLICATION FOR TABLES IN SCHEMA ...` is not allowed for the default `postgres` user (requires `superuser` permissions)
2. Creating a replication slot requires the `REPLICATION` role.
This PR fixes issue [2] by altering the current user's role to include `REPLICATION` if replication fails with insufficient privileges.

fix(zero-cache): make replication work for Google Cloud SQL upstreams

---

packages/zero-client/src/mod.ts

See https://discord.com/channels/830183651022471199/1332701718907195392/1333034924055330847

Export `ResultType` from `@rocicorp/zero`

---

packages/zero-client/src/mod.ts
packages/zero-schema/src/builder/table-builder.ts

Moved from https://github.com/rocicorp/mono/pull/3599

Schema type exports

---

packages/zqlite/src/table-source.test.ts
packages/zqlite/src/table-source.ts

#papercut: https://discord.com/channels/830183651022471199/1288232858795769917/1333915691782508576

chore(zero-cache): improve message when unique key is missing

---

packages/zero-client/src/mod.ts

By request from https://discord.com/channels/830183651022471199/1334065615639548005

chore(zero): Expose some types.

---

.gitignore
package-lock.json
packages/zero-cache/package.json
packages/zero-cache/src/scripts/run-query.ts

Automate what I need to do when debugging user reports of slow queries.
https://discord.com/channels/830183651022471199/1332349837554880513/1332359164592128131

feat(zql): explain query plans in debug script

---

packages/zero-cache/src/services/change-source/pg/change-source.ts
packages/zero-cache/src/services/change-streamer/storer.ts

Debugging https://discord.com/channels/830183651022471199/1334328586265563260

chore(zero-cache): add more logging to debug watermark rejections

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/services/change-source/custom/change-source.test.ts

chore(zero-cache): remove deprecated fields from custom change source tests

---

packages/zero-cache/src/services/running-state.ts

even smaller replication pause

feat(zero-cache): reduce initial retry interval to 25ms

---

packages/zero-client/src/client/zero-poke-handler.ts
packages/zero-client/src/client/zero.ts

chore(zero-client): Remove some async/await

---

.github/workflows/bencher-benchmarks-pr.yml
.github/workflows/bencher-benchmarks.yml

chore(zero): Change perf threshold to 0.9

---

packages/replicache/doc/package-lock.json
packages/replicache/doc/package.json

It was complaining about new TS flags.

chore(replicache): Fix docusaurus build

---

package-lock.json
packages/zero-protocol/src/ast.ts
packages/zql-to-sql/package.json
packages/zql-to-sql/src/compiler.output.test.ts
packages/zql-to-sql/src/compiler.ts
packages/zql-to-sql/src/sql.ts
packages/zql-to-sql/tsconfig.json

This is not tested against Postgres yet. Adding PG testing involved some refactoring of the existing test harnesses so I'm splitting that into its own PR for Darick to review, after which I'll test against PG.

feat(zql-to-sql): compile ZQL to SQL

---

packages/zero-solid/src/solid-view.test.ts

These are largely based on array-view.test.ts but adapted to solid-view.

test(zero-solid): Add more tests to solid-view, some of them fail exposing bugs

---

packages/zero-client/src/client/test-utils.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts

By retrying the assertion a few times.

chore(zero-client): Fix flaky test

---

packages/zero-cache/src/services/view-syncer/cvr.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

chore(zero-cache): Refactor putDesiredQueries

---

apps/zbugs/docker/share_sql/base.sql
apps/zbugs/docker/share_sql/index.sql

moved the triggers to index.sql so created / modified  do not get overwritten when copying the data to the upstream db

chore(infra): docker data 1gb, move triggers to index.sql  

---

packages/zero-cache/src/scripts/deploy-permissions.ts

feat(deploy-permissions): output to a sql file (consumable by psql)

---

packages/zero-cache/src/scripts/deploy-permissions.ts
packages/zero-cache/src/scripts/permissions.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.ts
packages/zero-schema/src/name-mapper.ts

feat(zero-deploy-permissions): validate rules before deploying to upstream

---

.github/workflows/sst-prod-deploy.yml
.github/workflows/sst-sandbox-deploy.yml

Context: https://github.com/rocicorp/mono/pull/3737#issuecomment-2645957677

feat(prod): set the glob-free npm tgz filename as the server version

---

packages/zero-cache/src/auth/load-permissions.test.ts
packages/zero-cache/src/auth/write-authorizer.test.ts
packages/zero-cache/src/services/change-source/pg/schema/shard.pg-test.ts
packages/zero-cache/src/services/view-syncer/snapshotter.test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-schema/src/compiled-permissions.ts
packages/zero-schema/src/permissions.test.ts
packages/zero-schema/src/permissions.ts

feat(zero-cache): remove `protocolVersion` from the permissions object

---

package-lock.json
packages/zero-client/src/client/custom.test.ts
packages/zero-client/src/client/custom.ts
packages/zero-client/src/client/options.ts
packages/zero-client/src/client/test-utils.ts
packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-pg/package.json
packages/zero-pg/src/custom.ts
packages/zero-pg/src/db.ts
packages/zero-pg/src/web.ts
packages/zero-pg/tsconfig.json
packages/zero-protocol/src/push.ts
packages/zql/src/mutate/custom.ts

…he server
Based on this design: https://www.notion.so/replicache/User-s-Push-Endpoint-1983bed895458069a83ee2ab73d54b0f

feat(zero-pg): API for custom mutator server SDK

---

prod/sst/sst.config.ts

cwd is the current package dir (i.e. sst)

fix(sst): fix the dir again

---

packages/zero-cache/src/services/life-cycle.ts

To see if this reduces the occurrence of "Task failed ELB health checks"

chore(zero-cache): increase heartbeat timeout from 15 to 20 seconds

---

packages/zero-cache/src/services/mutagen/mutagen.pg-test.ts
packages/zero-cache/src/types/pg.ts

This is the "write" side handling of #3742
https://bugs.rocicorp.dev/issue/3565
https://discord.com/channels/830183651022471199/1288232858795769917/1341076949749071955

fix(zero-cache): fix writes of NUMERIC types

---

packages/zero-cache/src/server/main.ts

This fixes the race condition in which `litestream` starts up when the replicator is vacuuming the replica, resulting in a `db is locked` error:

fix(zero-cache): start litestream after replicator is ready

---

packages/zero-cache/src/services/view-syncer/cvr.test.ts
packages/zero-cache/src/services/view-syncer/cvr.ts

getInactiveQueries needs to look at all clients in the client group since the eviction is based on the client group and not the client.

chore(zero-cache): getInactiveQueries fix

---

packages/shared/src/options.test.ts
packages/shared/src/options.ts

Fix handling of camel-cased ungrouped flags.

fix(shared): fix top-level camel case flags

---

packages/zero-cache/src/services/change-source/pg/schema/published.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/published.ts

User report: https://discord.com/channels/830183651022471199/1343292365561008258/1343303579380744303
Avoid replicating indexes with columns that are not published. This includes generated columns.
Includes the workaround for the PG15 bug in which generated columns are incorrectly listed in `pg_publication_tables.attnames` (even though they are not published).

fix(zero-cache): ignore indexes with unpublished (e.g. generated) columns

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zqlite/src/table-source.test.ts
packages/zqlite/src/table-source.ts

User report: https://discord.com/channels/830183651022471199/1288232858795769917/1343596491066835077
Avoid coercing `null` boolean values to a boolean. Let them be `null`.

fix(zero-cache): correctly handle null boolean values

---

packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

By injecting a fake setTimeout. (Unfortunately, vi.useFakeTimers() do not work with pg tests).

chore(zero-cache): Unflake expire tests

---

.github/workflows/sst-gigabugs-deploy.yml

Upgrade experiment complete (and successful!)

prod(gigabugs): reenable gigabugs cd

---

apps/zbugs/src/components/filter.tsx
apps/zbugs/src/components/label-picker.tsx
apps/zbugs/src/components/nav.tsx
apps/zbugs/src/components/user-picker.tsx
apps/zbugs/src/pages/issue/issue-page.tsx
apps/zbugs/src/pages/list/list-page.tsx
apps/zbugs/src/zero-setup.ts
packages/shared/src/time.ts
packages/zero-cache/src/services/view-syncer/view-syncer.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-pg/src/query.ts
packages/zero-react/src/use-query.test.ts
packages/zero-react/src/use-query.tsx
packages/zero-solid/src/use-query.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/query-internal.ts
packages/zql/src/query/query.ts
packages/zql/src/query/static-query.ts

This moves the ttl to a parameter of materialize. This is a lot simpler.
Update zbugs to use ttl in useQuery and preload.

feat(zero): Add ttl to useQuery and preload

---

packages/zero-cache/src/services/change-source/pg/initial-sync.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.ts

Use SQLite3's batch insert API to copy rows in batches of 50.
This speeds up the initial row copy by over 15% bringing the time for 2.3 MM rows from ~27 secs to ~22.5 secs.

feat(zero-cache): use batch inserts to speed up initial-sync

---

packages/shared/src/objects.test.ts
packages/shared/src/objects.ts

Per our conversation in https://rocicorp.slack.com/archives/C013XFG80JC/p1738806316413399?thread_ts=1738802020.370979&cid=C013XFG80JC
I'm using this in an upcoming PR but I figure it's worth carving out to reduce review overhead.

feat(shared): object mapping helpers

---

packages/zero-cache/src/services/view-syncer/view-syncer.ts

We always `#syncQueryPipelineSet()` after updating the CVR config, so move that logic into the common method.

chore(zero-cache): consolidate cvr update logic

---

package-lock.json
tools/client-simulator/package.json
tools/client-simulator/src/init-connection.json
tools/client-simulator/src/main.ts
tools/client-simulator/tsconfig.json

Used in conjunction with the `load-generator` to exercise `view-syncer` updates.

tool(client-simulator): tool for making sync connections to a zero-cache

---

packages/zero-cache/src/services/view-syncer/snapshotter.ts

This will help debug replication issues like https://discord.com/channels/830183651022471199/1347172642507063368

chore(zero-cache): throw a helpful error if row is missing

---

packages/zero-cache/src/services/view-syncer/cvr-store.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts

We keep the queries around for deleted clients in the CVR store until the query expires. However, the load code was not handling the case where the client was deleted correctly.

fix(zero-cache): Deal with deleted clients in CVR store

---

packages/zero-cache/bench/benchmark.ts
packages/zero-cache/src/auth/read-authorizer.query.test.ts
packages/zero-cache/src/scripts/run-query.ts
packages/zero-client/src/client/context.test.ts
packages/zero-client/src/client/context.ts
packages/zero-client/src/client/options.ts
packages/zero-client/src/client/zero.ts
packages/zql/src/query/query-impl.ts
packages/zql/src/query/test/query-delegate.ts
packages/zqlite/src/test/source-factory.ts

feat(zero): Print out a warning when a query takes a long time to

---

packages/z2s/src/test/chinook/chinook.pg-test.ts

Edits rows to random values then edits them back to their original values. Runs each edit then checks results of queries against pg.

test(zql): add integration tests for `push:edit`

---

apps/zbugs/api/push.ts
packages/zero-cache/src/services/mutagen/mutagen.ts
packages/zero-pg/src/custom.ts
packages/zero-pg/src/web.pg-test.ts
packages/zero-pg/src/web.ts

checks and sets lmid same way we did in existing `mutagen`.

bug(zero-pg): fix last mutation id tracking

---

package-lock.json
packages/z2s/package.json
packages/z2s/src/test/data-gen.ts
packages/zero-cache/package.json
packages/zero-client/src/client/custom.bench.ts
packages/zero-pg/package.json
packages/zql/package.json
packages/zql/src/query/ast-to-zql.test.ts
packages/zql/src/query/ast-to-zql.ts
packages/zql/src/query/expression.ts
packages/zql/src/query/test/data-gen.ts
packages/zql/src/query/test/query-gen.test.ts
packages/zql/src/query/test/query-gen.ts
packages/zql/src/query/test/schema-gen.test.ts
packages/zql/src/query/test/schema-gen.ts
packages/zql/src/query/test/util.ts

This adds a function that takes an AST and returns a string representing the code needed to build that AST using the Query interface.
This is going to be used for the inspector tool.

feat(zql): add astToZQL function

---

packages/zql/src/ivm/schema.ts
packages/zql/src/ivm/view-apply-change.ts

chore(zql): Refactor to share code

---

.github/workflows/bencher-benchmarks-pr.yml
.github/workflows/bencher-benchmarks.yml
.github/workflows/bundle-sizes.js.yml
.github/workflows/js.yml
.github/workflows/perf-smoke.yml
.github/workflows/perf-v2.js.yml
.github/workflows/syncpack.yml
packages/shared/src/custom-key-map.ts
packages/shared/src/custom-key-set.ts

The iterators where not correctly typed and some ts version flagged them.

chore(shared): Fix type of CustomKeyMap and CustomKeySet

---

packages/zql/src/query/query-impl.ts
packages/zql/src/query/query.ts

One remaining case where the ttl was using number

chore(zql): Fix ttl type parameter

---

.github/workflows/js.yml
packages/zql/src/query/ast-to-zql.ts

We have to fetch some depth to be able to get a diff that vitest can use to determine what changed.
I'm using 100 for now but maybe we should go back to `depth: 0` but it was very slow (because we have large stuff in the past).

chore: Test only changes

---

packages/zql/src/query/expression.test.ts
packages/zql/src/query/expression.ts

https://discord.com/channels/830183651022471199/1288232858795769917/1350600609845350471

chore: Bind exists to the expression builder

---

apps/zbugs/package.json
package-lock.json
packages/datadog/package.json
packages/replicache-doc/package.json
packages/replicache-perf/package.json
packages/replicache/package.json
packages/shared/package.json
packages/zero-cache/package.json
packages/zero-client/package.json
packages/zero-protocol/package.json
packages/zero/package.json
packages/zql/package.json
packages/zqlite-zql-test/package.json
packages/zqlite/package.json

chore: Upgrade to TypeScript 5.8

---

packages/zero-cache/src/db/warm.ts
packages/zero-cache/src/db/warmup.ts
packages/zero-cache/src/server/change-streamer.ts
packages/zero-cache/src/server/syncer.ts

This will facilitate investigating user reports of slowness.

chore(zero-cache): log db ping times at startup

---

.github/workflows/sst-gigabugs-deploy.yml
.github/workflows/sst-prod-deploy.yml
.github/workflows/sst-sandbox-deploy.yml
apps/zbugs/README.md
prod/sst/sst.config.ts

Need to point zero-cache to the zbugs api server to handle custom mutations

chore(zbugs): add missing `ZERO_PUSH_URL` environment variables

---

package-lock.json
packages/z2s/package.json
packages/zero-react/package.json
packages/zero-schema/package.json
packages/zero-solid/package.json
tools/ast-to-zql/README.md
tools/ast-to-zql/ast-to-zql.ts
tools/ast-to-zql/ast.json
tools/ast-to-zql/package.json
tools/ast-to-zql/tsconfig.json
tools/client-simulator/package.json
tools/load-generator/package.json
tools/process-tracker/package.json

This is a simple tool that outputs a ZQL query from an AST.
Save the AST to a json file. Then run the following command:
```bash
cat ast.json | bun ast-to-zql.ts
```
```bash
cat ast.json | deno run --allow-sys ast-to-zql.ts
```
````bash
cat ast.json | node --experimental-strip-types --no-warnings ast-to-zql.ts
````

chore: Add a tool for printing AST to zql

---

packages/zero-cache/src/scripts/deploy-permissions.ts

The developer may have deleted the rows in the table.
e.g. https://discord.com/channels/830183651022471199/1288232858795769917/1352314062138249377

fix(zero-deploy-permissions): handle the case where shardConfig is empty

---

packages/zero-cache/src/services/change-streamer/change-streamer-service.pg-test.ts

Test the behavior of resuming a stream at the right watermark after big commit (#4075). 
The test properly fails if the new ready logic is commented out.

chore(zero-cache): unit test for change-stream resumption

---

packages/zero-cache/src/types/streams.ts

No functional change; just more consistent / symmetrical with the inbound logic.

chore(zero-cache): use pipeline() for outbound streams

---

package-lock.json
tools/load-generator/package.json
tools/load-generator/src/main.ts

Add a mode to the `load-generator` to generate new rows (by copying existing rows).
This can be used for testing high bandwidth "download" scenarios.

chore(load-generator): generate new rows in load harness

---

packages/zero-cache/src/services/change-source/pg/schema/ddl.ts
packages/zero-cache/src/services/change-source/pg/schema/init.pg-test.ts
packages/zero-cache/src/services/change-source/pg/schema/init.ts

Fix the upstream schema migration logic for the new event triggers in #4098

chore(zero-cache): Fix event trigger migration

---

packages/zero-cache/src/db/migration-lite.ts
packages/zero-cache/src/server/main.ts
packages/zero-cache/src/services/change-source/replica-schema.ts

User report: https://discord.com/channels/830183651022471199/1354595802332401845/1354874207200346234
https://bugs.rocicorp.dev/issue/3689

fix(zero-cache): handle corrupt sqlite db by resyncing

---

packages/zero-client/src/mod.ts
packages/zero-solid/src/create-zero.ts

timestamp and number were missing, and MutatorDefs not correctly forwarded in Solid.

chore(zero): Fix up a few exports.

---

apps/zbugs/src/components/markdown.tsx
apps/zbugs/src/index.css

Revert "fix(zbugs): Proper nesting under checklists"

---

package-lock.json
packages/analyze-query/README.md
packages/analyze-query/package.json
packages/analyze-query/src/bin.ts
packages/analyze-query/tsconfig.json
packages/zero/package.json
packages/zero/src/analyze-query.ts
packages/zero/tsconfig.server.json

following the pattern from: https://github.com/rocicorp/mono/pull/4065

feat(zero): Add `npx analyze-query`

---

packages/analyze-query/src/bin-analyze.ts

Use Function instead of eval which exposed a bug where we were not awaiting the result.

fix(analyze-query): fix the analyze-query command

---

packages/zero-pg/src/custom.test.ts
packages/zero-pg/src/custom.ts
packages/zero-pg/src/web.pg-test.ts
packages/zero-pg/src/web.ts
packages/zero-pg/tsconfig.json

https://discord.com/channels/830183651022471199/1288232858795769917/1357366018812412085

chore(mutators): allow top level mutators on the server

---

packages/zero-cache/src/services/change-source/pg/logical-replication/stream.pg-test.ts

Fix interleaved transaction test to deterministically commit in the desired order.

chore(zero-cache): fix flaky test

---

packages/z2s/src/compiler.output.test.ts
packages/z2s/src/sql.ts
packages/zero-pg/src/test/schema.ts

User report: https://discord.com/channels/830183651022471199/1358217995188437074/1358218213489508596

fix(z2s): quote user defined types to preserve casing

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/server/runner/config.test.ts

I think this is what you meant?

chore(zero-cache): fix flag so default shows up in help usage

---

apps/zbugs/src/zero-setup.ts
packages/zero-cache/src/services/mutagen/pusher.test.ts
packages/zero-cache/src/services/mutagen/pusher.ts
packages/zero-client/src/client/options.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/connect.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

https://rocicorp.slack.com/archives/C013XFG80JC/p1744651637357629

feat(zero-cache)!: only allow `pushURL` to be configured and not headers

---

apps/zbugs/shared/schema.ts

zubgs strictly uses custom mutators. We do not need write permissions anymore.

feat!(zbugs): remove all write permissions

---

packages/analyze-query/src/bin-cache-stats.ts

check pragmas on the replica file.

chore(cache-stats): replica stats

---

packages/zero-cache/src/services/view-syncer/view-syncer.ts

This existing log line is never prtined:
Either:
a. we have a deadlock
b. the view syncer is shut down
There is 1 more place `if (!this.#stateChanges.active) {` where we bail before calling that log line which would indicate (b) as being the cause.

chore(zero-cache): more logs to debug stuck client groups

---

packages/zero-cache/src/workers/connection.ts

Context: https://discord.com/channels/830183651022471199/1365359347101732894/1365455352447111280

chore(zero-cache): Fix warning message.

---

apps/zbugs/src/pages/list/list-page.tsx

This improves nav performance to search results as we only need to find one page worth of results.

chore(zbugs): Add basic infinite scrolling.

---

packages/zql-integration-tests/src/chinook/chinook.pg-test.ts
packages/zql-integration-tests/src/chinook/schema.ts

Uncovers that:
- Self join is broken 
- `NOT IN` is broken 
- `IN` is broken
- `NOT EXISTS` is broken

chore(z2s): more expansive test coverage 

---

packages/analyze-query/src/bin-analyze.ts
packages/zero-cache/src/services/view-syncer/schema/cvr.ts

These are already in server-name format

fix(analyze-query): do not map asts from the CVR

---

packages/zero-cache/src/types/ws.ts

When a websocket is processing a lot of messages (e.g. a large changelog catchup at the beginning of a change-streamer subscription), it is possible for the initial ping message to be backed up behind those messages, and not processed until it is too late.
Fix the liveness checking logic to accept either pings or messages as a sign of liveness.
User report:
https://discord.com/channels/830183651022471199/1367606405481365674/1368063265594282004

fix(zero-cache): fix websocket liveness check to account for messages

---

packages/zero-cache/src/services/view-syncer/view-syncer.ts

User report:
https://discord.com/channels/830183651022471199/1367957671621296190/1368294818676998215
Catch and handle exceptions thrown from CVR operations in the eviction timer. Otherwise it can crash the server.

fix(zero-cache): handle exceptions in the eviction timer

---

packages/zql-benchmarks/src/chinook-hydration.bench.ts
packages/zql-benchmarks/src/chinook-push.bench.ts
packages/zql/src/ivm/constraint.ts

- unique db name for bench tests
- includes not indexOf

chore(zero): review nits

---

packages/zero-cache/src/services/view-syncer/view-syncer.ts
packages/zero-cache/src/types/streams.ts

Small improvements / clarifications noticed while debugging customer issues.

chore(zero-cache): improve logging

---

packages/zero-cache/src/types/ws.ts

Make the analogous fix for pongs as was done for pings in #4321
User report: 
https://discord.com/channels/830183651022471199/1370057107814088796/1370196000152752178

fix(zero-cache): fix websocket liveness check (again)

---

packages/zero-cache/src/types/ws.ts

chore(zero-cache): fix pong

---

packages/zero-cache/src/services/change-source/pg/logical-replication/stream.ts

PG should at least send a keepalive message every 30 seconds. Log if nothing comes down the stream, to debug session connectivity issues.

chore(zero-cache): log when upstream sends no data

---

packages/zero-cache/src/db/transaction-pool.ts

Go back to logging more information in the transaction pool, but still only for every 1000th statement.

chore(zero-cache): log every 1000th stmt per transaction

---

apps/zbugs/shared/auth.ts
packages/otel/src/log-options.ts
packages/shared/src/valita.test.ts
packages/shared/src/valita.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/db/specs.ts
packages/zero-cache/src/scripts/permissions.ts
packages/zero-cache/src/services/change-source/protocol/current/data.ts
packages/zero-cache/src/services/replicator/schema/change-log.ts
packages/zero-cache/src/services/view-syncer/schema/types.ts
packages/zero-cache/src/workers/replicator.ts
packages/zero-client/src/client/options.ts
packages/zero-protocol/src/ast.ts
packages/zero-protocol/src/client-schema.ts
packages/zero-protocol/src/error.ts
packages/zero-protocol/src/push.ts
packages/zero-schema/src/schema-config.ts

This is such a common pattern that it should be a helper.

chore(shared): Add literalUnion helper

---

packages/zql-benchmarks/src/chinook-push.bench.ts
packages/zql-integration-tests/src/helpers/runner.ts

note to self:
- we should allow asserting expected ranges. E.g., this should behave the same as inserts outside a bound.

chore(zql-bench): benchmark edits to nodes in and outside of take window

---

packages/zql-benchmarks/package.json
packages/zql-benchmarks/src/frontend-analysis.pg-test.ts
packages/zql-integration-tests/src/helpers/runner.ts

If you asked me:
- "How many queries is reasonable to have open?"
- "Should I do many small queries or 1 large query?"
- "Can I do a write for each mouse drag?"
I couldn't answer you. Start building that intuition.

chore(zql): build a sense of UI perf

---

packages/zql-benchmarks/src/frontend-analysis.pg-test.ts

Run:
> `npm run test | glow`
Full output reproduced below
----
A UI may:
1. Need to run many point queries at once (e.g. for a list of items)
2. Have many point queries open at once (e.g. same list of items)
We need to understand the limits of both cases.
- How many point queries can we hydrate at once?
- How many writes per second can we do with many point queries open at once?
How long to hydrate 100 point queries?
100 seems like a reasonable number. The intuition here is that this
could be a few pages of a list or table view.
1,000 point queries could be possible if each cell in a table grabbed its own data.
- Total time: `37.30`p99, `36.02`avg
- Frame budget: 16ms
- FPS: `0.43`p99, `0.44`avg
`2.33`  frames to hydrate 100 point queries which is
~`0.43` fps.
Is this reasonable? Lets …

chore(zql): explore range query perf

---

packages/zero-cache/src/services/change-source/pg/initial-sync.ts

In certain situations Postgres hangs on the final COMMIT after the queries in the read only transaction (e.g. the COPY TO workers) have completed. This hasn't happened at head but did for some in-progress optimizations in the copy code. Add this workaround to head just in case it a random issue that might arise in other contexts.

chore(zero-cache): workaround commit hang issue in development

---

prod/sst/sst.config.ts

Followup to #4335
Farewell, internal load balancer.

chore(prod): decommission the internal load balancer

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/services/change-source/pg/change-source.end-to-mid.pg-test.ts
packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts
packages/zero-cache/src/services/change-source/pg/decommission.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.pg-test.ts
packages/zero-cache/src/services/change-source/pg/initial-sync.ts
packages/zero-cache/src/services/change-source/pg/sync-schema.pg-test.ts
packages/zero-cache/src/types/lite.test.ts
packages/zero-cache/src/types/lite.ts
packages/zql-integration-tests/src/chinook/get-deps.ts
packages/zql-integration-tests/src/compiler-bigint.pg-test.ts
packages/zql-integration-tests/src/compiler-types-with-args.pg-test.ts
packages/zql-integration-tests/src/discord-repro.pg-test.ts
packages/zql-integration-tests/src/helpers/runner.ts
packages/zql-integration-tests/src/helpers/setup.ts

Need to figure out another hanging issue.

Revert "feat(zero-cache): memory-adaptive implementation of initial-sync"

---

packages/zero-cache/src/services/change-source/pg/initial-sync.pg-test.ts

Adds a unit test to the `initial-sync` test suite that triggers the Postgres-hanging bug that happens in the `COPY ... TO` implementation that has been reverted. The hang reproduces when reviving the change, and will be used to vet that the next `COPY ... TO`-based implementation is not susceptible to (or rather, successfully works around) the issue.

chore(zero-cache): add a unit test that triggers the COPY stream PG hang

---

packages/zero-cache/src/server/main.ts

Fixes a race condition in server startup in which the `syncer` workers try to access the replica file before the `serving-replicator` has finished setting it up.
User report:
https://discord.com/channels/830183651022471199/1374183593865384017/1374189675106930769

fix(zero-cache): delay syncer startup until replica file is ready

---

packages/zqlite/src/table-source.ts

User report: 
https://discord.com/channels/830183651022471199/1374859733701230672/1374874463329320991

chore(zqlite): include column name in bigint error message

---

packages/zql/src/query/test/query-gen.ts

The fuzzer now tracks all modifications it makes along the way to building a failing query.
This allows us to binary-search through all forms of the failing query for the simplest failing form and report that as the error.
Manually trying to prune down several hundred line queries to find what caused the failure was getting too tedious.
**Example, the first few generations of a query**
Each modification (limit, exists, order-by, related, modification of sub-query) creates a new generation.
(these queries were generated without sample data hence the random values in `where` clauses)
```ts
stdout | src/query/test/query-gen.test.ts > shrinkable generation
comment.orderBy('id', 'asc')
stdout | src/query/test/query-gen.test.ts > shrinkable generation
comment
.related('author', q => …
```

chore(fuzzer): track query modifications to enable shrinking queries

---

packages/zero-cache/src/services/change-source/pg/copy-runner.ts

Block for the commit timeout to improve connection reuse.

chore(zero-cache): improve copy runner connection reuse

---

packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts

URL to send custom / named query requests to.
Not 100% sure on the name yet but this is the URL to be called to run custom/named queries.

feat(zero-cache): pull url configuration option

---

packages/zero-cache/src/server/runner/zero-dispatcher.ts
packages/zero-cache/src/services/heapz.ts
packages/zero-cache/src/services/statz.ts

Is protected by same admin password as statz.

chore(zero-cache): Add /heapz endpoint for getting a heapdump from node.

---

packages/zero-cache/src/services/view-syncer/pipeline-driver.ts

Existing code avoided iterating the resulting Iterable, but this optimization avoids sending the query to sqlite entirely.

perf(zql): avoid initiating fetch of permission relationships in pipeline driver

---

packages/zero-cache/src/db/pg-copy.ts

This will allow it to be used more flexibly and not require a stream push for every token.

chore(zero-cache): split the TsvParser out of TextTransform

---

packages/zero-client/src/mod.ts

https://discord.com/channels/830183651022471199/1379156287723409552/1381831391255203850

chore(zql): export `PullRow`

---

packages/zero-cache/src/integration/integration.pg-test.ts
packages/zero-cache/src/server/worker-dispatcher.ts

Fixes a bug introduced in the removal of multi-tenant dispatch (#4325) in which invalid websocket requests were not properly being handled.
User report:
* https://discord.com/channels/830183651022471199/1288232858795769917/1382142719404806174

fix(zero-cache): fix handling of invalid websocket requests

---

packages/zero-cache/src/services/view-syncer/schema/cvr.ts
packages/zero-cache/src/services/view-syncer/schema/init.ts

forgot to change this to json before landing the original change.

chore(zero-cache): queryArgs should be `json` not `jsonb`

---

packages/zero-cache/src/services/view-syncer/cvr-store.pg-test.ts
packages/zero-cache/src/services/view-syncer/cvr-store.ts

custom queries which contained a boolean in their argument list would fail to insert.
https://github.com/porsager/postgres/issues/386
https://github.com/porsager/postgres/blob/9b92b65da6a5121545581a6dd5de859c2a70177f/src/types.js#L227

chore(zero-cache): handle json args for custom queries

---

.github/workflows/sst-gigabugs-deploy.yml
.github/workflows/sst-prod-deploy.yml
.github/workflows/sst-sandbox-deploy.yml
prod/sst/sst.config.ts

Revert "chore(zbugs): set pull urls for custom query use"

---

.github/workflows/sst-gigabugs-deploy.yml
.github/workflows/sst-prod-deploy.yml
.github/workflows/sst-sandbox-deploy.yml
prod/sst/sst.config.ts

fixed env vars in github to point to the right place. This should be safe to deploy now 🤞

chore(zbugs): set pull urls for custom query use

---

packages/zql-integration-tests/src/chinook/chinook-fuzz-hydration.pg-test.ts

1k runs seems a bit much for each PR.

chore(zql): less fuzzing in ci

---

apps/zbugs/api/index.ts
package-lock.json
packages/analyze-query/src/bin-analyze.ts
packages/analyze-query/src/bin-transform.ts
packages/shared/package.json
packages/shared/src/dotenv.ts
packages/zero-cache/bench/bench.ts
packages/zero-cache/bench/double.ts
packages/zero-cache/bench/wal-bench.ts
packages/zero-cache/bench/wal2-bench.ts
packages/zero-cache/package.json
packages/zero-cache/src/scripts/deploy-permissions.ts
packages/zero-cache/src/server/runner/main.ts
packages/zero-cache/src/server/runner/run-worker.ts
packages/zero-cache/tool/local.ts
packages/zero/src/zero-cache-dev.ts
tools/client-simulator/src/main.ts
tools/load-generator/src/main.ts

Also remove yellow info text about injecting from .env file.
Fixes https://bugs.rocicorp.dev/issue/3853

fix(zero): Remove red error text when starting tools w/o .env.

---

packages/zero-pg/src/push-processor.pg-test.ts
packages/zero-pg/src/push-processor.ts

Two bugs
There was a race where a mutator could fail for some reason then fail again with OOO or AlreadyProcessed in error mode. If it failed with OOO or AlreadyProcessed, in error mode, we would not catch and handle this.
E.g.,
```
Step 1: runMutator(foo);
Step 2: foo throws new Error();
Step 3: pushProcessor catches error
Step 4: push processor re-runs in error mode
Step 5: error mode throws OOO or AlreadyProcessed
```
The error from step (5) would not be caught. This means the ooo error would not reach the client or, if it was an already processed error, the rest of the mutations would not be processed.
If a mutation returned an error we would break the loop rather then continuing to process the remaining mutations in the array 🤯

fix(custom-mutators): handle errors thrown in errorMode, only break on ooo errors

---

packages/zero-client/src/client/zero.test.ts
packages/zero-client/src/client/zero.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/connect.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

Revert "chore(zero): Add activeClients to initConnection"

---

packages/analyze-query/src/bin-analyze.ts
packages/analyze-query/src/bin-transform.ts
packages/ast-to-zql/src/bin.ts
packages/otel/src/log-options.ts
packages/shared/src/logging.ts
packages/shared/src/options.test.ts
packages/shared/src/options.ts
packages/zero-cache/src/config/zero-config.test.ts
packages/zero-cache/src/config/zero-config.ts
packages/zero-cache/src/scripts/deploy-permissions.ts
packages/zero-cache/src/scripts/permissions.ts
packages/zero/src/zero-cache-dev.ts
packages/zqlite/src/runtime-debug.ts
packages/zqlite/src/table-source.ts

This came up because a user was [encountering several issues](https://discord.com/channels/830183651022471199/1388439235450765412/1388801208877191250) w/ analyze-query:
- No output on errors. This was fallout from some earlier changes I did to logging.
- Unclear how to run in production.
- Not printing stats for sql queries with zero results.
It's kind of a big change to a surprisingly delicate area so I would appreciate a careful review.

Rework logging again

---

packages/zero-cache/src/services/view-syncer/view-syncer.ts

The code created a Timer object but it wasn't using it correctly.

chore(zero-cache): Fix a timer measurement

---

packages/zql/src/ivm/take.push.test.ts

Follow up fixing some test changes in https://github.com/rocicorp/mono/pull/4563

test(zql): update to check pushesWithFetch

---

packages/zero-client/src/client/zero-poke-handler.ts

Doesn't seem ideal to use `map` when handling large pokes

chore(zero): less allocations in poke-handler

---

packages/zero-cache/src/services/change-source/pg/logical-replication/stream.ts

User reports:
* https://discord.com/channels/830183651022471199/1310407465560703030/1382626967639162882
* https://discord.com/channels/830183651022471199/1374582754632536125/1392213387949375579
Generally, a slot that was invalidated due to the wal exceeding the `max_slot_wal_keep_size` manifests as having a `NULL` `restart_lsn`, the detection upon which we auto-reset and resync: https://github.com/rocicorp/mono/blob/c6e73f050b1daf3aabd813a59c73ddd7e004e711/packages/zero-cache/src/services/change-source/pg/change-source.ts#L193
A different manifestation, which can happen when the invalidation happens after the slot check, is when the replication session is started, whereby Postgres the fails the request with an error:
```
"name":"PostgresError",
"severity_local":"ERROR", …
```

fix(zero-cache): handle another manifestation of an invalidated slot

---

packages/zero-client/src/client/active-clients-manager.test.ts

Instead of using a hard coded `sleep(5)` we use `vi.waitFor` which iterates until the condition is met or times out. This should make the test more robust against timing issues, especially in CI environments where the timing can be less predictable.

chore(zero-client): fix active clients test flake

---

packages/zero-client/src/client/active-clients-manager.ts

Follow up to https://github.com/grgbkr

refactor(zero-client): Simplify ActiveClientManager

---

packages/zero-cache/src/server/anonymous-otel-start.test.ts
packages/zero-cache/src/server/anonymous-otel-start.ts

Revert "fix(zero-cache): anonymous otel detect container for fsid, remove taskid"

---

packages/zero-cache/src/services/view-syncer/view-syncer-test-util.ts
packages/zero-cache/src/services/view-syncer/view-syncer-ttl.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

- Fix: Always call `#scheduleExpireEviction` in `#removeExpiredQueries` to ensure consistent timer management for queries with different TTLs.
- Fix: Always call `#scheduleExpireEviction` in `#removeExpiredQueries` even if we had now expired queries at the time.
- Refactor: Add helper functions (addQuery, removeQuery, expectGotDel, etc.) to TTL tests for better maintainability and readability

chore(zero-cache): Always reschedule expire timer

---

packages/zero-cache/src/services/view-syncer/view-syncer-test-util.ts
packages/zero-cache/src/services/view-syncer/view-syncer-ttl.pg-test.ts
packages/zero-cache/src/services/view-syncer/view-syncer.ts

This allows multiple evictions to be batched together, reducing the number of calls to the database and improving performance.

chore(zero-cache): Add some hysteresis to the eviction timer

---

packages/zero-client/src/client/options.ts

See https://discord.com/channels/830183651022471199/1391459722061811752 for context.

docs: fix docs for path segments

---

packages/zero-cache/src/services/litestream/commands.ts

Remove the requirement that a new (version of the) replication-manager be rolled out before the corresponding view-syncer is rolled out. From this release onward, the services can be rolled out in parallel when updating to a new version.
The initial snapshot request that the view-syncer makes to the replication-manager is used to determine whether the replication-manager supports the view-syncer's change-streamer protocol. If the view-syncer's change-streamer protocol is ahead of that of the replication-manager's, the snapshot request will fail, and the view-syncer will continue attempting to reserve a snapshot until it connects to a compatible replication-manager.
(Note that the change-streamer protocol rarely changes, and most of the time a new view-syncer will be compatible with an old …

feat(zero-cache): support parallel rollouts of replication-manager and view-syncer

---

packages/zero-client/src/client/custom.test.ts

https://discord.com/channels/830183651022471199/1387485021685944431/1395051551663329421
In addition, some manual testing --
https://github.com/user-attachments/assets/8c8ec614-59ec-4195-ba9e-9feecc6fc456

chore(zero-client): test that client promise resolution is transactional with write

---

packages/zero-schema/src/permissions.ts

docs: deprecation for write permissions

---

packages/zql-integration-tests/src/helpers/runner.ts

maybe we got a newer version of ts???

chore(zql-integration-tests): fix type error in runner.ts

---

packages/zero-cache/src/services/change-source/pg/change-source.pg-test.ts

By repeating the tests for now :'(

chore(zero-cache): Work around flake in change-streamer tests

---

.github/workflows/bencher-benchmarks-pr.yml
.github/workflows/bencher-benchmarks.yml

Reverts rocicorp/mono#4717
This didn't work

Revert "chore: Add a way to reset bencher base lines"

---

packages/zero/src/server/reaper.ts

chore(zero-cache): add reaper.ts to the zero package

---

packages/zero-cache/src/auth/jwt.test.ts
packages/zero-cache/src/auth/jwt.ts
packages/zero-cache/src/workers/syncer.test.ts
packages/zero-cache/src/workers/syncer.ts

This reverts commit c7047ee33767dd21875ff8c28daad86d26ff4723.

revert: added passthrough of auth

---

packages/zero-cache/src/types/pg.ts

Disable the `statement_timeout` for zero-cache connections unless explicitly set in a `PGSTATEMENT_TIMEOUT` environment variable.
Vanilla postgres does not set a db-level statement timeout, and documentation [explicitly discourages a db-level setting](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-STATEMENT-TIMEOUT):
> Setting statement_timeout in postgresql.conf is not recommended because it would affect all sessions.
However, supabase sets a default to `2min`, which may be reasonable for web-app behavior but tends to cause problems in zero-cache, particularly during initialization.
User reports:
* https://discord.com/channels/830183651022471199/1403518951152947431/1403548267509452850
* https://discord.com/channels/830183651022471199/1378857672375537808/13790082951 …

fix(zero-cache): disable db-level `statement_timeout` for zero-cache connections

---

.github/workflows/bencher-benchmarks-pr.yml
.github/workflows/bencher-benchmarks.yml

chore: Change bencher perf to 70%

---

apps/zbugs/debug.html
apps/zbugs/src/debug/debug-app.tsx
apps/zbugs/src/debug/debug.tsx
apps/zbugs/src/debug/query-users.tsx
apps/zbugs/vite.config.ts

Sometimes you just need to debug something end to end. Having a separate entrypoint in zbugs makes that real easy.

chore(zbugs): debug entrypoint in zbugs

---

packages/zero-cache/src/custom-queries/transform-query.test.ts
packages/zero-cache/src/custom-queries/transform-query.ts

Turns out we started swallowing this exception at some point

fix(zero): close connection on 401 from upstream

---

package-lock.json
packages/analyze-query/package.json
packages/analyze-query/src/run-ast.test.ts
packages/analyze-query/src/run-ast.ts
packages/analyze-query/vitest.config.ts

Also add some tests for analyze-query package

chore(zero): Make sure vendedRowCounts is always defined

---

apps/zql-viz/src/App.tsx
apps/zql-viz/vite.config.ts

zql viz was not updated to use `[delegateSymbol]`

chore(zql-viz): use `delegate`, fix lint

---

packages/zero-client/src/client/inspector/html-dialog-prompt.ts
packages/zero-client/src/client/inspector/lazy-inspector.ts

The builtin `prompt` function does not allow hiding the password.

chore(zero-client): use HTML dialog for password prompt

---

packages/zql-integration-tests/src/chinook/chinook.pg-test.ts

accidentally left this disabled after debugging

chore(zero): enable all chinook tests again

---

packages/zero-cache/src/types/pg.ts

Sending a plain `statement_timeout=0` in the connection settings does not successfully override a corresponding user-level setting.
Adding a measure after it, i.e. `statement_timeout=0s`, works though.  🤷 
User report:
* https://discord.com/channels/830183651022471199/1420477677227348105/1420572595908120617

fix(zero-cache): more forcefully disable the connection-level statement_timeout

---

packages/analyze-query/src/run-ast.test.ts
packages/analyze-query/src/run-ast.ts

Follow up to #4894
https://github.com/rocicorp/mono/pull/4894#discussion_r2350268492

chore(zero-cache): yield in analyzeQuery to avoid blocking

---

apps/zbugs/package.json
apps/zbugs/shared/queries.ts
package-lock.json
packages/zql/package.json

And use zod/mini for smaller bundle size.

chore(zbugs): upgrade zod to 4.x

---

packages/zero-cache/src/auth/write-authorizer.ts
packages/zero-cache/src/services/view-syncer/snapshotter.ts
packages/zqlite/src/table-source.test.ts
packages/zqlite/src/table-source.ts

chore(zero-cache): Always pass table name to fromSQLiteType

---

packages/analyze-query/src/bin-analyze.ts
packages/analyze-query/src/run-ast.test.ts
packages/analyze-query/src/run-ast.ts
packages/zero-client/src/client/inspector/inspector.test.ts
packages/zero-protocol/src/analyze-query-result.ts
packages/zero-protocol/src/ast.test.ts
packages/zero-protocol/src/protocol-version.test.ts
packages/zero-protocol/src/protocol-version.ts

Revert "chore(zero): Rename analyze-query result fields for clarity"
